"""Travel vertical Knowledge-graph projections package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.projections.knowledge import WORKFLOW_TYPE, project

__all__ = ["WORKFLOW_TYPE", "project"]
