"""Pack-owned Knowledge-graph projection for Travel's flight-disruption-
recovery hero (Task 7 Required A).

`project(workflow)` is a plain, deterministic function of
`workflow.payload` only -- exactly the shape
`api.shared.projection_contracts.ProjectionFn` requires
(`Callable[[Workflow], Sequence[EntityWrite | RelWrite | DecisionWrite]]`,
no `app_state`/live world reference). It consumes the real terminal Task-6
evidence the industry-neutral `WorldWorkflowAdapter.decided(...,
evidence=...)` parameter threads onto `workflow.payload["evidence"]` (the
orchestrator's own `_build_output()` dict, generated by
`durable_templates.py`) plus the trigger-time
`workflow.payload["observation"]` that `WorldWorkflowAdapter.start()`
already stores -- never a fabricated fixture-only summary.

Truthful absence: while the workflow is still `awaiting_hitl` (or has
otherwise not yet produced terminal orchestration evidence),
`workflow.payload["evidence"]` does not exist, so `project` returns `[]` --
no partial/fabricated subgraph. Once evidence exists, the trigger-level
subgraph (disruption, booking, party, travellers) is always projected; the
full decision/command/supplier/replacement chain is additionally projected
only once `evidence["command"]` is populated (i.e. a
`reaccommodate_travellers` command was actually authorised and applied) --
a declined/timed-out/no-alternative terminal outcome genuinely has no such
command, so nothing beyond the trigger-level facts is invented for it.

Registered on `WORKFLOW_TYPE`'s entry in the generated
`VerticalPack.projections` mapping (see `pack_templates.py`'s `MANIFEST_PY`
template) -- never on the shared global
`api.server.services.entity_projections.PROJECTIONS` dict, which is itself
only a compatibility snapshot seeded from `active_runtime().pack.projections`
at import time.

Node/relationship vocabulary emitted (all pre-existing, industry-neutral
`EntityGraph` schema; no destructive schema changes):

- ``Workflow`` --TRIGGERED_BY--> ``Asset`` (disruption)
- ``Workflow`` --AFFECTS_ASSET--> ``Asset`` (booking, party)
- ``Asset`` (party) --ASSIGNED_TO--> ``Person`` (each traveller)
- ``Asset`` (old/new flight, hotel, new transfer) --SUPPLIED_BY_ASSET-->
  ``Organisation`` (respective supplier)
- ``Asset`` (old flight) --RELATED_ASSET {role: replaced_by}--> ``Asset``
  (new flight)
- ``Asset`` (booking) --RELATED_ASSET {role: reaccommodated_on}-->
  ``Asset`` (new flight)
- ``Asset`` (booking) --RELATED_ASSET {role: retained_hotel}--> ``Asset``
  (hotel)
- ``Asset`` (booking) --RELATED_ASSET {role: assigned_transfer}-->
  ``Asset`` (new transfer)
- ``Asset`` (old transfer) --RELATED_ASSET {role: replaced_by}-->
  ``Asset`` (new transfer)
- ``Decision`` (decision_id) --DECIDED_ASSET--> ``Asset`` (option) --
  i.e. SELECTED_OPTION
- ``Decision`` (decision_id) --ISSUED_COMMAND--> ``Decision`` (command_id)
- ``Decision`` (command_id) --APPROVED_BY--> ``Decision`` (decision_id)
- ``Decision`` (command_id) --DECIDED_ASSET--> ``Asset`` (booking) -- i.e.
  MUTATED
- ``Decision`` (command_id) --EVALUATED_BY--> ``Decision`` (evaluation_id)
- ``Decision`` (evaluation_id) --RESOLVED_OBJECTIVE--> ``Workflow``

This module is generated by verticals.travel.generator.knowledge_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import json
from typing import Any

from api.server.services.entity_graph import DecisionWrite, EntityWrite, RelWrite
from api.shared.types import Workflow

WORKFLOW_TYPE = "flight-disruption-recovery"


def _json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, default=str)


def project(workflow: Workflow) -> list[EntityWrite | RelWrite | DecisionWrite]:
    payload = workflow.payload if isinstance(workflow.payload, dict) else {}
    evidence = payload.get("evidence")
    if not isinstance(evidence, dict):
        return []

    observation = payload.get("observation")
    observation = observation if isinstance(observation, dict) else {}
    workflow_id = workflow.id
    sw = (workflow_id,)

    booking_id = str(evidence.get("booking_id") or observation.get("booking_id") or "")
    party_id = str(evidence.get("party_id") or observation.get("party_id") or "")
    disruption_id = str(observation.get("disruption_id") or "")
    old_flight_id = str(observation.get("flight_id") or "")
    old_transfer_id = str(observation.get("old_transfer_id") or "")
    old_flight = observation.get("old_flight") or {}
    trigger_old_supplier_id = str(old_flight.get("supplier_id") or "")
    member_customer_ids = [str(c) for c in (observation.get("member_customer_ids") or [])]
    hotel_id = str(observation.get("hotel_id") or "")
    hotel_supplier_id = str(observation.get("hotel_supplier_id") or "")

    if not workflow_id or not booking_id:
        return []

    ops: list[EntityWrite | RelWrite | DecisionWrite] = []

    # -- trigger-level subgraph: real from the moment the workflow opened,
    # regardless of the eventual terminal outcome. ------------------------
    if disruption_id:
        ops.append(EntityWrite(
            kind="Asset", id=disruption_id,
            attrs={
                "kind": "disruption",
                "identifier": disruption_id,
                "attributes": _json({"trigger_flight_id": old_flight_id}),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(workflow_id, "TRIGGERED_BY", disruption_id))

    ops.append(EntityWrite(
        kind="Asset", id=booking_id,
        attrs={
            "kind": "booking",
            "identifier": booking_id,
            "attributes": _json({"party_id": party_id}),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(workflow_id, "AFFECTS_ASSET", booking_id, attrs={"role": "booking"}))

    if party_id:
        ops.append(EntityWrite(
            kind="Asset", id=party_id,
            attrs={
                "kind": "party",
                "identifier": party_id,
                "attributes": _json({
                    "booking_id": booking_id,
                    "member_customer_ids": member_customer_ids,
                }),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(workflow_id, "AFFECTS_ASSET", party_id, attrs={"role": "party"}))
        for cus_id in member_customer_ids:
            ops.append(EntityWrite(
                kind="Person", id=cus_id,
                attrs={
                    "role": "traveller",
                    "attributes": _json({"booking_id": booking_id, "party_id": party_id}),
                },
                source_workflows=sw,
            ))
            ops.append(RelWrite(party_id, "ASSIGNED_TO", cus_id))

    if old_flight_id:
        ops.append(EntityWrite(
            kind="Asset", id=old_flight_id,
            attrs={
                "kind": "flight",
                "identifier": old_flight_id,
                "status": "disrupted",
                "attributes": _json({"supplier_id": trigger_old_supplier_id}),
            },
            source_workflows=sw,
        ))

    if old_transfer_id:
        ops.append(EntityWrite(
            kind="Asset", id=old_transfer_id,
            attrs={
                "kind": "transfer",
                "identifier": old_transfer_id,
                "status": "replaced",
                "attributes": _json({"booking_id": booking_id}),
            },
            source_workflows=sw,
        ))

    if hotel_id:
        ops.append(EntityWrite(
            kind="Asset", id=hotel_id,
            attrs={
                "kind": "hotel",
                "identifier": hotel_id,
                "attributes": _json({"supplier_id": hotel_supplier_id}),
            },
            source_workflows=sw,
        ))
        if hotel_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=hotel_supplier_id,
                attrs={"name": hotel_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(hotel_id, "SUPPLIED_BY_ASSET", hotel_supplier_id))

    # -- decision/command/evaluation chain: only once a
    # reaccommodate_travellers command was actually authorised and applied.
    # A declined/timed-out/wrong_actor/no_alternative terminal outcome
    # never reaches TravelRecoveryBuildCommand, so `command` stays `None`
    # and there is genuinely nothing beyond the trigger-level facts above
    # to project -- returning early here is truthful, not a shortcut. ------
    command = evidence.get("command")
    if not isinstance(command, dict):
        return ops

    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    option_id = str(cmd_payload.get("option_id") or evidence.get("option_id") or "")
    new_flight_id = str(cmd_payload.get("new_flight_id") or "")
    new_transfer_id = str(cmd_payload.get("new_transfer_id") or "")
    old_supplier_id = str(cmd_payload.get("old_supplier_id") or "")
    new_supplier_id = str(cmd_payload.get("new_supplier_id") or "")
    cmd_hotel_supplier_id = str(cmd_payload.get("hotel_supplier_id") or hotel_supplier_id or "")
    new_transfer_supplier_id = str(cmd_payload.get("new_transfer_supplier_id") or "")
    decision_id = str(cmd_payload.get("decision_id") or "")
    command_id = str(command.get("command_id") or "")
    decision_outcome = str(cmd_payload.get("decision_outcome") or "")
    decided_by = str(cmd_payload.get("decided_by") or "")
    reasoning = str(evidence.get("reasoning") or "")

    if not option_id or not decision_id or not command_id:
        # Malformed/partial command evidence -- truthfully stop at the
        # trigger-level subgraph rather than emit decision/command nodes
        # keyed by an empty id.
        return ops

    evaluation_id = f"EVAL-{workflow_id}-{option_id}"

    ops.append(EntityWrite(
        kind="Asset", id=option_id,
        attrs={
            "kind": "recovery_option",
            "identifier": option_id,
            "attributes": _json({
                "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
                "arrival_delay_minutes": cmd_payload.get("arrival_delay_minutes"),
                "material_changes": cmd_payload.get("material_changes"),
                "requires_approval": cmd_payload.get("requires_approval"),
            }),
        },
        source_workflows=sw,
    ))

    if new_flight_id:
        ops.append(EntityWrite(
            kind="Asset", id=new_flight_id,
            attrs={
                "kind": "flight",
                "identifier": new_flight_id,
                "status": "reaccommodated",
                "attributes": _json({"supplier_id": new_supplier_id}),
            },
            source_workflows=sw,
        ))
        if old_flight_id:
            ops.append(RelWrite(old_flight_id, "RELATED_ASSET", new_flight_id, attrs={"role": "replaced_by"}))
        ops.append(RelWrite(booking_id, "RELATED_ASSET", new_flight_id, attrs={"role": "reaccommodated_on"}))
        if new_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=new_supplier_id,
                attrs={"name": new_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(new_flight_id, "SUPPLIED_BY_ASSET", new_supplier_id))

    if old_flight_id and old_supplier_id:
        ops.append(EntityWrite(
            kind="Organisation", id=old_supplier_id,
            attrs={"name": old_supplier_id, "kind": "supplier"},
            source_workflows=sw,
        ))
        ops.append(RelWrite(old_flight_id, "SUPPLIED_BY_ASSET", old_supplier_id))

    if hotel_id:
        ops.append(RelWrite(booking_id, "RELATED_ASSET", hotel_id, attrs={"role": "retained_hotel"}))
        if cmd_hotel_supplier_id and cmd_hotel_supplier_id != hotel_supplier_id:
            # Defensive: honour the command's own copy of the supplier id
            # if it ever differs from the trigger-time observation's copy
            # (should not happen -- both come from the same seed data).
            ops.append(EntityWrite(
                kind="Organisation", id=cmd_hotel_supplier_id,
                attrs={"name": cmd_hotel_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(hotel_id, "SUPPLIED_BY_ASSET", cmd_hotel_supplier_id))

    if new_transfer_id:
        ops.append(EntityWrite(
            kind="Asset", id=new_transfer_id,
            attrs={
                "kind": "transfer",
                "identifier": new_transfer_id,
                "attributes": _json({"supplier_id": new_transfer_supplier_id}),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(booking_id, "RELATED_ASSET", new_transfer_id, attrs={"role": "assigned_transfer"}))
        if old_transfer_id:
            ops.append(RelWrite(
                old_transfer_id, "RELATED_ASSET", new_transfer_id,
                attrs={"role": "replaced_by"},
            ))
        if new_transfer_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=new_transfer_supplier_id,
                attrs={"name": new_transfer_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(new_transfer_id, "SUPPLIED_BY_ASSET", new_transfer_supplier_id))

    # -- decision / command / evaluation chain ---------------------------
    ops.append(EntityWrite(
        kind="Decision", id=decision_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "approve_material_change",
            "persona_role": decided_by,
            "verdict": decision_outcome,
            "reason": reasoning,
            "attributes": _json({
                "decision_id": decision_id,
                "option_id": option_id,
                "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
                "material_changes": cmd_payload.get("material_changes"),
                "requires_approval": cmd_payload.get("requires_approval"),
            }),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(decision_id, "DECIDED_ASSET", option_id))  # SELECTED_OPTION

    ops.append(EntityWrite(
        kind="Decision", id=command_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "reaccommodate",
            "persona_role": str(command.get("issued_by") or ""),
            "verdict": "issued",
            "reason": f"reaccommodate_travellers command for option {option_id}",
            "attributes": _json({
                "command_id": command_id,
                "command_type": command.get("type"),
                "option_id": option_id,
                "booking_id": booking_id,
                "party_id": party_id,
                "old_flight_id": old_flight_id,
                "new_flight_id": new_flight_id,
                "old_supplier_id": old_supplier_id,
                "new_supplier_id": new_supplier_id,
                "hotel_id": hotel_id,
                "hotel_supplier_id": cmd_hotel_supplier_id or hotel_supplier_id,
                "new_transfer_id": new_transfer_id,
                "new_transfer_supplier_id": new_transfer_supplier_id,
                "traveller_ids": member_customer_ids,
            }),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(decision_id, "ISSUED_COMMAND", command_id))
    ops.append(RelWrite(command_id, "APPROVED_BY", decision_id))
    ops.append(RelWrite(command_id, "DECIDED_ASSET", booking_id))  # MUTATED

    outcome = payload.get("outcome") if isinstance(payload.get("outcome"), dict) else None
    eval_attributes: dict[str, Any] = {
        "evaluation_id": evaluation_id,
        "command_id": command_id,
        "booking_id": booking_id,
        "party_id": party_id,
    }
    if outcome is not None:
        eval_attributes["outcome_status"] = outcome.get("status")
        eval_attributes["final_measurements"] = outcome.get("final_measurements")
    ops.append(EntityWrite(
        kind="Decision", id=evaluation_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "evaluate",
            "verdict": str(outcome.get("status")) if outcome is not None else "",
            "reason": "generic outcome evaluator" if outcome is not None else "",
            "attributes": _json(eval_attributes),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(command_id, "EVALUATED_BY", evaluation_id))
    ops.append(RelWrite(evaluation_id, "RESOLVED_OBJECTIVE", workflow_id))

    return ops
