"""Travel vertical flight-disruption-recovery package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.recovery.planner import (
    AUTO_APPROVE_BOUND_GBP,
    RecoveryOption,
    plan_recovery_options,
)

__all__ = ["AUTO_APPROVE_BOUND_GBP", "RecoveryOption", "plan_recovery_options"]
