/**
 * Section 2 — The analogy.
 *
 * The Gutenberg illustration is generated by `scripts/generate_blueprint_image.py`
 * and written to `public/gutenberg.png`. Re-run the script when the prompt in
 * docs/archive/blueprint.md changes.
 */
export function Analogy() {
  return (
    <section className="section section--full analogy">
      <div className="analogy__image-frame">
        <img
          src={`${import.meta.env.BASE_URL}gutenberg.png`}
          alt="Two-panel illustration: a medieval scriptorium where each book is hand-illuminated, beside a Gutenberg-era print shop where a compositor sets pages from a reusable case of metal type."
        />
      </div>
      <p className="caption analogy__caption">
        Hand-illuminated, one volume at a time. Or set from a case of type that
        can be reset for the next page.
      </p>
    </section>
  );
}
