"""Codegen for author-entity-projection (TASK-012).

Pure function :func:`render_projection` that turns a v4 brief into the
source of one ``api/server/services/entity_projections/<wt_snake>.py``
module. Output shape mirrors the twelve hand-written Phase 1
projections so Phase 7 backfill can compare them for semantic
equivalence.

Notes on the rendering:

* The function is named ``project`` (Phase 1 PAT-005 — the registry
  binds a single bare callable per module).
* Imports are limited to:
    ``api.server.services.entity_projections`` (DecisionWrite,
    EntityWrite, RelWrite, build_decision, slug)
    + ``api.shared.types`` (Workflow).
* This codegen emits ``EntityWrite`` + ``RelWrite`` only. The
  ``DecisionWrite`` calls land via ``author-decision-mapping``'s
  Cypher codegen; the projection module reserves the import.
* Attribute paths in the brief use dotted ``payload.<key>...``
  notation; the codegen renders them as ``p.get("<key>", ...)``
  chains with sensible string-coercion defaults.
"""
from __future__ import annotations

from typing import Iterable

from _shared.brief_validator import SchemaError, validate_brief

__all__ = ["SchemaError", "render_projection"]


_ID_PREFIX = {
    "Person": "PERSON",
    "Organisation": "ORG",
    "Asset": "ASSET",
    "Money": "MONEY",
    "Decision": "DEC",
    "Place": "PLACE",
    "Period": "PERIOD",
}

_VAR_BY_KIND = {
    "Person": "person",
    "Organisation": "org",
    "Asset": "asset",
    "Money": "money",
    "Decision": "decision",
    "Place": "place",
    "Period": "period",
}


def _payload_to_get(ref: str) -> str:
    """Translate a ``payload.<a>.<b>.<c>`` ref to a Python expression
    that reads from ``p`` with `.get` chains and a sensible default.
    """
    if not ref.startswith("payload."):
        raise ValueError(f"ref must start with 'payload.': {ref!r}")
    parts = ref.split(".")[1:]
    if len(parts) == 1:
        return f'p.get({parts[0]!r})'
    expr = f'(p.get({parts[0]!r}) or {{}})'
    for k in parts[1:-1]:
        expr = f'({expr}.get({k!r}) or {{}})'
    expr = f'{expr}.get({parts[-1]!r})'
    return expr


def _attr_render(attrs: dict[str, str], indent: str) -> str:
    if not attrs:
        return "{}"
    lines = [f"{indent}    {k!r}: str({_payload_to_get(v)} or ''),"
             for k, v in attrs.items()]
    return "{\n" + "\n".join(lines) + f"\n{indent}}}"


def _entity_block(idx: int, ent: dict, var_names: dict[str, str]) -> list[str]:
    """Render one entity's id var + EntityWrite append."""
    kind = ent["kind"]
    ref = ent["ref_field"]
    source = ent.get("source") or ""
    var_base = _VAR_BY_KIND.get(kind, kind.lower())
    var = f"{var_base}_{idx}_id"
    var_names[ref] = var
    prefix = _ID_PREFIX.get(kind, kind.upper())
    source_part = f"-{source}" if source else ""
    ref_expr = _payload_to_get(ref)
    lines = [
        f'    {var} = f"{prefix}{source_part}-" + slug(str({ref_expr} or "unknown"))',
    ]

    attr_pairs: list[str] = []
    if source:
        attr_pairs.append(f'        "kind": {source!r},')
    for col, payload_ref in (ent.get("attributes") or {}).items():
        attr_pairs.append(
            f'        {col!r}: str({_payload_to_get(payload_ref)} or ""),'
        )
    attrs_block = "{\n" + "\n".join(attr_pairs) + "\n    }" if attr_pairs else "{}"

    lines.append("    ops.append(EntityWrite(")
    lines.append(f'        kind={kind!r},')
    lines.append(f"        id={var},")
    lines.append(f"        attrs={attrs_block},")
    lines.append("        source_workflows=sw,")
    lines.append("    ))")
    return lines


def _rel_block(src_var: str, rel: dict, var_names: dict[str, str]) -> list[str]:
    rkind = rel["kind"]
    tgt_ref = rel["target_ref"]
    tgt_var = var_names.get(tgt_ref)
    if tgt_var is None:
        raise SchemaError(
            path="entities[?].relations[?].target_ref",
            reason=f"target_ref {tgt_ref!r} not bound to any entity id var",
        )
    return [
        "    ops.append(RelWrite(",
        f"        src_id={src_var},",
        f'        rel={rkind!r},',
        f"        dst_id={tgt_var},",
        "    ))",
    ]


_HEADER = '''"""Projection: {workflow_type} (compose-domain v4 codegen).

Auto-generated by docs/superpowers/skills/compose-domain/sub-skills/author-entity-projection/codegen.py
from the brief at docs/superpowers/specs/{workflow_type}-brief.yaml.
DO NOT EDIT BY HAND — regenerate via `compose-domain --re-projection-only`.
"""
from __future__ import annotations

from api.server.services.entity_projections import (
    DecisionWrite,
    EntityWrite,
    RelWrite,
    build_decision,
    slug,
)
from api.shared.types import Workflow

WORKFLOW_TYPE = "{workflow_type}"


def project(workflow: Workflow) -> list[EntityWrite | RelWrite | DecisionWrite]:
    p = workflow.payload or {{}}
    sw = (workflow.id,)
    ops: list[EntityWrite | RelWrite | DecisionWrite] = []

'''


def render_projection(brief: dict) -> tuple[str, str]:
    """Render ``(module_filename, body)`` for a v4 brief.

    ``module_filename = brief["domain"]["workflow_type"].replace("-", "_") + ".py"``
    """
    validate_brief(brief)

    domain = brief.get("domain") or {}
    workflow_type = domain.get("workflow_type")
    if not workflow_type:
        raise SchemaError(
            path="domain.workflow_type",
            reason="domain.workflow_type required to render projection",
        )

    entities = brief.get("entities") or []
    var_names: dict[str, str] = {}
    body_lines: list[str] = []

    for i, ent in enumerate(entities):
        body_lines.extend(_entity_block(i, ent, var_names))

    # Second pass: emit relations now that all id vars are bound.
    for i, ent in enumerate(entities):
        src_ref = ent["ref_field"]
        src_var = var_names[src_ref]
        for rel in ent.get("relations") or []:
            body_lines.extend(_rel_block(src_var, rel, var_names))

    if not body_lines:
        body_lines.append("    # (No entities declared — projection is a no-op.)")

    # Stash decided_on var names per entity ref so downstream
    # author-decision-mapping can render `decided_on=(<var>, ...)`
    # without re-running this codegen.
    body = _HEADER.format(workflow_type=workflow_type) + "\n".join(body_lines) + "\n\n    return ops\n"

    filename = workflow_type.replace("-", "_") + ".py"
    return filename, body
