"""Travel vertical world package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.

Deliberately side-effect-free: this package must not eagerly re-export
`TravelWorld` here, because `verticals.travel.worlds.scenario` imports
`verticals.travel.actions.commands`, which imports
`verticals.travel.worlds.model` -- and importing any `verticals.travel.worlds`
submodule first runs this file. An eager re-export here would make that
import chain circular back through this package before
`verticals.travel.actions.commands` finishes initializing. Import
`TravelWorld` from `verticals.travel.worlds.scenario` directly instead.
"""
from __future__ import annotations

__all__: list[str] = []
