"""Direct, actor-world-disabled diagnostics for the Travel pack.

This module constructs a fresh, private deterministic TravelWorld only to
derive the same sensor event and Durable observation as the live world. It
never starts an actor-world service and never applies the resulting command,
so the generic diagnostic route can prove Durable/API recovery honestly while
the live actor world is intentionally disabled.

Generated by verticals.travel.generator.world_templates; do not hand-edit.
"""
from __future__ import annotations

from typing import Any

from verticals.travel.worlds.scenario import TravelWorld

_WORKFLOW_TYPE = "flight-disruption-recovery"
_TARGET_FLIGHT_ID = "FLT-ZV204"
_DISRUPTION_MINUTE = 180.0


def build_diagnostic_input(
    workflow_type: str,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return real derived input for the one supported direct diagnostic.

    The source sensor comes from a private run of the exact autonomous
    cancellation scenario. A diagnostic-specific transport id prevents this
    disabled-world run from being mistaken for a live actor-world journal
    event, while `source_sensor_event_id` preserves its real causal source.
    """
    if workflow_type != _WORKFLOW_TYPE:
        raise ValueError(f"unsupported Travel diagnostic workflow: {workflow_type!r}")

    world = TravelWorld(seed=42)
    world.run(_DISRUPTION_MINUTE)
    source = next(
        event
        for event in world.runtime.journal
        if event.type == "sensor.tripped" and event.target_id == _TARGET_FLIGHT_ID
    )
    source_event = source.to_dict()
    source_event_id = source_event["event_id"]
    diagnostic_trace_id = f"diagnostic-{source_event.get('trace_id') or source_event_id}"
    diagnostic_event = {
        **source_event,
        "event_id": f"diagnostic-{source_event_id}",
        "trace_id": diagnostic_trace_id,
        "payload": {
            **(source_event.get("payload") or {}),
            "source_sensor_event_id": source_event_id,
            "diagnostic": True,
        },
    }
    observation = world.build_observation(source_event, now=world.runtime.now)
    observation["trace_id"] = diagnostic_trace_id
    observation["evidence_event_ids"] = [source_event_id]
    return diagnostic_event, observation
