"""Dataclasses for the Travel vertical's deterministic, synthetic world.

Every record is a small, mutable dataclass carrying a real string "id" and
a "last_event_id" that always names the most recent causal journal event
that created or mutated it. There is no decorative or random state: every
field change in verticals.travel.worlds.scenario is paired with a journal
event that names the record (as actor or target) and carries the exact
new field values, so "last_event_id" evidence always matches final state.

This module is generated by verticals.travel.generator.world_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Airport:
    """A real-world-shaped, synthetic UK departure airport."""

    id: str
    name: str
    city: str
    country: str
    last_event_id: str | None = None


@dataclass
class Destination:
    """A holiday destination package bookings travel to."""

    id: str
    name: str
    country: str
    last_event_id: str | None = None


@dataclass
class Supplier:
    """A third-party supplier: airline, hotelier or transfer operator."""

    id: str
    name: str
    kind: str  # "airline" | "hotelier" | "transfer_operator"
    last_event_id: str | None = None


@dataclass
class StaffMember:
    """A tour-operator staff member and the most recent action they took."""

    id: str
    name: str
    role: str  # "adviser" | "operations" | "destination" | "finance"
    last_action: str | None = None
    last_event_id: str | None = None


@dataclass
class Customer:
    """An individual customer. "status" tracks their own booking journey."""

    id: str
    name: str
    email: str
    status: str = "new"  # "new" -> "browsing" -> "engaged" -> "booked"
    last_event_id: str | None = None


@dataclass
class TravellingParty:
    """A group of customers travelling together on one itinerary.

    "state" is the party's lifecycle stage and "location" is its current
    real-world position (a home marker, an airport id, a flight id, a
    destination id, or a hotel id) -- both only ever change through a
    matching causal journal event.
    """

    id: str
    lead_customer_id: str
    member_customer_ids: tuple[str, ...]
    size: int
    state: str
    location: str
    last_event_id: str | None = None


@dataclass
class Flight:
    """A scheduled flight operated by a supplier airline.

    "base_fare_gbp" is the deterministic, reference-data-fixed GBP cost of
    reaccommodating one affected party onto this flight as a
    flight-disruption-recovery replacement -- read directly as an
    already-incremental figure (never subtracted against the disrupted
    flight's own fare), so it is only meaningful on a flight that is a
    candidate replacement. It is 0.0 on every flight seeded as an ordinary,
    never-disrupted itinerary leg.
    """

    id: str
    supplier_id: str
    origin_airport_id: str
    destination_id: str
    scheduled_departure: float
    scheduled_arrival: float
    capacity: int
    reserved: int
    status: str  # "scheduled" -> "departed" -> "arrived"
    base_fare_gbp: float = 0.0
    last_event_id: str | None = None


@dataclass
class Hotel:
    """A contracted hotel at a destination."""

    id: str
    name: str
    destination_id: str
    supplier_id: str
    star_rating: int
    last_event_id: str | None = None


@dataclass
class RoomAllotment:
    """A hotel's contracted room inventory for this world.

    Conservation always holds: 0 <= occupied <= reserved <= allotment <=
    total.
    """

    id: str
    hotel_id: str
    total: int
    allotment: int
    reserved: int
    occupied: int
    last_event_id: str | None = None


@dataclass
class Transfer:
    """A resort transfer tied to exactly one flight arrival."""

    id: str
    destination_id: str
    flight_id: str
    supplier_id: str
    capacity: int
    reserved: int
    status: str  # "scheduled" -> "in_progress" -> "completed"
    last_event_id: str | None = None


@dataclass
class Quote:
    """A price quote an adviser prepares for a travelling party."""

    id: str
    party_id: str
    customer_id: str
    adviser_id: str
    price: float | None
    status: str  # "requested" -> "offered" -> "converted"
    last_event_id: str | None = None


@dataclass
class Booking:
    """A confirmed package booking converted from a quote.

    "status" is either the two-step "confirmed" -> "deposit_paid" -> "paid"
    ordinary sales journey, or a direct "confirmed" -> "paid" one-shot
    package sale (verticals.travel.actions.commands.confirm_package_booking).
    A booking can terminate as "cancelled" (cancellation-refund or a
    payment-exception release). "recovery_status" stays `None` unless a
    flight-disruption-recovery command has moved this booking onto a
    replacement flight/transfer, in which case it becomes
    `"reaccommodated"` -- real, queryable evidence distinct from the
    ordinary sales "status" progression above.
    """

    id: str
    quote_id: str
    party_id: str
    customer_id: str
    flight_id: str
    hotel_id: str
    allotment_id: str
    transfer_id: str
    rooms: int
    total_price: float
    status: str
    recovery_status: str | None = None
    last_event_id: str | None = None


@dataclass
class Payment:
    """A successful payment against a booking."""

    id: str
    booking_id: str
    kind: str  # "deposit" | "balance" | "full" (one-shot sale)
    amount: float
    last_event_id: str | None = None


@dataclass
class Refund:
    """A refund issued against a cancelled booking.

    Created by verticals.travel.actions.commands.cancel_and_refund_booking.
    """

    id: str
    booking_id: str
    amount: float
    reason: str
    status: str  # "issued"
    last_event_id: str | None = None


@dataclass
class Disruption:
    """A reported disruption against a resource.

    Reported by TravelWorld.report_disruption and resolved by whichever of
    the eight verticals.travel.actions.commands handlers accepts a command
    naming it. "status" moves "reported" -> "resolved" only on a successful
    command; a rejected command never touches it.
    """

    id: str
    resource_id: str
    kind: str
    reported_at: float
    status: str = "reported"
    last_event_id: str | None = None


@dataclass
class CareAction:
    """A customer-care action issued against a booking's travelling party.

    Created by verticals.travel.actions.commands.issue_customer_care_action.
    "kind" is "notification" (no cost) or "goodwill_gesture" (a bounded GBP
    gesture, checked against the issuing role's authority).
    """

    id: str
    booking_id: str
    party_id: str
    kind: str  # "notification" | "goodwill_gesture"
    amount_gbp: float
    message: str
    status: str  # "issued"
    last_event_id: str | None = None


@dataclass
class RecoveryDecision:
    """A HITL or auto-approval decision against one flight-disruption-recovery.

    Created by the option-based path of
    verticals.travel.actions.commands.reaccommodate_travellers once a real
    Durable orchestrator instance's TravelRecoveryApproval decision (or its
    own auto-approval for a bounded, non-material option) has been
    independently re-validated. One decision per workflow_id: a declined,
    timed-out or malformed decision never reaches this handler at all, so
    every RecoveryDecision that exists always has "outcome" of "approved"
    or "auto_approved".
    """

    id: str
    workflow_id: str
    option_id: str
    outcome: str  # "approved" | "auto_approved"
    decided_by: str | None
    last_event_id: str | None = None


@dataclass
class RecoveryCommand:
    """The typed reaccommodate_travellers command one RecoveryDecision authorised.

    A real, queryable world record of the same command
    TravelWorld.apply_command already applies idempotently by
    `command_id`, so "the command that reaccommodated this booking" is a
    first-class actor tests and evidence trails can look up directly,
    rather than only the transient SimulationCommand argument. Carries the
    old (disrupted) and new (replacement) flight's own real `supplier_id`
    straight from the RecoveryOption that authorised it, so this audit
    record never loses which real supplier is losing and gaining this
    booking even though only flight ids are named elsewhere.
    """

    id: str
    workflow_id: str
    decision_id: str
    option_id: str
    booking_id: str
    party_id: str
    old_flight_id: str
    new_flight_id: str
    old_supplier_id: str
    new_supplier_id: str
    incremental_cost_gbp: float
    last_event_id: str | None = None


@dataclass
class RecoveryEvaluation:
    """The PASS outcome recorded once a RecoveryCommand's mutation lands.

    Only ever created after every reaccommodation precondition passed and
    the atomic capacity/booking/party mutation actually applied -- so
    "status" is always "pass" here. A command that fails any precondition
    never reaches this record at all: it returns a "command.rejected"
    event instead with zero mutation and zero RecoveryEvaluation created.
    """

    id: str
    workflow_id: str
    command_id: str
    booking_id: str
    party_id: str
    status: str
    last_event_id: str | None = None
