"""Detector, evaluator and reference-case functions for the Travel portfolio.

Every `detect_*` function below is a real, deterministic sensor: it scans
live `TravelWorld` state for a genuine trigger condition and, for each match,
journals a real `"sensor.<condition>_tripped"` event (never a synthetic or
random one) via `world.runtime.emit`. Every `evaluate_*` function is a real,
standalone diagnostic outcome check against live world state -- distinct
from (and not wired into) the generic `api.server.world.evaluations`
pipeline that `TravelWorld.run_reference_process` drives; these are for
direct diagnostic use and for tooling that wants a plain pass/fail read of
one process's real-world condition without opening an objective.

`REFERENCE_CASES` maps each of the eight workflow types to one real,
executable scenario: a `setup(world)` that arranges genuine world state (by
running the deterministic simulation forward and, where relevant, reporting
a real disruption), a `detect(world)` that calls that process's own
detector and picks out its one real triggering sensor event, and a
`build_command(world, objective)` that returns a real, authority-valid
`SimulationCommand` naming real seeded (or disruption-derived) Travel actor
ids. `TravelWorld.run_reference_process` drives all three through the
generic sensor -> objective -> command -> evaluation pipeline as a pure
Python call -- no world-process HTTP run route is exercised anywhere in
this module.

This module is generated by verticals.travel.generator.process_templates.
Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from api.server.world.model import SimulationCommand, SimulationEvent


def _detect_disruption_kind(world: Any, *, kind: str, event_type: str) -> list[SimulationEvent]:
    """Journal one real sensor event per reported-but-unresolved `kind` disruption.

    Shared by five of the six disruption-driven detectors below -- every one
    except `detect_flight_cancellation_impact`, which needs its own
    eligibility-gated, rising-edge logic (see below): a disruption only
    ever trips its sensor while genuinely `"reported"`, so a disruption an
    earlier command already resolved never re-trips it.
    """
    events: list[SimulationEvent] = []
    for disruption in sorted(world.disruptions.values(), key=lambda d: d.id):
        if disruption.kind != kind or disruption.status != "reported":
            continue
        events.append(
            world.runtime.emit(
                event_type,
                target_id=disruption.resource_id,
                payload={"disruption_id": disruption.id, "measurements": {"kind": kind}},
            )
        )
    return events


def detect_quote_ready(world: Any) -> list[SimulationEvent]:
    """Real sensor: every currently-offered quote is ready to be confirmed."""
    events: list[SimulationEvent] = []
    for quote in sorted(world.quotes.values(), key=lambda quote: quote.id):
        if quote.status != "offered":
            continue
        events.append(
            world.runtime.emit(
                "sensor.quote_ready_tripped",
                target_id=quote.id,
                payload={"quote_id": quote.id, "measurements": {"price": quote.price}},
            )
        )
    return events


def detect_capacity_pressure(world: Any, threshold: float = 0.02) -> list[SimulationEvent]:
    """Real sensor: an allotment's reserved/contracted ratio at or above `threshold`."""
    events: list[SimulationEvent] = []
    for allotment in sorted(world.allotments.values(), key=lambda allotment: allotment.id):
        if allotment.allotment <= 0:
            continue
        ratio = allotment.reserved / allotment.allotment
        if ratio < threshold:
            continue
        events.append(
            world.runtime.emit(
                "sensor.capacity_pressure_tripped",
                target_id=allotment.id,
                payload={"allotment_id": allotment.id, "measurements": {"ratio": ratio}},
            )
        )
    return events


_SENSOR_FLIGHT_CANCELLATION_IMPACT = "sensor:flight_cancellation_impact"
_ELIGIBLE_BOOKING_STATUSES = frozenset({"confirmed", "deposit_paid", "paid"})


def detect_flight_cancellation_impact(world: Any) -> list[SimulationEvent]:
    """Real, state-derived sensor for a reported flight-cancellation disruption
    whose flight still has at least one affected paid/confirmed booking and
    traveller party.

    Bespoke rather than delegated to `_detect_disruption_kind` (unlike the
    other six disruption-driven detectors): a cancellation against a flight
    with no eligible demand never trips this sensor at all -- the condition
    is read from real world state, never faked. Once a disruption has
    tripped this sensor, this function never re-emits `"sensor.tripped"`
    for it again: calling it again (or advancing the simulation further)
    while the same condition remains true is always a safe, idempotent
    no-op, since the rising edge is re-derived from the journal itself on
    every call rather than from any separate latch.
    """
    already_tripped = {
        event.payload.get("disruption_id")
        for event in world.runtime.journal
        if event.type == "sensor.tripped" and event.payload.get("sensor_id") == _SENSOR_FLIGHT_CANCELLATION_IMPACT
    }
    events_by_id = {event.event_id: event for event in world.runtime.journal}

    events: list[SimulationEvent] = []
    for disruption in sorted(world.disruptions.values(), key=lambda d: d.id):
        if disruption.kind != "flight_cancellation" or disruption.status != "reported":
            continue
        if disruption.id in already_tripped:
            continue

        flight_id = disruption.resource_id
        affected_bookings = sorted(
            (
                booking
                for booking in world.bookings.values()
                if booking.flight_id == flight_id and booking.status in _ELIGIBLE_BOOKING_STATUSES
            ),
            key=lambda booking: booking.id,
        )
        if not affected_bookings:
            continue

        party_ids = sorted({booking.party_id for booking in affected_bookings})
        parties = [world.parties[party_id] for party_id in party_ids]
        member_customer_ids = sorted(
            {customer_id for party in parties for customer_id in party.member_customer_ids}
        )
        hotel_ids = sorted({booking.hotel_id for booking in affected_bookings})
        transfer_ids = sorted({booking.transfer_id for booking in affected_bookings})
        flight = world.flights[flight_id]
        supplier_ids = sorted(
            {flight.supplier_id}
            | {world.hotels[hotel_id].supplier_id for hotel_id in hotel_ids}
            | {world.transfers[transfer_id].supplier_id for transfer_id in transfer_ids}
        )
        traveller_count = sum(party.size for party in parties)
        actor_ids = sorted(
            {flight_id, disruption.id, *(b.id for b in affected_bookings), *party_ids}
            | set(member_customer_ids)
            | set(hotel_ids)
            | set(transfer_ids)
            | set(supplier_ids)
        )

        cause_event = events_by_id[disruption.last_event_id]
        events.append(
            world.runtime.emit(
                "sensor.tripped",
                actor_id=disruption.id,
                target_id=flight_id,
                cause_event_id=cause_event.event_id,
                trace_id=cause_event.trace_id,
                payload={
                    "sensor_id": _SENSOR_FLIGHT_CANCELLATION_IMPACT,
                    "disruption_id": disruption.id,
                    "flight_id": flight_id,
                    "booking_ids": [booking.id for booking in affected_bookings],
                    "party_ids": party_ids,
                    "member_customer_ids": member_customer_ids,
                    "hotel_ids": hotel_ids,
                    "transfer_ids": transfer_ids,
                    "supplier_ids": supplier_ids,
                    "actor_ids": actor_ids,
                    "measurements": {
                        "affected_booking_count": len(affected_bookings),
                        "affected_party_count": len(party_ids),
                        "affected_traveller_count": traveller_count,
                        "seats_impacted": traveller_count,
                        "material_change": True,
                    },
                },
            )
        )
    return events


def detect_hotel_allotment_shortfall(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved hotel allotment shortfall disruption."""
    return _detect_disruption_kind(
        world, kind="hotel_allotment_shortfall", event_type="sensor.hotel_allotment_shortfall_tripped",
    )


def detect_customer_cancellation_accepted(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved accepted customer cancellation."""
    return _detect_disruption_kind(
        world,
        kind="customer_cancellation_accepted",
        event_type="sensor.customer_cancellation_accepted_tripped",
    )


def detect_balance_payment_exception(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved balance payment exception disruption."""
    return _detect_disruption_kind(
        world, kind="balance_payment_exception", event_type="sensor.balance_payment_exception_tripped",
    )


def detect_transfer_arrival_risk(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved transfer arrival risk disruption."""
    return _detect_disruption_kind(
        world, kind="transfer_arrival_risk", event_type="sensor.transfer_arrival_risk_tripped",
    )


def detect_material_itinerary_change(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved material itinerary change disruption."""
    return _detect_disruption_kind(
        world, kind="material_itinerary_change", event_type="sensor.material_itinerary_change_tripped",
    )


DETECTORS: dict[str, Callable[..., list[SimulationEvent]]] = {
    "holiday-sales-booking": detect_quote_ready,
    "capacity-yield-management": detect_capacity_pressure,
    "flight-disruption-recovery": detect_flight_cancellation_impact,
    "hotel-supplier-recovery": detect_hotel_allotment_shortfall,
    "cancellation-refund": detect_customer_cancellation_accepted,
    "payment-exception": detect_balance_payment_exception,
    "destination-operations": detect_transfer_arrival_risk,
    "proactive-customer-care": detect_material_itinerary_change,
}


def evaluate_booking_confirmed_and_paid(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` names a real booking whose status is `"paid"`."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking"}
    if booking.status != "paid":
        return {"status": "fail", "booking_id": booking_id, "reason": f"booking is {booking.status!r}"}
    return {"status": "pass", "booking_id": booking_id, "total_price": booking.total_price}


def evaluate_capacity_within_bounds(world: Any, *, allotment_id: str) -> dict[str, Any]:
    """Pass iff `allotment_id`'s conservation invariant holds and it is not over-pressured."""
    allotment = world.allotments.get(allotment_id)
    if allotment is None:
        return {"status": "fail", "allotment_id": allotment_id, "reason": "unknown allotment"}
    conserved = 0 <= allotment.occupied <= allotment.reserved <= allotment.allotment <= allotment.total
    if not conserved:
        return {"status": "fail", "allotment_id": allotment_id, "reason": "conservation invariant broken"}
    ratio = (allotment.reserved / allotment.allotment) if allotment.allotment else 0.0
    return {"status": "pass", "allotment_id": allotment_id, "ratio": ratio}


def evaluate_travellers_reaccommodated(world: Any, *, booking_id: str, disruption_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` exists and its linked disruption is `"resolved"`."""
    booking = world.bookings.get(booking_id)
    disruption = world.disruptions.get(disruption_id)
    if booking is None or disruption is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking or disruption"}
    if disruption.status != "resolved":
        return {"status": "fail", "booking_id": booking_id, "reason": "disruption not yet resolved"}
    return {"status": "pass", "booking_id": booking_id, "flight_id": booking.flight_id}


def evaluate_accommodation_restored(world: Any, *, disruption_id: str) -> dict[str, Any]:
    """Pass iff the named hotel-shortfall disruption is `"resolved"`."""
    disruption = world.disruptions.get(disruption_id)
    if disruption is None:
        return {"status": "fail", "disruption_id": disruption_id, "reason": "unknown disruption"}
    if disruption.status != "resolved":
        return {"status": "fail", "disruption_id": disruption_id, "reason": "not yet resolved"}
    return {"status": "pass", "disruption_id": disruption_id}


def evaluate_refund_settled(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` is cancelled and carries exactly one issued refund."""
    booking = world.bookings.get(booking_id)
    if booking is None or booking.status != "cancelled":
        return {"status": "fail", "booking_id": booking_id, "reason": "booking not cancelled"}
    refunds = [refund for refund in world.refunds.values() if refund.booking_id == booking_id]
    if not refunds or refunds[0].status != "issued":
        return {"status": "fail", "booking_id": booking_id, "reason": "no issued refund"}
    return {"status": "pass", "booking_id": booking_id, "refund_amount": refunds[0].amount}


def evaluate_payment_or_inventory_resolved(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` ended either `"paid"` (retry) or `"cancelled"` (release)."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking"}
    if booking.status not in ("paid", "cancelled"):
        return {"status": "fail", "booking_id": booking_id, "reason": f"booking is {booking.status!r}"}
    return {"status": "pass", "booking_id": booking_id, "resolution": booking.status}


def evaluate_transfer_sla_restored(world: Any, *, transfer_id: str) -> dict[str, Any]:
    """Pass iff `transfer_id` was superseded by a real dispatched replacement."""
    transfer = world.transfers.get(transfer_id)
    replacement = world.transfers.get(f"TRF-REPL-{transfer_id}")
    if transfer is None or replacement is None:
        return {"status": "fail", "transfer_id": transfer_id, "reason": "no dispatched replacement"}
    if transfer.status != "superseded":
        return {"status": "fail", "transfer_id": transfer_id, "reason": "original transfer not superseded"}
    return {"status": "pass", "transfer_id": transfer_id, "replacement_id": replacement.id}


def evaluate_customer_notified_and_supported(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` carries at least one issued customer care action."""
    actions = [action for action in world.care_actions.values() if action.booking_id == booking_id]
    if not actions or any(action.status != "issued" for action in actions):
        return {"status": "fail", "booking_id": booking_id, "reason": "no issued care action"}
    return {"status": "pass", "booking_id": booking_id, "care_action_ids": [a.id for a in actions]}


EVALUATORS: dict[str, Callable[..., dict[str, Any]]] = {
    "holiday-sales-booking": evaluate_booking_confirmed_and_paid,
    "capacity-yield-management": evaluate_capacity_within_bounds,
    "flight-disruption-recovery": evaluate_travellers_reaccommodated,
    "hotel-supplier-recovery": evaluate_accommodation_restored,
    "cancellation-refund": evaluate_refund_settled,
    "payment-exception": evaluate_payment_or_inventory_resolved,
    "destination-operations": evaluate_transfer_sla_restored,
    "proactive-customer-care": evaluate_customer_notified_and_supported,
}


def _run_setup(world: Any, *, run_until_minutes: float, disruption: tuple[str, str] | None) -> None:
    world.run(run_until_minutes)
    if disruption is not None:
        kind, resource_id = disruption
        world.report_disruption(kind=kind, resource_id=resource_id)


def _run_detect(world: Any, *, workflow_type: str, target_id: str) -> SimulationEvent:
    events = DETECTORS[workflow_type](world)
    return next(event for event in events if event.target_id == target_id)


@dataclass(frozen=True)
class ReferenceCase:
    """One real, executable reference scenario for one portfolio process."""

    workflow_type: str
    role: str
    run_until_minutes: float
    disruption: tuple[str, str] | None
    detect_target_id: str
    command_id: str
    command_type: str
    command_payload: dict[str, Any]

    def setup(self, world: Any) -> None:
        _run_setup(world, run_until_minutes=self.run_until_minutes, disruption=self.disruption)

    def detect(self, world: Any) -> SimulationEvent:
        return _run_detect(world, workflow_type=self.workflow_type, target_id=self.detect_target_id)

    def build_command(self, world: Any, objective: Any) -> SimulationCommand:
        return SimulationCommand(
            command_id=self.command_id,
            trace_id=objective.trace_id,
            issued_by=objective.claimed_by,
            type=self.command_type,
            payload=dict(self.command_payload),
        )

REFERENCE_CASES: dict[str, ReferenceCase] = {
    'holiday-sales-booking': ReferenceCase(
        workflow_type='holiday-sales-booking',
        role='travel_adviser',
        run_until_minutes=50.0,
        disruption=None,
        detect_target_id='QTE-6',
        command_id='ref-hsb-01',
        command_type='confirm_package_booking',
        command_payload={'quote_id': 'QTE-6', 'flight_id': 'FLT-ZV102', 'hotel_id': 'HTL-BLU-TFS', 'allotment_id': 'ALT-BLU-TFS', 'transfer_id': 'TRF-3', 'rooms': 1, 'authorized_by': 'travel_adviser'},
    ),
    'capacity-yield-management': ReferenceCase(
        workflow_type='capacity-yield-management',
        role='revenue_manager',
        run_until_minutes=80.0,
        disruption=None,
        detect_target_id='ALT-SUN-PMI',
        command_id='ref-cym-02',
        command_type='adjust_package_allotment',
        command_payload={'from_allotment_id': 'ALT-SUN-AYT', 'to_allotment_id': 'ALT-SUN-PMI', 'rooms': 5, 'estimated_value_gbp': 500.0, 'authorized_by': 'revenue_manager'},
    ),
    'flight-disruption-recovery': ReferenceCase(
        workflow_type='flight-disruption-recovery',
        role='operations_controller',
        run_until_minutes=80.0,
        disruption=('flight_cancellation', 'FLT-ZV101'),
        detect_target_id='FLT-ZV101',
        command_id='ref-fdr-03',
        command_type='reaccommodate_travellers',
        command_payload={'booking_id': 'BKG-1', 'disruption_id': 'DIS-flight_cancellation-FLT-ZV101', 'to_flight_id': 'FLT-ZV204', 'to_transfer_id': 'TRF-2', 'estimated_cost_gbp': 500.0, 'authorized_by': 'operations_controller'},
    ),
    'hotel-supplier-recovery': ReferenceCase(
        workflow_type='hotel-supplier-recovery',
        role='accommodation_manager',
        run_until_minutes=80.0,
        disruption=('hotel_allotment_shortfall', 'ALT-SUN-PMI'),
        detect_target_id='ALT-SUN-PMI',
        command_id='ref-hsr-04',
        command_type='move_hotel_allotment',
        command_payload={'disruption_id': 'DIS-hotel_allotment_shortfall-ALT-SUN-PMI', 'from_allotment_id': 'ALT-SUN-AYT', 'to_allotment_id': 'ALT-SUN-PMI', 'rooms': 15, 'estimated_value_gbp': 2000.0, 'authorized_by': 'accommodation_manager'},
    ),
    'cancellation-refund': ReferenceCase(
        workflow_type='cancellation-refund',
        role='finance_operations_lead',
        run_until_minutes=80.0,
        disruption=('customer_cancellation_accepted', 'BKG-2'),
        detect_target_id='BKG-2',
        command_id='ref-cxr-05',
        command_type='cancel_and_refund_booking',
        command_payload={'disruption_id': 'DIS-customer_cancellation_accepted-BKG-2', 'booking_id': 'BKG-2', 'authorized_by': 'finance_operations_lead'},
    ),
    'payment-exception': ReferenceCase(
        workflow_type='payment-exception',
        role='payments_specialist',
        run_until_minutes=60.0,
        disruption=('balance_payment_exception', 'BKG-3'),
        detect_target_id='BKG-3',
        command_id='ref-pex-06',
        command_type='resolve_payment_exception',
        command_payload={'disruption_id': 'DIS-balance_payment_exception-BKG-3', 'booking_id': 'BKG-3', 'action': 'retry', 'authorized_by': 'payments_specialist'},
    ),
    'destination-operations': ReferenceCase(
        workflow_type='destination-operations',
        role='destination_operations_manager',
        run_until_minutes=45.0,
        disruption=('transfer_arrival_risk', 'TRF-1'),
        detect_target_id='TRF-1',
        command_id='ref-dop-07',
        command_type='dispatch_replacement_transfer',
        command_payload={'disruption_id': 'DIS-transfer_arrival_risk-TRF-1', 'transfer_id': 'TRF-1', 'estimated_cost_gbp': 150.0, 'authorized_by': 'destination_operations_manager'},
    ),
    'proactive-customer-care': ReferenceCase(
        workflow_type='proactive-customer-care',
        role='customer_care_lead',
        run_until_minutes=80.0,
        disruption=('material_itinerary_change', 'BKG-1'),
        detect_target_id='BKG-1',
        command_id='ref-pcc-08',
        command_type='issue_customer_care_action',
        command_payload={'disruption_id': 'DIS-material_itinerary_change-BKG-1', 'booking_id': 'BKG-1', 'kind': 'goodwill_gesture', 'amount_gbp': 50.0, 'message': 'We are sorry for the disruption to your holiday.', 'authorized_by': 'customer_care_lead'},
    ),
}
