"""World-pack registration for the Travel eight-process portfolio.

Wires every process's real `ObjectiveRoute` (sensor -> objective ->
allowed command -> success/failure event types -> evaluation timeout) and
`ResponderRegistration` (objective type -> orchestrator name -> workflow
type -> prefix -> owning function -> timeout) into one
`api.shared.world_contracts.WorldPackRegistration` scale profile, keyed by
objective_type exactly as `api.server.world.objectives.ObjectiveManager`
and `api.server.world.commands.CommandGateway` expect.

This module is generated by verticals.travel.generator.process_templates.
Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.world_contracts import (
    ObjectiveRoute,
    ResponderRegistration,
    WorldPackRegistration,
    WorldScaleProfile,
)
from verticals.travel.worlds.diagnostics import build_diagnostic_input
from verticals.travel.worlds.scenario import TravelWorld

_ROUTES: tuple[ObjectiveRoute, ...] = (
    ObjectiveRoute(
        sensor_id='sensor:quote_ready',
        objective_type='convert_holiday_demand',
        allowed_command_types=frozenset({'confirm_package_booking'}),
        success_event_types=frozenset(('booking.paid',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=60.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:capacity_pressure',
        objective_type='protect_package_capacity',
        allowed_command_types=frozenset({'adjust_package_allotment'}),
        success_event_types=frozenset(('hotel.allotment_adjusted',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=60.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:flight_cancellation_impact',
        objective_type='recover_cancelled_flight',
        allowed_command_types=frozenset({'reaccommodate_travellers'}),
        success_event_types=frozenset(('booking.reaccommodated',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=90.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:hotel_allotment_shortfall',
        objective_type='restore_hotel_accommodation',
        allowed_command_types=frozenset({'move_hotel_allotment'}),
        success_event_types=frozenset(('hotel.allotment_moved',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=90.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:customer_cancellation_accepted',
        objective_type='settle_cancelled_booking',
        allowed_command_types=frozenset({'cancel_and_refund_booking'}),
        success_event_types=frozenset(('refund.issued',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=60.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:balance_payment_exception',
        objective_type='preserve_payment_booking',
        allowed_command_types=frozenset({'resolve_payment_exception'}),
        success_event_types=frozenset(('booking.cancelled', 'payment.succeeded')),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=60.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:transfer_arrival_risk',
        objective_type='restore_destination_journey',
        allowed_command_types=frozenset({'dispatch_replacement_transfer'}),
        success_event_types=frozenset(('transfer.replacement_dispatched',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=45.0,
    ),
    ObjectiveRoute(
        sensor_id='sensor:material_itinerary_change',
        objective_type='protect_disrupted_customer',
        allowed_command_types=frozenset({'issue_customer_care_action'}),
        success_event_types=frozenset(('care.action_issued',)),
        failure_event_types=frozenset(('command.rejected',)),
        evaluation_timeout_minutes=30.0,
    ),
)

_RESPONDERS: dict[str, ResponderRegistration] = {
    'convert_holiday_demand': ResponderRegistration(
        objective_type='convert_holiday_demand',
        orchestrator='HolidaySalesBookingOrchestrator',
        workflow_type='holiday-sales-booking',
        prefix='hsb',
        owner_function='commercial',
        timeout_seconds=120.0,
        lifecycle_start_via_bridge=False,
    ),
    'protect_package_capacity': ResponderRegistration(
        objective_type='protect_package_capacity',
        orchestrator='CapacityYieldManagementOrchestrator',
        workflow_type='capacity-yield-management',
        prefix='cym',
        owner_function='commercial',
        timeout_seconds=120.0,
        lifecycle_start_via_bridge=False,
    ),
    'recover_cancelled_flight': ResponderRegistration(
        objective_type='recover_cancelled_flight',
        orchestrator='TravelFlightDisruptionRecoveryOrchestrator',
        workflow_type='flight-disruption-recovery',
        prefix='fdr',
        owner_function='operations-control',
        timeout_seconds=180.0,
        lifecycle_start_via_bridge=True,
    ),
    'restore_hotel_accommodation': ResponderRegistration(
        objective_type='restore_hotel_accommodation',
        orchestrator='HotelSupplierRecoveryOrchestrator',
        workflow_type='hotel-supplier-recovery',
        prefix='hsr',
        owner_function='accommodation-supply',
        timeout_seconds=180.0,
        lifecycle_start_via_bridge=False,
    ),
    'settle_cancelled_booking': ResponderRegistration(
        objective_type='settle_cancelled_booking',
        orchestrator='CancellationRefundOrchestrator',
        workflow_type='cancellation-refund',
        prefix='cxr',
        owner_function='customer-finance',
        timeout_seconds=120.0,
        lifecycle_start_via_bridge=False,
    ),
    'preserve_payment_booking': ResponderRegistration(
        objective_type='preserve_payment_booking',
        orchestrator='PaymentExceptionOrchestrator',
        workflow_type='payment-exception',
        prefix='pex',
        owner_function='customer-finance',
        timeout_seconds=120.0,
        lifecycle_start_via_bridge=False,
    ),
    'restore_destination_journey': ResponderRegistration(
        objective_type='restore_destination_journey',
        orchestrator='DestinationOperationsOrchestrator',
        workflow_type='destination-operations',
        prefix='dop',
        owner_function='destination-operations',
        timeout_seconds=90.0,
        lifecycle_start_via_bridge=False,
    ),
    'protect_disrupted_customer': ResponderRegistration(
        objective_type='protect_disrupted_customer',
        orchestrator='ProactiveCustomerCareOrchestrator',
        workflow_type='proactive-customer-care',
        prefix='pcc',
        owner_function='customer-care',
        timeout_seconds=60.0,
        lifecycle_start_via_bridge=False,
    ),
}

def _build_demo_scenario(runtime: object) -> TravelWorld:
    """Build the demo-scale TravelWorld, sharing the pack runtime."""
    return TravelWorld(seed=42, runtime=runtime)


_SCALES: dict[str, WorldScaleProfile] = {
    "demo": WorldScaleProfile(
        name="demo",
        build_scenario=_build_demo_scenario,
        default_minutes_per_second=2.0,
    ),
}

TRAVEL_WORLD = WorldPackRegistration(
    name="travel",
    scales=_SCALES,
    default_scale="demo",
    objective_routes=_ROUTES,
    responders=_RESPONDERS,
    build_diagnostic_input=build_diagnostic_input,
)

TRAVEL_WORLDS: dict[str, WorldPackRegistration] = {"travel": TRAVEL_WORLD}

_ROUTE_BY_WORKFLOW_TYPE: dict[str, ObjectiveRoute] = {
    'holiday-sales-booking': _ROUTES[0],
    'capacity-yield-management': _ROUTES[1],
    'flight-disruption-recovery': _ROUTES[2],
    'hotel-supplier-recovery': _ROUTES[3],
    'cancellation-refund': _ROUTES[4],
    'payment-exception': _ROUTES[5],
    'destination-operations': _ROUTES[6],
    'proactive-customer-care': _ROUTES[7],
}


def route_for_workflow_type(workflow_type: str) -> ObjectiveRoute:
    """The real ObjectiveRoute registered for `workflow_type`."""
    return _ROUTE_BY_WORKFLOW_TYPE[workflow_type]


def responder_for_workflow_type(workflow_type: str) -> ResponderRegistration:
    """The real ResponderRegistration registered for `workflow_type`."""
    for responder in _RESPONDERS.values():
        if responder.workflow_type == workflow_type:
            return responder
    raise KeyError(f"no responder registered for workflow type {workflow_type!r}")
