"""Deterministic, synthetic Travel world simulation (Task 3 + Task 4 + Task 5).

TravelWorld builds a seeded, integrated-tour-operator-style world on top
of api.server.world.runtime.SimulationRuntime: customers browse a
destination, then request quotes, advisers make offers, quotes convert
into confirmed package bookings, deposits and balances are paid, and (for
the one itinerary whose flight departs before minute 180) the party real
position advances booked -> checked-in at its origin airport -> airborne
-> disembarked at the destination -> transferred to its resort, with
hotel occupancy changing to match. Every mutation is paired with a
causal journal event that names the record it changed (as actor or
target) and carries the exact new field values, and every mutated
record last_event_id points at that exact event.

Task 4 adds the eight-process portfolio's real, journal-backed command
surface on top of that ordinary lifecycle: `report_disruption` records a
real disruption event against a resource; `apply_command` is a typed,
idempotent dispatcher (`verticals.travel.actions.commands.COMMAND_HANDLERS`)
that replays a cached result for a previously-seen `command_id` instead of
re-mutating; `run_reference_process` drives one real
sensor -> objective -> command -> evaluation pass for a named workflow type
through the generic `api.server.world` gateway, entirely as a pure Python
call -- no world-process HTTP run route is exercised anywhere in this
module.

Task 5 adds one autonomous, deterministic operational disruption on top of
that ordinary lifecycle and command surface: at simulation minute 180, once
FLT-ZV204's own ordinary shopping/booking activity has produced a real paid
package booking on it, a real supplier/operations cancellation changes its
status to `"cancelled"` and reports a real disruption, both causally
chained by `cause_event_id`/`trace_id`. A separate sensor-evaluation step
then re-derives `sensor:flight_cancellation_impact` from that mutated state
through the real generated detector -- never an unconditional emission --
so the sensor only trips while there is genuine, eligible demand at risk,
and never trips twice for the same disruption. This mutation never
releases or rebooks capacity by itself; that recovery is a distinct, later
task's command, and no objective/workflow/responder event is exercised
anywhere in this module.

Task 6 adds `build_observation`, which turns one
`sensor:flight_cancellation_impact` event into the single flat, JSON-only
dict the real Azure Durable Functions
`verticals.travel.durable.functions.TravelFlightDisruptionRecoveryOrchestrator`
and the pure `verticals.travel.recovery.planner.plan_recovery_options`
both read -- naming the exact affected booking/party/flight and every
candidate replacement flight/transfer, so the planner itself never reaches
back into this module's own mutable world state. The option-based path of
`verticals.travel.actions.commands.reaccommodate_travellers` then applies
the approved (or auto-approved) `RecoveryOption` atomically, and records
its own `RecoveryDecision`/`RecoveryCommand`/`RecoveryEvaluation` as real,
queryable world actors alongside the ordinary booking/flight/transfer
mutation.

This module is generated by verticals.travel.generator.world_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import dataclasses
from typing import Any, Callable

from api.server.world.model import SimulationCommand, SimulationEvent
from api.server.world.runtime import SimulationRuntime
from verticals.travel.actions.commands import COMMAND_HANDLERS, reject
from verticals.travel.worlds import processes, reference_data
from verticals.travel.worlds.model import (
    Airport,
    Booking,
    CareAction,
    Customer,
    Destination,
    Disruption,
    Flight,
    Hotel,
    Payment,
    Quote,
    RecoveryCommand,
    RecoveryDecision,
    RecoveryEvaluation,
    Refund,
    RoomAllotment,
    StaffMember,
    Supplier,
    Transfer,
    TravellingParty,
)


def _jsonify(value: Any) -> Any:
    if isinstance(value, (tuple, list)):
        return [_jsonify(item) for item in value]
    if isinstance(value, dict):
        return {key: _jsonify(item) for key, item in value.items()}
    return value


class TravelWorld:
    """A deterministic, synthetic integrated-tour-operator world."""

    def __init__(self, seed: int = 42, *, runtime: SimulationRuntime | None = None) -> None:
        self.seed = seed
        # Task 3 deliberately builds and seeds eagerly in one phase so the
        # scenario is immediately usable standalone in tests. The generic
        # `ActorWorldService` instead builds a runtime first and calls a
        # separate `.install()` afterwards (see
        # `api.server.world.packs.support.SupportScenario` for the shared
        # precedent this mirrors) -- passing `runtime=` here lets
        # `worlds.registration.build_travel_demo` share that externally
        # built runtime instead of this scenario constructing its own,
        # while every existing `TravelWorld(seed=...)` call site keeps
        # working unchanged.
        self.runtime = runtime if runtime is not None else SimulationRuntime(seed=seed)

        self.airports: dict[str, Airport] = {}
        self.destinations: dict[str, Destination] = {}
        self.suppliers: dict[str, Supplier] = {}
        self.staff: dict[str, StaffMember] = {}
        self.customers: dict[str, Customer] = {}
        self.parties: dict[str, TravellingParty] = {}
        self.flights: dict[str, Flight] = {}
        self.hotels: dict[str, Hotel] = {}
        self.allotments: dict[str, RoomAllotment] = {}
        self.transfers: dict[str, Transfer] = {}
        self.quotes: dict[str, Quote] = {}
        self.bookings: dict[str, Booking] = {}
        self.payments: dict[str, Payment] = {}
        self.refunds: dict[str, Refund] = {}
        self.disruptions: dict[str, Disruption] = {}
        self.care_actions: dict[str, CareAction] = {}

        # Task 6: flight-disruption-recovery's own real, queryable actors.
        self.recovery_decisions: dict[str, RecoveryDecision] = {}
        self.recovery_commands: dict[str, RecoveryCommand] = {}
        self.recovery_evaluations: dict[str, RecoveryEvaluation] = {}

        # Task 4: idempotency cache keyed by command_id -- replaying a
        # previously-seen command_id (success or rejection) always returns
        # the cached event and never re-emits or re-mutates.
        self._processed_commands: dict[str, SimulationEvent] = {}

        self._seed_world()
        self._schedule_processes()

    def install(self) -> None:
        """No-op: satisfies `ActorWorldService`'s two-phase build/install
        convention. Task 3 chose eager single-phase seeding inside
        `__init__` (for standalone testability), so there is no deferred
        seeding step left to run here.
        """
        return None

    # -- generic causal-mutation helpers ----------------------------------

    def _created(
        self,
        event_type: str,
        record: Any,
        *,
        target_id: str | None = None,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
        extra_payload: dict[str, Any] | None = None,
    ):
        payload = dict(extra_payload or {})
        payload.setdefault("id", record.id)
        event = self.runtime.emit(
            event_type,
            actor_id=record.id,
            target_id=target_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            payload=payload,
        )
        record.last_event_id = event.event_id
        return event

    def _apply(
        self,
        event_type: str,
        record: Any,
        changes: dict[str, Any],
        *,
        target_id: str | None = None,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
        extra_payload: dict[str, Any] | None = None,
    ):
        payload = {**(extra_payload or {}), **changes}
        event = self.runtime.emit(
            event_type,
            actor_id=record.id,
            target_id=target_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            payload=payload,
        )
        for field, value in changes.items():
            setattr(record, field, value)
        record.last_event_id = event.event_id
        return event

    # -- genesis -------------------------------------------------------------

    def _seed_world(self) -> None:
        for airport in reference_data.build_airports():
            self.airports[airport.id] = airport
            self._created("world.airport_seeded", airport)
        for destination in reference_data.build_destinations():
            self.destinations[destination.id] = destination
            self._created("world.destination_seeded", destination)
        for supplier in reference_data.build_suppliers():
            self.suppliers[supplier.id] = supplier
            self._created("world.supplier_seeded", supplier)
        for member in reference_data.build_staff():
            self.staff[member.id] = member
            self._created("world.staff_seeded", member)
        for customer in reference_data.build_customers():
            self.customers[customer.id] = customer
            self._created("world.customer_seeded", customer)
        for party in reference_data.build_parties():
            self.parties[party.id] = party
            self._created("world.party_seeded", party)
        for flight in reference_data.build_flights():
            self.flights[flight.id] = flight
            self._created("world.flight_seeded", flight)
        for hotel in reference_data.build_hotels():
            self.hotels[hotel.id] = hotel
            self._created("world.hotel_seeded", hotel)
        for allotment in reference_data.build_allotments():
            self.allotments[allotment.id] = allotment
            self._created("world.allotment_seeded", allotment)
        for transfer in reference_data.build_transfers():
            self.transfers[transfer.id] = transfer
            self._created("world.transfer_seeded", transfer)

    def _schedule_processes(self) -> None:
        for plan in reference_data.build_party_plans():
            self.runtime.process(self._party_pipeline(plan))
        for flight_id in sorted(self.flights):
            self.runtime.process(self._flight_lifecycle(flight_id))
        self.runtime.process(self._operations_flight_cancellation())

    # -- ordinary autonomous lifecycle ---------------------------------------

    def _party_pipeline(self, plan: reference_data.PartyPlan):
        party = self.parties[plan.party_id]
        lead_customer = self.customers[plan.customer_id]
        adviser = self.staff[plan.adviser_id]

        yield self.runtime.env.timeout(plan.browse_at)
        browsed = self._apply(
            "customer.browsed",
            lead_customer,
            {"status": "browsing"},
            target_id=party.id,
            extra_payload={"party_id": party.id, "destination_id": plan.browse_destination_id},
        )

        yield self.runtime.env.timeout(plan.request_at - plan.browse_at)
        quote = Quote(
            id=plan.quote_id,
            party_id=party.id,
            customer_id=lead_customer.id,
            adviser_id=adviser.id,
            price=None,
            status="requested",
        )
        self.quotes[quote.id] = quote
        created = self._created(
            "quote.requested",
            quote,
            target_id=party.id,
            cause_event_id=browsed.event_id,
            extra_payload={"party_id": party.id, "customer_id": lead_customer.id},
        )
        self._apply(
            "party.quote_requested",
            party,
            {"state": "quote_requested"},
            cause_event_id=created.event_id,
        )
        self._apply(
            "customer.engaged",
            lead_customer,
            {"status": "engaged"},
            cause_event_id=created.event_id,
        )

        if plan.offer_at is None:
            return
        yield self.runtime.env.timeout(plan.offer_at - plan.request_at)
        self._apply(
            "quote.offered",
            quote,
            {"price": plan.price, "status": "offered"},
            target_id=adviser.id,
        )
        self._apply(
            "staff.handled_quote",
            adviser,
            {"last_action": f"offered:{quote.id}"},
            target_id=quote.id,
        )

        if plan.convert_at is None:
            return
        yield self.runtime.env.timeout(plan.convert_at - plan.offer_at)
        self._apply("quote.converted", quote, {"status": "converted"})

        booking = Booking(
            id=plan.booking_id,
            quote_id=quote.id,
            party_id=party.id,
            customer_id=lead_customer.id,
            flight_id=plan.flight_id,
            hotel_id=plan.hotel_id,
            allotment_id=plan.allotment_id,
            transfer_id=plan.transfer_id,
            rooms=plan.rooms,
            total_price=plan.price,
            status="confirmed",
        )
        self.bookings[booking.id] = booking
        booking_created = self._created(
            "booking.confirmed",
            booking,
            target_id=quote.id,
            extra_payload={"party_id": party.id, "flight_id": plan.flight_id},
        )
        self._apply(
            "party.booked", party, {"state": "booked"}, cause_event_id=booking_created.event_id,
        )

        flight = self.flights[plan.flight_id]
        self._apply(
            "flight.capacity_reserved",
            flight,
            {"reserved": flight.reserved + party.size},
            target_id=booking.id,
        )
        allotment = self.allotments[plan.allotment_id]
        self._apply(
            "hotel.rooms_reserved",
            allotment,
            {"reserved": allotment.reserved + booking.rooms},
            target_id=booking.id,
        )
        transfer = self.transfers[plan.transfer_id]
        self._apply(
            "transfer.capacity_reserved",
            transfer,
            {"reserved": transfer.reserved + party.size},
            target_id=booking.id,
        )

        if plan.deposit_at is None:
            return
        yield self.runtime.env.timeout(plan.deposit_at - plan.convert_at)
        deposit_amount = plan.price * 20 // 100
        deposit_payment = Payment(
            id=plan.deposit_payment_id,
            booking_id=booking.id,
            kind="deposit",
            amount=deposit_amount,
        )
        self.payments[deposit_payment.id] = deposit_payment
        self._created("payment.succeeded", deposit_payment, target_id=booking.id)
        self._apply("booking.deposit_paid", booking, {"status": "deposit_paid"})
        finance = self.staff["FIN-1"]
        self._apply(
            "staff.handled_payment",
            finance,
            {"last_action": f"deposit:{deposit_payment.id}"},
            target_id=deposit_payment.id,
        )

        if plan.balance_at is None:
            return
        yield self.runtime.env.timeout(plan.balance_at - plan.deposit_at)
        balance_amount = plan.price - deposit_amount
        balance_payment = Payment(
            id=plan.balance_payment_id,
            booking_id=booking.id,
            kind="balance",
            amount=balance_amount,
        )
        self.payments[balance_payment.id] = balance_payment
        self._created("payment.succeeded", balance_payment, target_id=booking.id)
        self._apply("booking.paid", booking, {"status": "paid"})
        self._apply("customer.booked", lead_customer, {"status": "booked"})
        self._apply(
            "staff.handled_payment",
            finance,
            {"last_action": f"balance:{balance_payment.id}"},
            target_id=balance_payment.id,
        )

    def _bookings_for_flight(self, flight_id: str) -> list[Booking]:
        return sorted(
            (booking for booking in self.bookings.values() if booking.flight_id == flight_id),
            key=lambda booking: booking.id,
        )

    def _flight_lifecycle(self, flight_id: str):
        flight = self.flights[flight_id]
        checkin_offset = flight.scheduled_departure - 10
        yield self.runtime.env.timeout(checkin_offset)

        bookings = self._bookings_for_flight(flight_id)
        ops = self.staff["OPS-1"]
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply(
                "party.checked_in",
                party,
                {"state": "checked_in", "location": flight.origin_airport_id},
            )
            self._apply(
                "staff.handled_checkin",
                ops,
                {"last_action": f"checked_in:{party.id}"},
                target_id=party.id,
            )

        yield self.runtime.env.timeout(flight.scheduled_departure - checkin_offset)
        self._apply("flight.departed", flight, {"status": "departed"})
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply("party.boarded", party, {"state": "airborne", "location": flight.id})

        yield self.runtime.env.timeout(flight.scheduled_arrival - flight.scheduled_departure)
        self._apply("flight.arrived", flight, {"status": "arrived"})
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply(
                "party.disembarked",
                party,
                {"state": "in_transfer", "location": flight.destination_id},
            )
            transfer = self.transfers[booking.transfer_id]
            self._apply("transfer.departed", transfer, {"status": "in_progress"})

        yield self.runtime.env.timeout(20)
        rep = self.staff["REP-1"]
        for booking in bookings:
            party = self.parties[booking.party_id]
            hotel = self.hotels[booking.hotel_id]
            allotment = self.allotments[booking.allotment_id]
            self._apply(
                "party.arrived_at_resort", party, {"state": "at_resort", "location": hotel.id},
            )
            self._apply(
                "hotel.rooms_occupied",
                allotment,
                {"occupied": allotment.occupied + booking.rooms},
                target_id=hotel.id,
            )
            transfer = self.transfers[booking.transfer_id]
            self._apply("transfer.completed", transfer, {"status": "completed"})
            self._apply(
                "staff.handled_arrival",
                rep,
                {"last_action": f"arrived:{party.id}"},
                target_id=party.id,
            )

    def run(self, until: float) -> None:
        self.runtime.run_until(until)

    # -- Task 4: process portfolio command/process surface --------------------

    def report_disruption(
        self,
        *,
        kind: str,
        resource_id: str,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
    ) -> Disruption:
        """Record a real disruption against `resource_id`.

        Deterministic id `DIS-{kind}-{resource_id}`: reporting the exact
        same (kind, resource_id) pair twice returns the already-reported
        record unchanged instead of double-journalling it. `cause_event_id`
        and `trace_id` are optional so an autonomous mutation (Task 5's
        minute-180 flight cancellation) can causally chain this report back
        to the event that triggered it; every existing call site that omits
        them keeps its original, untraced-cause behaviour unchanged.
        """
        disruption_id = f"DIS-{kind}-{resource_id}"
        existing = self.disruptions.get(disruption_id)
        if existing is not None:
            return existing

        disruption = Disruption(
            id=disruption_id,
            resource_id=resource_id,
            kind=kind,
            reported_at=self.runtime.now,
            status="reported",
        )
        self.disruptions[disruption_id] = disruption
        self._created(
            "disruption.reported",
            disruption,
            target_id=resource_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            extra_payload={"kind": kind, "resource_id": resource_id},
        )
        return disruption

    def apply_command(self, command: SimulationCommand) -> SimulationEvent:
        """Typed, idempotent dispatch for the eight portfolio commands.

        Replaying a previously-seen `command_id` (whether it succeeded or
        was rejected) always returns the cached event unchanged and never
        re-mutates or re-journals: the cache is keyed purely by
        `command_id`, never by command type or payload, so a genuine retry
        with the exact same id is always safe.
        """
        cached = self._processed_commands.get(command.command_id)
        if cached is not None:
            return cached

        handler = COMMAND_HANDLERS.get(command.type)
        result = (
            reject(self, command, f"unknown command type {command.type!r}")
            if handler is None
            else handler(self, command)
        )
        self._processed_commands[command.command_id] = result
        return result

    def run_reference_process(self, workflow_type: str) -> dict[str, Any]:
        """Run one real sensor -> objective -> command -> evaluation pass.

        Drives the generic `api.server.world` objective/command/evaluation
        machinery for `workflow_type`'s reference case end to end as a pure
        Python call: arranges the exact world state the case needs, runs
        its real detector, opens and claims a real objective, and applies
        its real command through the same `CommandGateway` the live bridge
        uses. No world-process HTTP run route is exercised --
        this is a pure diagnostic call for tests and tooling; a later task
        owns scheduling this pipeline live inside a running world.
        """
        from api.server.world.commands import CommandGateway
        from api.server.world.objectives import ObjectiveManager
        from verticals.travel.worlds.processes import REFERENCE_CASES
        from verticals.travel.worlds.registration import (
            responder_for_workflow_type,
            route_for_workflow_type,
        )

        case = REFERENCE_CASES[workflow_type]
        case.setup(self)
        sensor_event = case.detect(self)

        route = route_for_workflow_type(workflow_type)
        responder = responder_for_workflow_type(workflow_type)
        objectives = ObjectiveManager(self.runtime)
        objective = objectives.open(
            sensor_event.to_dict(), route, owner_function=responder.owner_function,
        )
        # Objective is immutable: transition() returns the updated instance
        # rather than mutating in place, so the local binding must be
        # reassigned or build_command below would see a stale claimed_by.
        objective = objectives.transition(objective.id, "claimed", claimed_by=case.role)
        objective = objectives.transition(objective.id, "acting")

        gateway = CommandGateway(self.runtime, objectives, self.apply_command)
        command = case.build_command(self, objective)
        result_event = gateway.apply(objective, command)
        evaluation = gateway.evaluator.for_objective(objective.id)
        result_payload = result_event.payload or {}

        return {
            "workflow_type": workflow_type,
            "command_id": command.command_id,
            "trace_id": command.trace_id,
            "affected_actor_ids": result_payload.get("affected_actor_ids"),
            "evidence_event_ids": result_payload.get("evidence_event_ids"),
            "evaluation_status": evaluation.status if evaluation is not None else None,
        }

    # -- Task 5: autonomous operational disruption -----------------------------

    def _operations_flight_cancellation(self):
        """Autonomous minute-180 disruption: a real supplier/operations
        cancellation of FLT-ZV204, strictly after its own ordinary
        shopping/booking activity has produced a real paid booking on it.

        Mutates `Flight.status` to `"cancelled"` and reports a real
        disruption, both causally chained by cause_event_id/trace_id, then
        runs a *separate* sensor-evaluation step against the now-mutated
        world state through the real generated detector -- never an
        unconditional `sensor.tripped` emission. The detector itself
        (`verticals.travel.worlds.processes.detect_flight_cancellation_impact`)
        owns the eligibility gate (no eligible booking means no sensor) and
        the rising-edge/no-repeat guarantee, so calling it again later (or
        from anywhere else) is always a safe no-op. This mutation never
        releases or rebooks capacity by itself -- recovery is a distinct,
        later task's command.
        """
        yield self.runtime.env.timeout(180)
        flight = self.flights["FLT-ZV204"]
        cancelled_event = self._apply(
            "flight.cancelled",
            flight,
            {"status": "cancelled"},
            extra_payload={"reason": "supplier_operational_cancellation"},
        )
        self.report_disruption(
            kind="flight_cancellation",
            resource_id=flight.id,
            cause_event_id=cancelled_event.event_id,
            trace_id=cancelled_event.trace_id,
        )
        processes.detect_flight_cancellation_impact(self)

    # -- Task 6: flight-disruption-recovery observation ------------------------

    def build_observation(
        self, sensor_event: dict[str, Any], *, now: float | None = None
    ) -> dict[str, Any]:
        """Turn one `sensor:flight_cancellation_impact` `sensor.tripped` event
        into the single flat, JSON-only observation dict that both the pure
        `verticals.travel.recovery.planner.plan_recovery_options` and the
        real Azure Durable Functions
        `verticals.travel.durable.functions.TravelRecoveryDetect` /
        `TravelRecoveryAssessImpact` activities read. `sensor_event` is a
        plain dict (the same `SimulationEvent.to_dict()` shape the world
        bridge already publishes as `FleetEvent.simulation_event`), so this
        method never depends on a live event object -- only JSON-shaped
        data flows onward from here, matching a real Durable orchestrator's
        own no-object-identity replay constraint. `now` lets a caller pin
        the observation's clock reading to a specific moment (e.g. the
        world's own `runtime.now` at sensor-trip time) instead of
        whatever the world's clock reads when this method happens to run;
        defaults to `self.runtime.now` when omitted.

        Deliberately supports exactly one affected booking and party per
        sensor event: every reference disruption in this world's own
        reference data (FLT-ZV204, FLT-ZV102) only ever has one
        paid/confirmed booking against it. Raising here instead of
        silently only recovering the first affected party would otherwise
        hide unrecovered demand -- a genuinely multi-party disruption is
        out of this task's scope.
        """
        payload = sensor_event.get("payload", {})
        disruption_id = payload["disruption_id"]
        flight_id = payload["flight_id"]
        booking_ids = payload["booking_ids"]
        party_ids = payload["party_ids"]
        if len(booking_ids) != 1 or len(party_ids) != 1:
            raise ValueError(
                "build_observation supports exactly one affected booking and party per "
                f"flight_cancellation_impact sensor event; disruption {disruption_id!r} named "
                f"{len(booking_ids)} booking(s) and {len(party_ids)} part(y/ies)"
            )

        booking = self.bookings[booking_ids[0]]
        party = self.parties[party_ids[0]]
        old_flight = self.flights[flight_id]
        hotel = self.hotels[booking.hotel_id]

        candidate_flights = [
            {
                "flight_id": flight.id,
                "supplier_id": flight.supplier_id,
                "destination_id": flight.destination_id,
                "scheduled_departure": flight.scheduled_departure,
                "scheduled_arrival": flight.scheduled_arrival,
                "capacity": flight.capacity,
                "reserved": flight.reserved,
                "status": flight.status,
                "base_fare_gbp": flight.base_fare_gbp,
            }
            for flight in sorted(self.flights.values(), key=lambda flight: flight.id)
            if flight.id != flight_id
            and flight.destination_id == old_flight.destination_id
            and flight.status == "scheduled"
        ]
        candidate_transfers = [
            {
                "transfer_id": transfer.id,
                "flight_id": transfer.flight_id,
                "destination_id": transfer.destination_id,
                "supplier_id": transfer.supplier_id,
                "capacity": transfer.capacity,
                "reserved": transfer.reserved,
                "status": transfer.status,
            }
            for transfer in sorted(self.transfers.values(), key=lambda transfer: transfer.id)
        ]

        return {
            "sensor_id": payload.get("sensor_id", "sensor:flight_cancellation_impact"),
            "trace_id": sensor_event["trace_id"],
            "disruption_id": disruption_id,
            "flight_id": flight_id,
            "booking_id": booking.id,
            "party_id": party.id,
            "party_size": party.size,
            "member_customer_ids": list(party.member_customer_ids),
            "hotel_id": booking.hotel_id,
            "hotel_supplier_id": hotel.supplier_id,
            "allotment_id": booking.allotment_id,
            "old_transfer_id": booking.transfer_id,
            "destination_id": old_flight.destination_id,
            "old_flight": {
                "flight_id": old_flight.id,
                "supplier_id": old_flight.supplier_id,
                "destination_id": old_flight.destination_id,
                "scheduled_departure": old_flight.scheduled_departure,
                "scheduled_arrival": old_flight.scheduled_arrival,
                "capacity": old_flight.capacity,
                "reserved": old_flight.reserved,
            },
            "candidate_flights": candidate_flights,
            "candidate_transfers": candidate_transfers,
            "now": now if now is not None else self.runtime.now,
            "evidence_event_ids": [sensor_event.get("event_id")],
        }

    # -- scene-renderer-ready state -------------------------------------------

    def render_state(self) -> dict[str, Any]:
        def rows(
            mapping: dict[str, Any],
            extra: Callable[[Any], dict[str, Any]] | None = None,
        ) -> list[dict[str, Any]]:
            result = []
            for record in sorted(mapping.values(), key=lambda record: record.id):
                row = _jsonify(dataclasses.asdict(record))
                if extra is not None:
                    row.update(_jsonify(extra(record)))
                result.append(row)
            return result

        # -- Task 8: JSON-safe derived scene fields for the generic spatial
        # world renderer. Every value below is derived from this same
        # authoritative, journal-backed state (real flight/transfer
        # schedule and status, real party/booking location, real hotel
        # allotment occupancy) -- never decorative or random -- so it
        # changes only when the record it is derived from changes.

        # `self.runtime.now` only ever advances to the sim_time of the most
        # recently *processed* event -- anywhere in this shared world, not
        # necessarily this flight's own timeline (`run_until` steps event
        # by event rather than forcing a wall clock) -- so interpolating a
        # single flight's elapsed-journey fraction against it would risk a
        # stale, misleadingly-precise value driven by an unrelated event
        # elsewhere. A real, authoritative, status-derived progress value
        # is used instead, exactly mirroring how transfers (which carry no
        # timing fields at all) are already derived below.
        _FLIGHT_PROGRESS = {"scheduled": 0.0, "departed": 0.5, "arrived": 1.0, "cancelled": 0.0}

        def _flight_extra(flight: Flight) -> dict[str, Any]:
            return {
                "route_location_ids": [flight.origin_airport_id, flight.destination_id],
                "progress": _FLIGHT_PROGRESS.get(flight.status, 0.0),
            }

        def _hotel_for_destination(destination_id: str) -> Hotel | None:
            return next(
                (hotel for hotel in self.hotels.values() if hotel.destination_id == destination_id),
                None,
            )

        _TRANSFER_PROGRESS = {"scheduled": 0.0, "in_progress": 0.5, "completed": 1.0}

        def _transfer_extra(transfer: Transfer) -> dict[str, Any]:
            hotel = _hotel_for_destination(transfer.destination_id)
            return {
                "route_location_ids": [transfer.destination_id, hotel.id if hotel is not None else None],
                "progress": _TRANSFER_PROGRESS.get(transfer.status, 0.0),
            }

        def _party_location(party: TravellingParty | None) -> str | None:
            if party is None:
                return None
            if party.location in self.flights:
                # Airborne: mid-flight is a genuine transient gap between
                # named real-world locations, not an invented position.
                return None
            return party.location

        def _party_extra(party: TravellingParty) -> dict[str, Any]:
            return {"current_location_id": _party_location(party)}

        def _party_for_customer(customer_id: str) -> TravellingParty | None:
            return next(
                (
                    party
                    for party in self.parties.values()
                    if party.lead_customer_id == customer_id
                    or customer_id in party.member_customer_ids
                ),
                None,
            )

        def _customer_extra(customer: Customer) -> dict[str, Any]:
            party = _party_for_customer(customer.id)
            location = _party_location(party) if party is not None else None
            return {"current_location_id": location if location is not None else "home"}

        def _booking_extra(booking: Booking) -> dict[str, Any]:
            return {"current_location_id": _party_location(self.parties.get(booking.party_id))}

        def _disruption_extra(disruption: Disruption) -> dict[str, Any]:
            flight = self.flights.get(disruption.resource_id)
            return {"current_location_id": flight.origin_airport_id if flight is not None else None}

        def _recovery_decision_extra(decision: RecoveryDecision) -> dict[str, Any]:
            command = next(
                (
                    candidate
                    for candidate in self.recovery_commands.values()
                    if candidate.workflow_id == decision.workflow_id
                ),
                None,
            )
            party = self.parties.get(command.party_id) if command is not None else None
            return {"current_location_id": _party_location(party)}

        def _staff_extra(_staff: StaffMember) -> dict[str, Any]:
            # No per-staff-member location is modelled in this world: every
            # staff action (check-in, arrival handling) is issued from the
            # single real operations base, never a travel location.
            return {"current_location_id": "home"}

        def _hotel_extra(hotel: Hotel) -> dict[str, Any]:
            allotment = next(
                (a for a in self.allotments.values() if a.hotel_id == hotel.id),
                None,
            )
            if allotment is None or allotment.allotment <= 0:
                return {"occupancy_ratio": 0.0, "capacity_ratio": 0.0, "occupancy_status": "normal"}
            occupancy_ratio = allotment.occupied / allotment.allotment
            capacity_ratio = allotment.reserved / allotment.allotment
            if occupancy_ratio >= 1.0:
                occupancy_status = "full"
            elif occupancy_ratio >= 0.85:
                occupancy_status = "near_full"
            else:
                occupancy_status = "normal"
            return {
                "occupancy_ratio": occupancy_ratio,
                "capacity_ratio": capacity_ratio,
                "occupancy_status": occupancy_status,
            }

        bookings_paid = sum(1 for booking in self.bookings.values() if booking.status == "paid")
        return {
            "seed": self.seed,
            "sim_time": self.runtime.now,
            "status": self.runtime.status,
            "airports": rows(self.airports),
            "destinations": rows(self.destinations),
            "suppliers": rows(self.suppliers),
            "staff": rows(self.staff, _staff_extra),
            "customers": rows(self.customers, _customer_extra),
            "parties": rows(self.parties, _party_extra),
            "flights": rows(self.flights, _flight_extra),
            "hotels": rows(self.hotels, _hotel_extra),
            "allotments": rows(self.allotments),
            "transfers": rows(self.transfers, _transfer_extra),
            "quotes": rows(self.quotes),
            "bookings": rows(self.bookings, _booking_extra),
            "payments": rows(self.payments),
            "refunds": rows(self.refunds),
            "disruptions": rows(self.disruptions, _disruption_extra),
            "care_actions": rows(self.care_actions),
            "recovery_decisions": rows(self.recovery_decisions, _recovery_decision_extra),
            "recovery_commands": rows(self.recovery_commands),
            "recovery_evaluations": rows(self.recovery_evaluations),
            "summary": {
                "customers": len(self.customers),
                "parties": len(self.parties),
                "flights": len(self.flights),
                "hotels": len(self.hotels),
                "transfers": len(self.transfers),
                "quotes": len(self.quotes),
                "bookings": len(self.bookings),
                "bookings_paid": bookings_paid,
                "payments": len(self.payments),
                "care_actions": len(self.care_actions),
                "recovery_commands": len(self.recovery_commands),
            },
        }
