"""Travel: one machine agent per process (generated by
verticals.travel.generator.pack_templates).

Every agent's `allowed_tools` is that process's own `mcps.
travel_operations` tool pair, and `max_value_gbp` is bounded by its
authorising role's spend limit -- a machine agent can never propose
beyond what a human in that role could itself approve.

Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.agent_contracts import AgentRegistryEntry

TRAVEL_AGENTS: dict[str, AgentRegistryEntry] = {
    'travel-hsb-assistant': AgentRegistryEntry(
        agent_id='travel-hsb-assistant',
        allowed_tools=('travel_operations_check_quote_offer', 'travel_operations_reserve_package_capacity'),
        max_value_gbp=2000.0,
        reversible_only=True,
        scope_function='commercial',
        description="Assistant agent for Holiday Sales Booking: proposes and drafts the confirm_package_booking action within travel_adviser's bounded authority; every write is journalled and reversible.",
    ),
    'travel-cym-assistant': AgentRegistryEntry(
        agent_id='travel-cym-assistant',
        allowed_tools=('travel_operations_check_allotment_headroom', 'travel_operations_move_allotment_rooms'),
        max_value_gbp=5000.0,
        reversible_only=True,
        scope_function='commercial',
        description="Assistant agent for Capacity Yield Management: proposes and drafts the adjust_package_allotment action within revenue_manager's bounded authority; every write is journalled and reversible.",
    ),
    'travel-fdr-assistant': AgentRegistryEntry(
        agent_id='travel-fdr-assistant',
        allowed_tools=('travel_operations_check_flight_disruption', 'travel_operations_reaccommodate_booking'),
        max_value_gbp=750.0,
        reversible_only=True,
        scope_function='operations-control',
        description="Assistant agent for Flight Disruption Recovery: proposes and drafts the reaccommodate_travellers action within operations_controller's bounded authority; every write is journalled and reversible.",
    ),
    'travel-hsr-assistant': AgentRegistryEntry(
        agent_id='travel-hsr-assistant',
        allowed_tools=('travel_operations_check_allotment_headroom', 'travel_operations_move_allotment_rooms'),
        max_value_gbp=5000.0,
        reversible_only=True,
        scope_function='accommodation-supply',
        description="Assistant agent for Hotel Supplier Recovery: proposes and drafts the move_hotel_allotment action within accommodation_manager's bounded authority; every write is journalled and reversible.",
    ),
    'travel-cxr-assistant': AgentRegistryEntry(
        agent_id='travel-cxr-assistant',
        allowed_tools=('travel_operations_check_booking_status', 'travel_operations_release_booking_capacity'),
        max_value_gbp=2000.0,
        reversible_only=True,
        scope_function='customer-finance',
        description="Assistant agent for Cancellation Refund: proposes and drafts the cancel_and_refund_booking action within finance_operations_lead's bounded authority; every write is journalled and reversible.",
    ),
    'travel-pex-assistant': AgentRegistryEntry(
        agent_id='travel-pex-assistant',
        allowed_tools=('travel_operations_check_booking_status', 'travel_operations_release_booking_capacity'),
        max_value_gbp=5000.0,
        reversible_only=True,
        scope_function='customer-finance',
        description="Assistant agent for Payment Exception: proposes and drafts the resolve_payment_exception action within payments_specialist's bounded authority; every write is journalled and reversible.",
    ),
    'travel-dop-assistant': AgentRegistryEntry(
        agent_id='travel-dop-assistant',
        allowed_tools=('travel_operations_check_transfer_risk', 'travel_operations_dispatch_replacement_transfer'),
        max_value_gbp=1000.0,
        reversible_only=True,
        scope_function='destination-operations',
        description="Assistant agent for Destination Operations: proposes and drafts the dispatch_replacement_transfer action within destination_operations_manager's bounded authority; every write is journalled and reversible.",
    ),
    'travel-pcc-assistant': AgentRegistryEntry(
        agent_id='travel-pcc-assistant',
        allowed_tools=('travel_operations_check_booking_status', 'travel_operations_issue_care_action'),
        max_value_gbp=500.0,
        reversible_only=True,
        scope_function='customer-care',
        description="Assistant agent for Proactive Customer Care: proposes and drafts the issue_customer_care_action action within customer_care_lead's bounded authority; every write is journalled and reversible.",
    ),
}
