"""Exact workflow-detail assembler for Travel's flight-disruption-recovery
hero (Task 7 Required B).

`workflow_detail(workflow, app_state)` is the two-argument hook
`VerticalPack.workflow_detail_hook` carries -- richer than the pure
`ProjectionFn` contract because assembling a human-inspectable detail
payload legitimately needs live world state the industry-neutral
`Workflow.payload` alone does not carry (the Travel-owned
`RecoveryEvaluation.status` and the generic `Objective.status`, both only
ever available off `app_state.world_service`). The generic
`GET /api/workflows/{id}` route (`api/server/routes/workflows.py`) calls
this hook -- when the active pack declares one -- and merges its return
value under a single `"packDetail"` response key; the route itself carries
zero Travel-specific branching.

Every field here is read from the real terminal Task-6 evidence
(`workflow.payload["evidence"]`, the orchestrator's own `_build_output()`
dict) or the trigger-time `workflow.payload["observation"]` -- never
fabricated. Trigger information (`observation`) and Durable/objective
identity are available from the moment the workflow opens, so
`workflow_detail` always returns a real dict once `observation` exists
(never `None` just because the workflow has not yet reached a terminal
state) -- but `command`/`evaluation`/`hitl` sub-fields stay truthfully
`None`/not-applicable until the evidence that would populate them actually
exists. No success-shaped defaults: missing evidence remains absent, never
invented.

This module is generated by verticals.travel.generator.knowledge_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from typing import Any, Mapping

from api.shared.types import Workflow

WORKFLOW_TYPE = "flight-disruption-recovery"

_EVALUATION_CRITERIA = (
    "booking now points at the new flight/transfer with recovery_status="
    "'reaccommodated', party.state='reaccommodated', and seat/room capacity "
    "on both the released and reserved flight/transfer legs stays within "
    "[0, capacity] on both sides of the move"
)


def _trigger(observation: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "disruption_id": observation.get("disruption_id"),
        "flight_id": observation.get("flight_id"),
        "booking_id": observation.get("booking_id"),
        "party_id": observation.get("party_id"),
        "member_customer_ids": list(observation.get("member_customer_ids") or []),
        "hotel_id": observation.get("hotel_id"),
        "hotel_supplier_id": observation.get("hotel_supplier_id"),
        "sensor_id": observation.get("sensor_id"),
        "old_transfer_id": observation.get("old_transfer_id"),
        "destination_id": observation.get("destination_id"),
        "evidence_event_ids": list(observation.get("evidence_event_ids") or []),
    }


def _phase_records(
    observation: Mapping[str, Any], evidence: Mapping[str, Any],
    evaluation: Mapping[str, Any] | None,
) -> list[dict[str, Any]]:
    command = evidence.get("command")
    decision = evidence.get("decision") or {}
    notify = evidence.get("notify")
    options = evidence.get("options") or []
    option_id = evidence.get("option_id")
    hitl_audit = evidence.get("hitl_audit") or {}

    has_alternatives = bool(options)
    approve_status = decision.get("outcome") or ("no_alternative" if option_id is None else "pending")
    if evaluation is not None:
        evaluate_status = evaluation.get("status")
    elif isinstance(command, dict):
        # A command was authorised/applied but the Travel-owned
        # `RecoveryEvaluation` record could not be found on the live world
        # service -- an anomalous state, reported truthfully rather than
        # papered over as "completed".
        evaluate_status = "unknown"
    else:
        # No command was ever authorised (declined / no-alternative /
        # timed-out terminal outcome) -- there is genuinely nothing to
        # evaluate.
        evaluate_status = "not_applicable"
    return [
        {
            "name": "detect",
            "status": "completed",
            "evidence": {
                "disruption_id": observation.get("disruption_id"),
                "flight_id": observation.get("flight_id"),
                "booking_id": observation.get("booking_id"),
                "party_id": observation.get("party_id"),
            },
        },
        {
            "name": "assess_impact",
            "status": "completed",
            "evidence": {
                "party_size": observation.get("party_size"),
                "member_customer_ids": list(observation.get("member_customer_ids") or []),
                "destination_id": observation.get("destination_id"),
            },
        },
        {
            "name": "search_alternatives",
            "status": "completed" if has_alternatives else "no_alternative",
            "evidence": {"option_count": len(options)},
        },
        {
            "name": "bound_options",
            "status": "completed" if has_alternatives else "no_alternative",
            "evidence": {"options": options},
        },
        {
            "name": "approve_material_change",
            "status": approve_status,
            "evidence": {"requires_approval": bool(hitl_audit.get("required")), "decision": decision},
        },
        {
            "name": "reaccommodate",
            "status": "completed" if isinstance(command, dict) else "not_applicable",
            "evidence": (command or {}).get("payload", {}) if isinstance(command, dict) else {},
        },
        {
            "name": "notify",
            "status": "completed" if notify else "not_applicable",
            "evidence": notify or {},
        },
        {
            "name": "evaluate",
            "status": evaluate_status,
            "evidence": {
                "evaluation_intent": evidence.get("evaluation_intent"),
                "evaluation": evaluation,
            },
        },
    ]


def _reasoning(evidence: Mapping[str, Any]) -> dict[str, Any]:
    options = evidence.get("options") or []
    option_id = evidence.get("option_id")
    booking_id = evidence.get("booking_id")
    party_id = evidence.get("party_id")
    decision = evidence.get("decision") or {}
    hitl_required = bool((evidence.get("hitl_audit") or {}).get("required"))
    decided_by = decision.get("decided_by")
    affected_analysis = (
        f"booking {booking_id} for party {party_id} affected by this disruption; "
        f"{len(options)} ranked alternative(s) evaluated"
    )
    if hitl_required:
        authority_rule = (
            f"material-change / above-bound options require {decided_by or 'head_of_operations'} "
            "approval via the TravelRecoveryApproval human-in-the-loop gate"
        )
    else:
        authority_rule = (
            f"auto-approved under {decided_by or 'operations_controller'} bounded authority "
            "(non-material, within the auto-approve cost bound)"
        )
    return {
        "affected_analysis": affected_analysis,
        "alternatives": options,
        "selected_option": option_id,
        "authority_rule": authority_rule,
    }


def _hitl(workflow_id: str, evidence: Mapping[str, Any]) -> dict[str, Any]:
    hitl_audit = evidence.get("hitl_audit") or {}
    required = bool(hitl_audit.get("required"))
    if not required:
        return {
            "required": False,
            "gate_id": None,
            "decision_id": None,
            "required_role": None,
            "decision_actor": None,
            "outcome": None,
        }
    decision = evidence.get("decision") or {}
    command = evidence.get("command")
    skills = evidence.get("skills") or []
    cmd_payload = command.get("payload") if isinstance(command, dict) else None
    cmd_payload = cmd_payload if isinstance(cmd_payload, dict) else {}
    return {
        "required": True,
        "gate_id": workflow_id,
        "decision_id": cmd_payload.get("decision_id"),
        "required_role": skills[-1] if skills else None,
        "decision_actor": decision.get("decided_by"),
        "outcome": decision.get("outcome"),
    }


def _command(
    evidence: Mapping[str, Any], observation: Mapping[str, Any],
) -> dict[str, Any] | None:
    command = evidence.get("command")
    if not isinstance(command, dict):
        return None
    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    decision = evidence.get("decision") or {}
    return {
        "type": command.get("type"),
        "command_id": command.get("command_id"),
        "option_id": cmd_payload.get("option_id"),
        "booking_id": cmd_payload.get("booking_id"),
        "party_id": cmd_payload.get("party_id"),
        "old_flight_id": cmd_payload.get("old_flight_id"),
        "new_flight_id": cmd_payload.get("new_flight_id"),
        "old_supplier_id": cmd_payload.get("old_supplier_id"),
        "new_supplier_id": cmd_payload.get("new_supplier_id"),
        "hotel_id": cmd_payload.get("hotel_id"),
        "hotel_supplier_id": cmd_payload.get("hotel_supplier_id"),
        "old_transfer_id": cmd_payload.get("old_transfer_id"),
        "new_transfer_id": cmd_payload.get("new_transfer_id"),
        "new_transfer_supplier_id": cmd_payload.get("new_transfer_supplier_id"),
        "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
        # The exact traveller/customer ids from the trigger-time
        # observation -- not `RecoveryOption.affected_actor_ids`, which
        # deliberately mixes booking/flight/supplier ids alongside the
        # travellers themselves and would be a misleading source for a
        # field literally named "traveller ids".
        "traveller_ids": list(observation.get("member_customer_ids") or []),
        "decision_outcome": cmd_payload.get("decision_outcome") or decision.get("outcome"),
        "decided_by": cmd_payload.get("decided_by") or decision.get("decided_by"),
    }


def _evaluation(workflow_id: str, evidence: Mapping[str, Any], app_state: Any) -> dict[str, Any] | None:
    command = evidence.get("command")
    if not isinstance(command, dict):
        return None
    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    option_id = cmd_payload.get("option_id") or evidence.get("option_id")
    if not option_id:
        return None
    evaluation_id = f"EVAL-{workflow_id}-{option_id}"
    world_service = getattr(app_state, "world_service", None)
    scenario = getattr(world_service, "scenario", None)
    recovery_evaluations = getattr(scenario, "recovery_evaluations", None) or {}
    recovery_eval = recovery_evaluations.get(evaluation_id)
    if recovery_eval is None:
        return None
    return {
        "evaluation_id": evaluation_id,
        "command_id": getattr(recovery_eval, "command_id", command.get("command_id")),
        "booking_id": getattr(recovery_eval, "booking_id", None),
        "party_id": getattr(recovery_eval, "party_id", None),
        "status": getattr(recovery_eval, "status", None),
        "criteria": _EVALUATION_CRITERIA,
    }


def _objective(payload: Mapping[str, Any], app_state: Any) -> dict[str, Any] | None:
    objective_id = payload.get("objective_id")
    if not objective_id:
        return None
    world_service = getattr(app_state, "world_service", None)
    objectives = getattr(world_service, "objectives", None)
    objective = objectives.get(objective_id) if objectives is not None else None
    return {
        "objective_id": objective_id,
        "status": getattr(objective, "status", None) if objective is not None else None,
    }


def _durable(workflow: Workflow, payload: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "workflow_id": workflow.id,
        "orchestration_instance_id": workflow.orchestration_instance_id,
        "trace_id": payload.get("trace_id"),
    }


def workflow_detail(workflow: Workflow, app_state: Any) -> Mapping[str, Any] | None:
    if getattr(workflow, "type", None) != WORKFLOW_TYPE:
        return None
    payload = workflow.payload if isinstance(workflow.payload, dict) else {}
    observation = payload.get("observation")
    if not isinstance(observation, dict):
        return None

    evidence = payload.get("evidence")
    evidence = evidence if isinstance(evidence, dict) else None
    trigger = _trigger(observation)

    if evidence is None:
        return {
            "trigger": trigger,
            "phases": [],
            "skills": [],
            "tools": [],
            "reasoning": None,
            "hitl": None,
            "command": None,
            "evaluation": None,
            "objective": _objective(payload, app_state),
            "durable": _durable(workflow, payload),
        }

    workflow_id = workflow.id
    evaluation = _evaluation(workflow_id, evidence, app_state)
    return {
        "trigger": trigger,
        "phases": _phase_records(observation, evidence, evaluation),
        "skills": list(evidence.get("skills") or []),
        "tools": list(evidence.get("tools") or []),
        "reasoning": _reasoning(evidence),
        "hitl": _hitl(workflow_id, evidence),
        "command": _command(evidence, observation),
        "evaluation": evaluation,
        "objective": _objective(payload, app_state),
        "durable": _durable(workflow, payload),
    }
