"""Travel: the eight-process portfolio's Domain declarations
(generated by verticals.travel.generator.pack_templates).

`function` is populated by the same `wire_domain_functions` helper
every other vertical pack uses (from `verticals._helpers`, a
cross-vertical utility, not Travel-specific), cross-validating that
`TRAVEL_FUNCTIONS`'s `owns_domains` rows exactly partition these eight
workflow types with no gaps or overlaps.

Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.domain_contracts import Domain, HitlGate, Phase
from verticals._helpers import wire_domain_functions
from verticals.travel.functions import TRAVEL_FUNCTIONS

_RAW_DOMAINS: dict[str, Domain] = {
    'holiday-sales-booking': Domain(
        workflow_type='holiday-sales-booking',
        display_name='Holiday Sales Booking',
        workflow_id_prefix='hsb',
        orchestrator_name='HolidaySalesBookingOrchestrator',
        operator_surface='commercial-manager',
        phases=(
            Phase(name='detect_demand', kind='deterministic'),
            Phase(name='assess_quote', kind='agent'),
            Phase(name='confirm_and_pay', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('holiday-sales-booking',),
        stub=False,
    ),
    'capacity-yield-management': Domain(
        workflow_type='capacity-yield-management',
        display_name='Capacity Yield Management',
        workflow_id_prefix='cym',
        orchestrator_name='CapacityYieldManagementOrchestrator',
        operator_surface='commercial-manager',
        phases=(
            Phase(name='detect_pressure', kind='deterministic'),
            Phase(name='plan_adjustment', kind='agent'),
            Phase(name='execute_adjustment', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('capacity-yield-management',),
        stub=False,
    ),
    'flight-disruption-recovery': Domain(
        workflow_type='flight-disruption-recovery',
        display_name='Flight Disruption Recovery',
        workflow_id_prefix='fdr',
        orchestrator_name='FlightDisruptionRecoveryOrchestrator',
        operator_surface='operations-controller',
        phases=(
            Phase(name='detect_cancellation', kind='deterministic'),
            Phase(name='assess_impact', kind='agent'),
            Phase(name='escalate', kind='hitl'),
            Phase(name='reaccommodate', kind='deterministic'),
        ),
        hitl_gates=(
            HitlGate(
                gate_phase='escalate',
                external_event='reaccommodation_approval',
                persona='head_of_operations',
                wait_probability=0.3,
            ),
        ),
        skills=('flight-disruption-recovery',),
        stub=False,
    ),
    'hotel-supplier-recovery': Domain(
        workflow_type='hotel-supplier-recovery',
        display_name='Hotel Supplier Recovery',
        workflow_id_prefix='hsr',
        orchestrator_name='HotelSupplierRecoveryOrchestrator',
        operator_surface='accommodation-manager',
        phases=(
            Phase(name='detect_shortfall', kind='deterministic'),
            Phase(name='assess_recovery', kind='agent'),
            Phase(name='plan_move', kind='agent'),
            Phase(name='execute_move', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('hotel-supplier-recovery',),
        stub=False,
    ),
    'cancellation-refund': Domain(
        workflow_type='cancellation-refund',
        display_name='Cancellation Refund',
        workflow_id_prefix='cxr',
        orchestrator_name='CancellationRefundOrchestrator',
        operator_surface='finance-operations-lead',
        phases=(
            Phase(name='detect_cancellation', kind='deterministic'),
            Phase(name='assess_refund', kind='agent'),
            Phase(name='settle', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('cancellation-refund',),
        stub=False,
    ),
    'payment-exception': Domain(
        workflow_type='payment-exception',
        display_name='Payment Exception',
        workflow_id_prefix='pex',
        orchestrator_name='PaymentExceptionOrchestrator',
        operator_surface='finance-operations-lead',
        phases=(
            Phase(name='detect_exception', kind='deterministic'),
            Phase(name='assess_resolution', kind='agent'),
            Phase(name='resolve', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('payment-exception',),
        stub=False,
    ),
    'destination-operations': Domain(
        workflow_type='destination-operations',
        display_name='Destination Operations',
        workflow_id_prefix='dop',
        orchestrator_name='DestinationOperationsOrchestrator',
        operator_surface='destination-operations-manager',
        phases=(
            Phase(name='detect_risk', kind='deterministic'),
            Phase(name='plan_replacement', kind='agent'),
            Phase(name='dispatch', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('destination-operations',),
        stub=False,
    ),
    'proactive-customer-care': Domain(
        workflow_type='proactive-customer-care',
        display_name='Proactive Customer Care',
        workflow_id_prefix='pcc',
        orchestrator_name='ProactiveCustomerCareOrchestrator',
        operator_surface='customer-care-lead',
        phases=(
            Phase(name='detect_change', kind='deterministic'),
            Phase(name='assess_care', kind='agent'),
            Phase(name='issue_action', kind='deterministic'),
        ),
        hitl_gates=(),
        skills=('proactive-customer-care',),
        stub=False,
    ),
}

TRAVEL_DOMAINS: dict[str, Domain] = wire_domain_functions(_RAW_DOMAINS, dict(TRAVEL_FUNCTIONS))
TRAVEL_HERO_WORKFLOW_TYPES: frozenset[str] = frozenset(('flight-disruption-recovery', 'hotel-supplier-recovery'))
