"""Travel: the six organisation functions grouping the eight-process
portfolio (generated by verticals.travel.generator.pack_templates).

Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.function_contracts import Function, PersonaTree

TRAVEL_FUNCTIONS: dict[str, Function] = {
    'commercial': Function(
        name='commercial',
        display='Commercial',
        operator_surface='commercial-manager',
        owns_domains=('holiday-sales-booking', 'capacity-yield-management'),
        ambient_agents=('travel-hsb-assistant', 'travel-cym-assistant'),
        kpis=('conversion_rate_pct', 'package_margin_pct', 'capacity_utilisation_pct'),
        persona_hierarchy=PersonaTree(
            role='head_of_commercial',
            manages=(PersonaTree(role='travel_adviser'), PersonaTree(role='revenue_manager')),
        ),
    ),
    'operations-control': Function(
        name='operations-control',
        display='Operations Control',
        operator_surface='operations-controller',
        owns_domains=('flight-disruption-recovery',),
        ambient_agents=('travel-fdr-assistant',),
        kpis=('recovery_time_hours', 'rebooking_success_rate_pct', 'disruption_cost_gbp'),
        persona_hierarchy=PersonaTree(
            role='head_of_operations',
            manages=(PersonaTree(role='operations_controller'),),
        ),
    ),
    'accommodation-supply': Function(
        name='accommodation-supply',
        display='Accommodation & Supply',
        operator_surface='accommodation-manager',
        owns_domains=('hotel-supplier-recovery',),
        ambient_agents=('travel-hsr-assistant',),
        kpis=('allotment_utilisation_pct', 'shortfall_resolution_time_hours', 'supplier_slippage_rate'),
        persona_hierarchy=PersonaTree(
            role='head_of_accommodation',
            manages=(PersonaTree(role='accommodation_manager'),),
        ),
    ),
    'customer-finance': Function(
        name='customer-finance',
        display='Customer Finance',
        operator_surface='finance-operations-lead',
        owns_domains=('cancellation-refund', 'payment-exception'),
        ambient_agents=('travel-cxr-assistant', 'travel-pex-assistant'),
        kpis=('refund_cycle_time_hours', 'payment_exception_rate_pct', 'revenue_at_risk_gbp'),
        persona_hierarchy=PersonaTree(
            role='head_of_customer_finance',
            manages=(PersonaTree(role='finance_operations_lead'), PersonaTree(role='payments_specialist')),
        ),
    ),
    'destination-operations': Function(
        name='destination-operations',
        display='Destination Operations',
        operator_surface='destination-operations-manager',
        owns_domains=('destination-operations',),
        ambient_agents=('travel-dop-assistant',),
        kpis=('transfer_sla_pct', 'on_ground_incident_rate'),
        persona_hierarchy=PersonaTree(
            role='head_of_destination_operations',
            manages=(PersonaTree(role='destination_operations_manager'),),
        ),
    ),
    'customer-care': Function(
        name='customer-care',
        display='Customer Care',
        operator_surface='customer-care-lead',
        owns_domains=('proactive-customer-care',),
        ambient_agents=('travel-pcc-assistant',),
        kpis=('care_response_time_minutes', 'goodwill_spend_gbp', 'customer_satisfaction_score'),
        persona_hierarchy=PersonaTree(
            role='head_of_customer_care',
            manages=(PersonaTree(role='customer_care_lead'),),
        ),
    ),
}
