"""Travel: pack lifecycle start/stop hooks (generated by
verticals.travel.generator).

Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any


async def start(_state: Any) -> Sequence[Any]:
    """No background tasks to start yet: returns no stop actions.

    Task 4 only needs the pure, diagnostic
    `TravelWorld.run_reference_process` call path (see
    `verticals.travel.worlds.scenario`), which never needs a background
    task. A later task owns scheduling the live detector/objective
    pipeline against a running world here.
    """
    return ()
