"""Travel VerticalPack manifest (generated by verticals.travel.generator).

Builds the discoverable `VerticalPack` for `ZAVA_VERTICAL=travel`: eight
non-stub Domains, six organisation Functions, the fourteen-row bounded GBP
authority matrix, one Persona per authority role, one machine agent per
process, the pack-local `skills/` and `personae/` roots, the
`mcps.travel_operations` tool module, the pure `durable/` phase-plan
engine, and the `travel` world (default scale `demo`). Task 7 additionally
registers the pack-owned Knowledge-graph projection and workflow-detail
hook for `flight-disruption-recovery` (`projections/knowledge.py` and
`detail.py`) -- never on any shared global registry.

Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from importlib import import_module
from pathlib import Path

from api.shared.vertical_pack import (
    DurableFunctionRegistration,
    LifecycleRegistration,
    RecordingSources,
    SeedRegistration,
    VerticalPack,
)
from verticals._helpers import load_ui_manifest
from verticals.travel.agents import TRAVEL_AGENTS
from verticals.travel.authority import TRAVEL_AUTHORITY
from verticals.travel.detail import workflow_detail
from verticals.travel.domains import TRAVEL_DOMAINS
from verticals.travel.functions import TRAVEL_FUNCTIONS
from verticals.travel.lifecycle import start
from verticals.travel.personas import TRAVEL_PERSONAS
from verticals.travel.projections.knowledge import WORKFLOW_TYPE as _KNOWLEDGE_WORKFLOW_TYPE
from verticals.travel.projections.knowledge import project as _project_knowledge
from verticals.travel.seed import bootstrap
from verticals.travel.worlds.registration import TRAVEL_WORLDS

PACK_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PACK_ROOT.parents[1]

# No third-party/network capability names yet: every Travel MCP operation is
# a real, in-process, deterministic query/mutation-planning helper over
# TravelWorld state (see mcps/travel_operations.py) -- none call out to an
# external system.
TRAVEL_EXTERNAL_CAPABILITIES: frozenset[str] = frozenset()


def _load_durable_module():
    return import_module("verticals.travel.durable")


def build_pack() -> VerticalPack:
    orchestrators = frozenset(
        domain.orchestrator_name for domain in TRAVEL_DOMAINS.values() if not domain.stub
    )
    return VerticalPack(
        root=PACK_ROOT,
        name="travel",
        display_name="Travel",
        manifest_version="1",
        domains=dict(TRAVEL_DOMAINS),
        organisation_functions=dict(TRAVEL_FUNCTIONS),
        agents=dict(TRAVEL_AGENTS),
        authority=dict(TRAVEL_AUTHORITY),
        personas=dict(TRAVEL_PERSONAS),
        policy_sources=(PACK_ROOT / "policies" / "tools.yaml",),
        durable_functions=DurableFunctionRegistration(
            load_module=_load_durable_module,
            orchestrators=orchestrators,
            activities=frozenset(),
        ),
        personae_roots=(PACK_ROOT / "personae",),
        skill_roots=(PACK_ROOT / "skills",),
        mcp_modules=("verticals.travel.mcps.travel_operations",),
        external_capabilities=TRAVEL_EXTERNAL_CAPABILITIES,
        worlds=dict(TRAVEL_WORLDS),
        default_world="travel",
        seed=SeedRegistration(bootstrap=bootstrap),
        projections={_KNOWLEDGE_WORKFLOW_TYPE: _project_knowledge},
        memory_workflow_types=(_KNOWLEDGE_WORKFLOW_TYPE,),
        lifecycle=LifecycleRegistration(start=start),
        recordings=RecordingSources(curated_dirs=()),
        ui=load_ui_manifest(PACK_ROOT / "ui.json"),
        ramp_workflow_types=(),
        workflow_detail_hook=workflow_detail,
    )
