"""Travel: one Persona per authority role (generated by
verticals.travel.generator.pack_templates).

Covers all fourteen `TRAVEL_AUTHORITY` roles: the eight process roles
plus their six escalation heads, matching every function's
`persona_hierarchy` in `functions.py`.

Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.persona_contracts import Persona

TRAVEL_PERSONAS: dict[str, Persona] = {
    'travel_adviser': Persona(
        role='travel_adviser',
        archetype="approver",
        scope_function='commercial',
        workflow_label='Holiday Sales Booking',
    ),
    'revenue_manager': Persona(
        role='revenue_manager',
        archetype="approver",
        scope_function='commercial',
        workflow_label='Capacity Yield Management',
    ),
    'operations_controller': Persona(
        role='operations_controller',
        archetype="approver",
        scope_function='operations-control',
        workflow_label='Flight Disruption Recovery',
    ),
    'accommodation_manager': Persona(
        role='accommodation_manager',
        archetype="approver",
        scope_function='accommodation-supply',
        workflow_label='Hotel Supplier Recovery',
    ),
    'finance_operations_lead': Persona(
        role='finance_operations_lead',
        archetype="approver",
        scope_function='customer-finance',
        workflow_label='Cancellation Refund',
    ),
    'payments_specialist': Persona(
        role='payments_specialist',
        archetype="approver",
        scope_function='customer-finance',
        workflow_label='Payment Exception',
    ),
    'destination_operations_manager': Persona(
        role='destination_operations_manager',
        archetype="approver",
        scope_function='destination-operations',
        workflow_label='Destination Operations',
    ),
    'customer_care_lead': Persona(
        role='customer_care_lead',
        archetype="approver",
        scope_function='customer-care',
        workflow_label='Proactive Customer Care',
    ),
    'head_of_commercial': Persona(
        role='head_of_commercial',
        archetype="approver",
        scope_function='commercial',
        workflow_label='Commercial escalation',
    ),
    'head_of_operations': Persona(
        role='head_of_operations',
        archetype="approver",
        scope_function='operations-control',
        workflow_label='Operations Control escalation',
    ),
    'head_of_accommodation': Persona(
        role='head_of_accommodation',
        archetype="approver",
        scope_function='accommodation-supply',
        workflow_label='Accommodation & Supply escalation',
    ),
    'head_of_customer_finance': Persona(
        role='head_of_customer_finance',
        archetype="approver",
        scope_function='customer-finance',
        workflow_label='Customer Finance escalation',
    ),
    'head_of_destination_operations': Persona(
        role='head_of_destination_operations',
        archetype="approver",
        scope_function='destination-operations',
        workflow_label='Destination Operations escalation',
    ),
    'head_of_customer_care': Persona(
        role='head_of_customer_care',
        archetype="approver",
        scope_function='customer-care',
        workflow_label='Customer Care escalation',
    ),
}
