"""Travel: pack seed bootstrap (generated by verticals.travel.generator).

Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from typing import Any


def bootstrap(_state: Any) -> None:
    """Nothing further to seed: TravelWorld seeds all of its own actors.

    `verticals.travel.worlds.scenario.TravelWorld.__init__` deterministically
    seeds every actor (airports, destinations, suppliers, staff, customers,
    parties, flights, hotels, allotments, transfers) via its own
    `_seed_world` on construction, so this hook has nothing left to
    bootstrap. It exists purely to satisfy
    `api.shared.vertical_pack.SeedRegistration`'s contract.
    """
    return None
