"""Deterministic synthetic hiring corpus generator for POC2.

Spine seed produces:
  - 50 CVs across 5 roles × 2 jurisdictions (USA, DE)
  - JD library (5 roles × 2 levels)
  - Policy bundles in USA/ and DE/ (BetrVG diverges from EEO)
  - employee directory + manager assignments

Reuses the deterministic-walk pattern from the POC1 expense generator
(`generate.py`) — same `_label_for_index` style picking which CV gets a
right-to-work gap, missing dates, etc. Per-track work in Track A.4 grows
this to the ~200-CV target in poc2-status.md §3 Track A.
"""
from __future__ import annotations
import json
from pathlib import Path

DATA = Path(__file__).parent
CVS = DATA / "cvs"
JDS = DATA / "jds"
LABELS = DATA / "labels.csv"

ROLES = [
    ("senior-data-engineer", "Senior Data Engineer", "L5"),
    ("frontend-engineer", "Frontend Engineer", "L3"),
    ("creative-director", "Creative Director", "L6"),
    ("media-strategist", "Media Strategist", "L4"),
    ("werkstudent-frontend", "Werkstudent Frontend Engineer", "L2"),
]
JURISDICTIONS = ("USA", "DE")
ROLE_INDEX_MAX = 5  # 5 candidates per role × jurisdiction = 50 CVs


def _build_cv(role_slug: str, role_title: str, level: str, jurisdiction: str, idx: int) -> dict:
    cid = f"C-{role_slug[:2].upper()}-{jurisdiction}-{idx:02d}"
    name_pool_usa = ["Alex Park", "Priya Mehta", "Daniel Chen", "Maria Rivera", "Jordan Lee"]
    name_pool_de = ["Lara Schmidt", "Felix Becker", "Anya Hoffmann", "Tobias Klein", "Isabel König"]
    name = (name_pool_usa if jurisdiction == "USA" else name_pool_de)[idx % 5]
    skills_by_role = {
        "senior-data-engineer": ["python", "spark", "airflow", "dbt", "kubernetes"],
        "frontend-engineer": ["typescript", "react", "vite", "tailwind", "playwright"],
        "creative-director": ["brand-strategy", "campaign-design", "shoot-direction"],
        "media-strategist": ["paid-media", "attribution", "audience-segmentation"],
        "werkstudent-frontend": ["typescript", "react", "tailwind"],
    }
    rtw_pool = (
        ["us_citizen", "green_card", "h1b", "us_citizen", "unknown"]
        if jurisdiction == "USA"
        else ["eu_citizen", "blue_card", "eu_citizen", "unknown", "eu_citizen"]
    )
    rtw_evidence = rtw_pool[idx % 5]
    return {
        "candidate_id": cid,
        "name": name,
        "current_title": role_title,
        "tenure_years_total": 1.5 + idx * 1.1,
        "education": [{"institution": "Synthetic University", "degree": "BSc CS", "year": 2018 - idx}],
        "work_history": [{"employer": f"Synth Corp {idx}", "title": role_title, "start": "2020-01", "end": "2024-06"}],
        "skills": skills_by_role[role_slug],
        "right_to_work": {"jurisdiction": jurisdiction, "evidence": rtw_evidence},
        "inconsistencies": [] if idx % 7 != 0 else [{"kind": "date_overlap", "detail": "two roles both list 2022 as end date"}],
        "level_target": level,
        "jurisdiction_target": jurisdiction,
    }


def _build_jd(role_slug: str, role_title: str, level: str) -> str:
    return (
        f"# {role_title} ({level})\n\n"
        f"## Summary\n\n"
        f"{role_title} role at WPP. Synthetic JD body — generated by data/synthetic/hiring/generate_hiring.py.\n\n"
        f"## Responsibilities\n\n"
        f"- Lead on day-to-day {role_title.lower()} responsibilities.\n"
        f"- Partner across teams to deliver agency outcomes.\n"
        f"- Mentor more junior team members where applicable.\n\n"
        f"## Skills required\n\n"
        f"- 3+ years in a comparable role.\n"
        f"- Demonstrated jurisdiction-relevant experience.\n\n"
        f"## Compensation\n\n"
        f"Band disclosed at offer — see [comp_band_lookup MCP tool].\n"
    )


def main() -> None:
    CVS.mkdir(parents=True, exist_ok=True)
    JDS.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, str, str, str]] = []
    for role_slug, role_title, level in ROLES:
        (JDS / f"{role_slug}.md").write_text(_build_jd(role_slug, role_title, level), encoding="utf-8")
        for jurisdiction in JURISDICTIONS:
            for idx in range(ROLE_INDEX_MAX):
                cv = _build_cv(role_slug, role_title, level, jurisdiction, idx)
                cid = cv["candidate_id"]
                (CVS / f"{cid}.json").write_text(json.dumps(cv, indent=2, ensure_ascii=False), encoding="utf-8")
                rows.append((cid, role_slug, jurisdiction, cv["right_to_work"]["evidence"]))
    LABELS.write_text(
        "candidate_id,role,jurisdiction,rtw_evidence\n" + "\n".join(",".join(r) for r in rows) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} CVs across {len(ROLES)} roles × {len(JURISDICTIONS)} jurisdictions")
    print(f"wrote {len(ROLES)} JDs")


if __name__ == "__main__":
    main()
