"""Travel vertical action package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.actions.commands import COMMAND_HANDLERS, reject

__all__ = ["COMMAND_HANDLERS", "reject"]
