"""Hand-authored source templates for the Travel vertical's `projections/`
package and its `detail.py` workflow-detail hook (Task 7).

This is the ONLY place these two pack-owned modules are hand-written.
`verticals/travel/projections/` and `verticals/travel/detail.py` are
generated output rendered from the string constants below by `render.py` --
never hand-edit those generated files directly. To change the Knowledge
projection or the workflow-detail hook, edit the relevant constant here and
regenerate via `uv run python -m verticals.travel.generator`.

Both modules consume the *real* terminal Task-6 evidence the
industry-neutral `WorldWorkflowAdapter.decided(..., evidence=...)`
parameter threads onto `workflow.payload["evidence"]` (the orchestrator's
own `_build_output()` dict from `durable_templates.py`), plus the
trigger-time `workflow.payload["observation"]` that
`WorldWorkflowAdapter.start()` already stores -- never a fabricated
fixture-only summary.

`knowledge.py`'s `project(workflow)` matches the shared, unmodified
`api.shared.projection_contracts.ProjectionFn` signature exactly
(`Callable[[Workflow], Sequence[EntityWrite | RelWrite | DecisionWrite]]`)
-- a pure function of `workflow.payload` only, no `app_state`/live world
reference. `detail.py`'s `workflow_detail(workflow, app_state)` is the
richer, two-argument hook `VerticalPack.workflow_detail_hook` carries, used
only by the generic `GET /api/workflows/{id}` route to attach a
`"packDetail"` key -- it MAY read live `app_state.world_service` state
(e.g. the Travel-owned `recovery_evaluations`/`objectives` records) because
detail assembly is not required to be a pure projection.
"""
from __future__ import annotations

PROJECTIONS_INIT_PY = '''"""Travel vertical Knowledge-graph projections package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.projections.knowledge import WORKFLOW_TYPE, project

__all__ = ["WORKFLOW_TYPE", "project"]
'''

PROJECTIONS_KNOWLEDGE_PY = '''"""Pack-owned Knowledge-graph projection for Travel's flight-disruption-
recovery hero (Task 7 Required A).

`project(workflow)` is a plain, deterministic function of
`workflow.payload` only -- exactly the shape
`api.shared.projection_contracts.ProjectionFn` requires
(`Callable[[Workflow], Sequence[EntityWrite | RelWrite | DecisionWrite]]`,
no `app_state`/live world reference). It consumes the real terminal Task-6
evidence the industry-neutral `WorldWorkflowAdapter.decided(...,
evidence=...)` parameter threads onto `workflow.payload["evidence"]` (the
orchestrator's own `_build_output()` dict, generated by
`durable_templates.py`) plus the trigger-time
`workflow.payload["observation"]` that `WorldWorkflowAdapter.start()`
already stores -- never a fabricated fixture-only summary.

Truthful absence: while the workflow is still `awaiting_hitl` (or has
otherwise not yet produced terminal orchestration evidence),
`workflow.payload["evidence"]` does not exist, so `project` returns `[]` --
no partial/fabricated subgraph. Once evidence exists, the trigger-level
subgraph (disruption, booking, party, travellers) is always projected; the
full decision/command/supplier/replacement chain is additionally projected
only once `evidence["command"]` is populated (i.e. a
`reaccommodate_travellers` command was actually authorised and applied) --
a declined/timed-out/no-alternative terminal outcome genuinely has no such
command, so nothing beyond the trigger-level facts is invented for it.

Registered on `WORKFLOW_TYPE`'s entry in the generated
`VerticalPack.projections` mapping (see `pack_templates.py`'s `MANIFEST_PY`
template) -- never on the shared global
`api.server.services.entity_projections.PROJECTIONS` dict, which is itself
only a compatibility snapshot seeded from `active_runtime().pack.projections`
at import time.

Node/relationship vocabulary emitted (all pre-existing, industry-neutral
`EntityGraph` schema; no destructive schema changes):

- ``Workflow`` --TRIGGERED_BY--> ``Asset`` (disruption)
- ``Workflow`` --AFFECTS_ASSET--> ``Asset`` (booking, party)
- ``Asset`` (party) --ASSIGNED_TO--> ``Person`` (each traveller)
- ``Asset`` (old/new flight, hotel, new transfer) --SUPPLIED_BY_ASSET-->
  ``Organisation`` (respective supplier)
- ``Asset`` (old flight) --RELATED_ASSET {role: replaced_by}--> ``Asset``
  (new flight)
- ``Asset`` (booking) --RELATED_ASSET {role: reaccommodated_on}-->
  ``Asset`` (new flight)
- ``Asset`` (booking) --RELATED_ASSET {role: retained_hotel}--> ``Asset``
  (hotel)
- ``Asset`` (booking) --RELATED_ASSET {role: assigned_transfer}-->
  ``Asset`` (new transfer)
- ``Asset`` (old transfer) --RELATED_ASSET {role: replaced_by}-->
  ``Asset`` (new transfer)
- ``Decision`` (decision_id) --DECIDED_ASSET--> ``Asset`` (option) --
  i.e. SELECTED_OPTION
- ``Decision`` (decision_id) --ISSUED_COMMAND--> ``Decision`` (command_id)
- ``Decision`` (command_id) --APPROVED_BY--> ``Decision`` (decision_id)
- ``Decision`` (command_id) --DECIDED_ASSET--> ``Asset`` (booking) -- i.e.
  MUTATED
- ``Decision`` (command_id) --EVALUATED_BY--> ``Decision`` (evaluation_id)
- ``Decision`` (evaluation_id) --RESOLVED_OBJECTIVE--> ``Workflow``

This module is generated by verticals.travel.generator.knowledge_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import json
from typing import Any

from api.server.services.entity_graph import DecisionWrite, EntityWrite, RelWrite
from api.shared.types import Workflow

WORKFLOW_TYPE = "flight-disruption-recovery"


def _json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, default=str)


def project(workflow: Workflow) -> list[EntityWrite | RelWrite | DecisionWrite]:
    payload = workflow.payload if isinstance(workflow.payload, dict) else {}
    evidence = payload.get("evidence")
    if not isinstance(evidence, dict):
        return []

    observation = payload.get("observation")
    observation = observation if isinstance(observation, dict) else {}
    workflow_id = workflow.id
    sw = (workflow_id,)

    booking_id = str(evidence.get("booking_id") or observation.get("booking_id") or "")
    party_id = str(evidence.get("party_id") or observation.get("party_id") or "")
    disruption_id = str(observation.get("disruption_id") or "")
    old_flight_id = str(observation.get("flight_id") or "")
    old_transfer_id = str(observation.get("old_transfer_id") or "")
    old_flight = observation.get("old_flight") or {}
    trigger_old_supplier_id = str(old_flight.get("supplier_id") or "")
    member_customer_ids = [str(c) for c in (observation.get("member_customer_ids") or [])]
    hotel_id = str(observation.get("hotel_id") or "")
    hotel_supplier_id = str(observation.get("hotel_supplier_id") or "")

    if not workflow_id or not booking_id:
        return []

    ops: list[EntityWrite | RelWrite | DecisionWrite] = []

    # -- trigger-level subgraph: real from the moment the workflow opened,
    # regardless of the eventual terminal outcome. ------------------------
    if disruption_id:
        ops.append(EntityWrite(
            kind="Asset", id=disruption_id,
            attrs={
                "kind": "disruption",
                "identifier": disruption_id,
                "attributes": _json({"trigger_flight_id": old_flight_id}),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(workflow_id, "TRIGGERED_BY", disruption_id))

    ops.append(EntityWrite(
        kind="Asset", id=booking_id,
        attrs={
            "kind": "booking",
            "identifier": booking_id,
            "attributes": _json({"party_id": party_id}),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(workflow_id, "AFFECTS_ASSET", booking_id, attrs={"role": "booking"}))

    if party_id:
        ops.append(EntityWrite(
            kind="Asset", id=party_id,
            attrs={
                "kind": "party",
                "identifier": party_id,
                "attributes": _json({
                    "booking_id": booking_id,
                    "member_customer_ids": member_customer_ids,
                }),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(workflow_id, "AFFECTS_ASSET", party_id, attrs={"role": "party"}))
        for cus_id in member_customer_ids:
            ops.append(EntityWrite(
                kind="Person", id=cus_id,
                attrs={
                    "role": "traveller",
                    "attributes": _json({"booking_id": booking_id, "party_id": party_id}),
                },
                source_workflows=sw,
            ))
            ops.append(RelWrite(party_id, "ASSIGNED_TO", cus_id))

    if old_flight_id:
        ops.append(EntityWrite(
            kind="Asset", id=old_flight_id,
            attrs={
                "kind": "flight",
                "identifier": old_flight_id,
                "status": "disrupted",
                "attributes": _json({"supplier_id": trigger_old_supplier_id}),
            },
            source_workflows=sw,
        ))

    if old_transfer_id:
        ops.append(EntityWrite(
            kind="Asset", id=old_transfer_id,
            attrs={
                "kind": "transfer",
                "identifier": old_transfer_id,
                "status": "replaced",
                "attributes": _json({"booking_id": booking_id}),
            },
            source_workflows=sw,
        ))

    if hotel_id:
        ops.append(EntityWrite(
            kind="Asset", id=hotel_id,
            attrs={
                "kind": "hotel",
                "identifier": hotel_id,
                "attributes": _json({"supplier_id": hotel_supplier_id}),
            },
            source_workflows=sw,
        ))
        if hotel_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=hotel_supplier_id,
                attrs={"name": hotel_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(hotel_id, "SUPPLIED_BY_ASSET", hotel_supplier_id))

    # -- decision/command/evaluation chain: only once a
    # reaccommodate_travellers command was actually authorised and applied.
    # A declined/timed-out/wrong_actor/no_alternative terminal outcome
    # never reaches TravelRecoveryBuildCommand, so `command` stays `None`
    # and there is genuinely nothing beyond the trigger-level facts above
    # to project -- returning early here is truthful, not a shortcut. ------
    command = evidence.get("command")
    if not isinstance(command, dict):
        return ops

    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    option_id = str(cmd_payload.get("option_id") or evidence.get("option_id") or "")
    new_flight_id = str(cmd_payload.get("new_flight_id") or "")
    new_transfer_id = str(cmd_payload.get("new_transfer_id") or "")
    old_supplier_id = str(cmd_payload.get("old_supplier_id") or "")
    new_supplier_id = str(cmd_payload.get("new_supplier_id") or "")
    cmd_hotel_supplier_id = str(cmd_payload.get("hotel_supplier_id") or hotel_supplier_id or "")
    new_transfer_supplier_id = str(cmd_payload.get("new_transfer_supplier_id") or "")
    decision_id = str(cmd_payload.get("decision_id") or "")
    command_id = str(command.get("command_id") or "")
    decision_outcome = str(cmd_payload.get("decision_outcome") or "")
    decided_by = str(cmd_payload.get("decided_by") or "")
    reasoning = str(evidence.get("reasoning") or "")

    if not option_id or not decision_id or not command_id:
        # Malformed/partial command evidence -- truthfully stop at the
        # trigger-level subgraph rather than emit decision/command nodes
        # keyed by an empty id.
        return ops

    evaluation_id = f"EVAL-{workflow_id}-{option_id}"

    ops.append(EntityWrite(
        kind="Asset", id=option_id,
        attrs={
            "kind": "recovery_option",
            "identifier": option_id,
            "attributes": _json({
                "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
                "arrival_delay_minutes": cmd_payload.get("arrival_delay_minutes"),
                "material_changes": cmd_payload.get("material_changes"),
                "requires_approval": cmd_payload.get("requires_approval"),
            }),
        },
        source_workflows=sw,
    ))

    if new_flight_id:
        ops.append(EntityWrite(
            kind="Asset", id=new_flight_id,
            attrs={
                "kind": "flight",
                "identifier": new_flight_id,
                "status": "reaccommodated",
                "attributes": _json({"supplier_id": new_supplier_id}),
            },
            source_workflows=sw,
        ))
        if old_flight_id:
            ops.append(RelWrite(old_flight_id, "RELATED_ASSET", new_flight_id, attrs={"role": "replaced_by"}))
        ops.append(RelWrite(booking_id, "RELATED_ASSET", new_flight_id, attrs={"role": "reaccommodated_on"}))
        if new_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=new_supplier_id,
                attrs={"name": new_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(new_flight_id, "SUPPLIED_BY_ASSET", new_supplier_id))

    if old_flight_id and old_supplier_id:
        ops.append(EntityWrite(
            kind="Organisation", id=old_supplier_id,
            attrs={"name": old_supplier_id, "kind": "supplier"},
            source_workflows=sw,
        ))
        ops.append(RelWrite(old_flight_id, "SUPPLIED_BY_ASSET", old_supplier_id))

    if hotel_id:
        ops.append(RelWrite(booking_id, "RELATED_ASSET", hotel_id, attrs={"role": "retained_hotel"}))
        if cmd_hotel_supplier_id and cmd_hotel_supplier_id != hotel_supplier_id:
            # Defensive: honour the command's own copy of the supplier id
            # if it ever differs from the trigger-time observation's copy
            # (should not happen -- both come from the same seed data).
            ops.append(EntityWrite(
                kind="Organisation", id=cmd_hotel_supplier_id,
                attrs={"name": cmd_hotel_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(hotel_id, "SUPPLIED_BY_ASSET", cmd_hotel_supplier_id))

    if new_transfer_id:
        ops.append(EntityWrite(
            kind="Asset", id=new_transfer_id,
            attrs={
                "kind": "transfer",
                "identifier": new_transfer_id,
                "attributes": _json({"supplier_id": new_transfer_supplier_id}),
            },
            source_workflows=sw,
        ))
        ops.append(RelWrite(booking_id, "RELATED_ASSET", new_transfer_id, attrs={"role": "assigned_transfer"}))
        if old_transfer_id:
            ops.append(RelWrite(
                old_transfer_id, "RELATED_ASSET", new_transfer_id,
                attrs={"role": "replaced_by"},
            ))
        if new_transfer_supplier_id:
            ops.append(EntityWrite(
                kind="Organisation", id=new_transfer_supplier_id,
                attrs={"name": new_transfer_supplier_id, "kind": "supplier"},
                source_workflows=sw,
            ))
            ops.append(RelWrite(new_transfer_id, "SUPPLIED_BY_ASSET", new_transfer_supplier_id))

    # -- decision / command / evaluation chain ---------------------------
    ops.append(EntityWrite(
        kind="Decision", id=decision_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "approve_material_change",
            "persona_role": decided_by,
            "verdict": decision_outcome,
            "reason": reasoning,
            "attributes": _json({
                "decision_id": decision_id,
                "option_id": option_id,
                "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
                "material_changes": cmd_payload.get("material_changes"),
                "requires_approval": cmd_payload.get("requires_approval"),
            }),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(decision_id, "DECIDED_ASSET", option_id))  # SELECTED_OPTION

    ops.append(EntityWrite(
        kind="Decision", id=command_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "reaccommodate",
            "persona_role": str(command.get("issued_by") or ""),
            "verdict": "issued",
            "reason": f"reaccommodate_travellers command for option {option_id}",
            "attributes": _json({
                "command_id": command_id,
                "command_type": command.get("type"),
                "option_id": option_id,
                "booking_id": booking_id,
                "party_id": party_id,
                "old_flight_id": old_flight_id,
                "new_flight_id": new_flight_id,
                "old_supplier_id": old_supplier_id,
                "new_supplier_id": new_supplier_id,
                "hotel_id": hotel_id,
                "hotel_supplier_id": cmd_hotel_supplier_id or hotel_supplier_id,
                "new_transfer_id": new_transfer_id,
                "new_transfer_supplier_id": new_transfer_supplier_id,
                "traveller_ids": member_customer_ids,
            }),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(decision_id, "ISSUED_COMMAND", command_id))
    ops.append(RelWrite(command_id, "APPROVED_BY", decision_id))
    ops.append(RelWrite(command_id, "DECIDED_ASSET", booking_id))  # MUTATED

    outcome = payload.get("outcome") if isinstance(payload.get("outcome"), dict) else None
    eval_attributes: dict[str, Any] = {
        "evaluation_id": evaluation_id,
        "command_id": command_id,
        "booking_id": booking_id,
        "party_id": party_id,
    }
    if outcome is not None:
        eval_attributes["outcome_status"] = outcome.get("status")
        eval_attributes["final_measurements"] = outcome.get("final_measurements")
    ops.append(EntityWrite(
        kind="Decision", id=evaluation_id,
        attrs={
            "workflow_id": workflow_id,
            "phase": "evaluate",
            "verdict": str(outcome.get("status")) if outcome is not None else "",
            "reason": "generic outcome evaluator" if outcome is not None else "",
            "attributes": _json(eval_attributes),
        },
        source_workflows=sw,
    ))
    ops.append(RelWrite(command_id, "EVALUATED_BY", evaluation_id))
    ops.append(RelWrite(evaluation_id, "RESOLVED_OBJECTIVE", workflow_id))

    return ops
'''

DETAIL_PY = '''"""Exact workflow-detail assembler for Travel's flight-disruption-recovery
hero (Task 7 Required B).

`workflow_detail(workflow, app_state)` is the two-argument hook
`VerticalPack.workflow_detail_hook` carries -- richer than the pure
`ProjectionFn` contract because assembling a human-inspectable detail
payload legitimately needs live world state the industry-neutral
`Workflow.payload` alone does not carry (the Travel-owned
`RecoveryEvaluation.status` and the generic `Objective.status`, both only
ever available off `app_state.world_service`). The generic
`GET /api/workflows/{id}` route (`api/server/routes/workflows.py`) calls
this hook -- when the active pack declares one -- and merges its return
value under a single `"packDetail"` response key; the route itself carries
zero Travel-specific branching.

Every field here is read from the real terminal Task-6 evidence
(`workflow.payload["evidence"]`, the orchestrator's own `_build_output()`
dict) or the trigger-time `workflow.payload["observation"]` -- never
fabricated. Trigger information (`observation`) and Durable/objective
identity are available from the moment the workflow opens, so
`workflow_detail` always returns a real dict once `observation` exists
(never `None` just because the workflow has not yet reached a terminal
state) -- but `command`/`evaluation`/`hitl` sub-fields stay truthfully
`None`/not-applicable until the evidence that would populate them actually
exists. No success-shaped defaults: missing evidence remains absent, never
invented.

This module is generated by verticals.travel.generator.knowledge_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from typing import Any, Mapping

from api.shared.types import Workflow

WORKFLOW_TYPE = "flight-disruption-recovery"

_EVALUATION_CRITERIA = (
    "booking now points at the new flight/transfer with recovery_status="
    "'reaccommodated', party.state='reaccommodated', and seat/room capacity "
    "on both the released and reserved flight/transfer legs stays within "
    "[0, capacity] on both sides of the move"
)


def _trigger(observation: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "disruption_id": observation.get("disruption_id"),
        "flight_id": observation.get("flight_id"),
        "booking_id": observation.get("booking_id"),
        "party_id": observation.get("party_id"),
        "member_customer_ids": list(observation.get("member_customer_ids") or []),
        "hotel_id": observation.get("hotel_id"),
        "hotel_supplier_id": observation.get("hotel_supplier_id"),
        "sensor_id": observation.get("sensor_id"),
        "old_transfer_id": observation.get("old_transfer_id"),
        "destination_id": observation.get("destination_id"),
        "evidence_event_ids": list(observation.get("evidence_event_ids") or []),
    }


def _phase_records(
    observation: Mapping[str, Any], evidence: Mapping[str, Any],
    evaluation: Mapping[str, Any] | None,
) -> list[dict[str, Any]]:
    command = evidence.get("command")
    decision = evidence.get("decision") or {}
    notify = evidence.get("notify")
    options = evidence.get("options") or []
    option_id = evidence.get("option_id")
    hitl_audit = evidence.get("hitl_audit") or {}

    has_alternatives = bool(options)
    approve_status = decision.get("outcome") or ("no_alternative" if option_id is None else "pending")
    if evaluation is not None:
        evaluate_status = evaluation.get("status")
    elif isinstance(command, dict):
        # A command was authorised/applied but the Travel-owned
        # `RecoveryEvaluation` record could not be found on the live world
        # service -- an anomalous state, reported truthfully rather than
        # papered over as "completed".
        evaluate_status = "unknown"
    else:
        # No command was ever authorised (declined / no-alternative /
        # timed-out terminal outcome) -- there is genuinely nothing to
        # evaluate.
        evaluate_status = "not_applicable"
    return [
        {
            "name": "detect",
            "status": "completed",
            "evidence": {
                "disruption_id": observation.get("disruption_id"),
                "flight_id": observation.get("flight_id"),
                "booking_id": observation.get("booking_id"),
                "party_id": observation.get("party_id"),
            },
        },
        {
            "name": "assess_impact",
            "status": "completed",
            "evidence": {
                "party_size": observation.get("party_size"),
                "member_customer_ids": list(observation.get("member_customer_ids") or []),
                "destination_id": observation.get("destination_id"),
            },
        },
        {
            "name": "search_alternatives",
            "status": "completed" if has_alternatives else "no_alternative",
            "evidence": {"option_count": len(options)},
        },
        {
            "name": "bound_options",
            "status": "completed" if has_alternatives else "no_alternative",
            "evidence": {"options": options},
        },
        {
            "name": "approve_material_change",
            "status": approve_status,
            "evidence": {"requires_approval": bool(hitl_audit.get("required")), "decision": decision},
        },
        {
            "name": "reaccommodate",
            "status": "completed" if isinstance(command, dict) else "not_applicable",
            "evidence": (command or {}).get("payload", {}) if isinstance(command, dict) else {},
        },
        {
            "name": "notify",
            "status": "completed" if notify else "not_applicable",
            "evidence": notify or {},
        },
        {
            "name": "evaluate",
            "status": evaluate_status,
            "evidence": {
                "evaluation_intent": evidence.get("evaluation_intent"),
                "evaluation": evaluation,
            },
        },
    ]


def _reasoning(evidence: Mapping[str, Any]) -> dict[str, Any]:
    options = evidence.get("options") or []
    option_id = evidence.get("option_id")
    booking_id = evidence.get("booking_id")
    party_id = evidence.get("party_id")
    decision = evidence.get("decision") or {}
    hitl_required = bool((evidence.get("hitl_audit") or {}).get("required"))
    decided_by = decision.get("decided_by")
    affected_analysis = (
        f"booking {booking_id} for party {party_id} affected by this disruption; "
        f"{len(options)} ranked alternative(s) evaluated"
    )
    if hitl_required:
        authority_rule = (
            f"material-change / above-bound options require {decided_by or 'head_of_operations'} "
            "approval via the TravelRecoveryApproval human-in-the-loop gate"
        )
    else:
        authority_rule = (
            f"auto-approved under {decided_by or 'operations_controller'} bounded authority "
            "(non-material, within the auto-approve cost bound)"
        )
    return {
        "affected_analysis": affected_analysis,
        "alternatives": options,
        "selected_option": option_id,
        "authority_rule": authority_rule,
    }


def _hitl(workflow_id: str, evidence: Mapping[str, Any]) -> dict[str, Any]:
    hitl_audit = evidence.get("hitl_audit") or {}
    required = bool(hitl_audit.get("required"))
    if not required:
        return {
            "required": False,
            "gate_id": None,
            "decision_id": None,
            "required_role": None,
            "decision_actor": None,
            "outcome": None,
        }
    decision = evidence.get("decision") or {}
    command = evidence.get("command")
    skills = evidence.get("skills") or []
    cmd_payload = command.get("payload") if isinstance(command, dict) else None
    cmd_payload = cmd_payload if isinstance(cmd_payload, dict) else {}
    return {
        "required": True,
        "gate_id": workflow_id,
        "decision_id": cmd_payload.get("decision_id"),
        "required_role": skills[-1] if skills else None,
        "decision_actor": decision.get("decided_by"),
        "outcome": decision.get("outcome"),
    }


def _command(
    evidence: Mapping[str, Any], observation: Mapping[str, Any],
) -> dict[str, Any] | None:
    command = evidence.get("command")
    if not isinstance(command, dict):
        return None
    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    decision = evidence.get("decision") or {}
    return {
        "type": command.get("type"),
        "command_id": command.get("command_id"),
        "option_id": cmd_payload.get("option_id"),
        "booking_id": cmd_payload.get("booking_id"),
        "party_id": cmd_payload.get("party_id"),
        "old_flight_id": cmd_payload.get("old_flight_id"),
        "new_flight_id": cmd_payload.get("new_flight_id"),
        "old_supplier_id": cmd_payload.get("old_supplier_id"),
        "new_supplier_id": cmd_payload.get("new_supplier_id"),
        "hotel_id": cmd_payload.get("hotel_id"),
        "hotel_supplier_id": cmd_payload.get("hotel_supplier_id"),
        "old_transfer_id": cmd_payload.get("old_transfer_id"),
        "new_transfer_id": cmd_payload.get("new_transfer_id"),
        "new_transfer_supplier_id": cmd_payload.get("new_transfer_supplier_id"),
        "incremental_cost_gbp": cmd_payload.get("incremental_cost_gbp"),
        # The exact traveller/customer ids from the trigger-time
        # observation -- not `RecoveryOption.affected_actor_ids`, which
        # deliberately mixes booking/flight/supplier ids alongside the
        # travellers themselves and would be a misleading source for a
        # field literally named "traveller ids".
        "traveller_ids": list(observation.get("member_customer_ids") or []),
        "decision_outcome": cmd_payload.get("decision_outcome") or decision.get("outcome"),
        "decided_by": cmd_payload.get("decided_by") or decision.get("decided_by"),
    }


def _evaluation(workflow_id: str, evidence: Mapping[str, Any], app_state: Any) -> dict[str, Any] | None:
    command = evidence.get("command")
    if not isinstance(command, dict):
        return None
    cmd_payload = command.get("payload") if isinstance(command.get("payload"), dict) else {}
    option_id = cmd_payload.get("option_id") or evidence.get("option_id")
    if not option_id:
        return None
    evaluation_id = f"EVAL-{workflow_id}-{option_id}"
    world_service = getattr(app_state, "world_service", None)
    scenario = getattr(world_service, "scenario", None)
    recovery_evaluations = getattr(scenario, "recovery_evaluations", None) or {}
    recovery_eval = recovery_evaluations.get(evaluation_id)
    if recovery_eval is None:
        return None
    return {
        "evaluation_id": evaluation_id,
        "command_id": getattr(recovery_eval, "command_id", command.get("command_id")),
        "booking_id": getattr(recovery_eval, "booking_id", None),
        "party_id": getattr(recovery_eval, "party_id", None),
        "status": getattr(recovery_eval, "status", None),
        "criteria": _EVALUATION_CRITERIA,
    }


def _objective(payload: Mapping[str, Any], app_state: Any) -> dict[str, Any] | None:
    objective_id = payload.get("objective_id")
    if not objective_id:
        return None
    world_service = getattr(app_state, "world_service", None)
    objectives = getattr(world_service, "objectives", None)
    objective = objectives.get(objective_id) if objectives is not None else None
    return {
        "objective_id": objective_id,
        "status": getattr(objective, "status", None) if objective is not None else None,
    }


def _durable(workflow: Workflow, payload: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "workflow_id": workflow.id,
        "orchestration_instance_id": workflow.orchestration_instance_id,
        "trace_id": payload.get("trace_id"),
    }


def workflow_detail(workflow: Workflow, app_state: Any) -> Mapping[str, Any] | None:
    if getattr(workflow, "type", None) != WORKFLOW_TYPE:
        return None
    payload = workflow.payload if isinstance(workflow.payload, dict) else {}
    observation = payload.get("observation")
    if not isinstance(observation, dict):
        return None

    evidence = payload.get("evidence")
    evidence = evidence if isinstance(evidence, dict) else None
    trigger = _trigger(observation)

    if evidence is None:
        return {
            "trigger": trigger,
            "phases": [],
            "skills": [],
            "tools": [],
            "reasoning": None,
            "hitl": None,
            "command": None,
            "evaluation": None,
            "objective": _objective(payload, app_state),
            "durable": _durable(workflow, payload),
        }

    workflow_id = workflow.id
    evaluation = _evaluation(workflow_id, evidence, app_state)
    return {
        "trigger": trigger,
        "phases": _phase_records(observation, evidence, evaluation),
        "skills": list(evidence.get("skills") or []),
        "tools": list(evidence.get("tools") or []),
        "reasoning": _reasoning(evidence),
        "hitl": _hitl(workflow_id, evidence),
        "command": _command(evidence, observation),
        "evaluation": evaluation,
        "objective": _objective(payload, app_state),
        "durable": _durable(workflow, payload),
    }
'''
