"""Hand-authored source templates for the Travel vertical's process surface.

Renders two generated files from `verticals.travel.generator.portfolio`'s
`PROCESS_SPECS`/`CASE_SPECS` (the single declarative source of truth for the
eight-process portfolio):

* `verticals/travel/worlds/processes.py` -- eight real `detect_*` sensor
  functions, eight real `evaluate_*` outcome functions, the `DETECTORS`/
  `EVALUATORS` lookup dicts, and `REFERENCE_CASES`: one real, executable
  scenario per process (a `setup`/`detect`/`build_command` triple) that
  `TravelWorld.run_reference_process` drives end to end as a pure Python
  call.
* `verticals/travel/worlds/registration.py` -- the `WorldPackRegistration`
  (`TRAVEL_WORLD`) wiring each process's real `ObjectiveRoute` and
  `ResponderRegistration`, plus `build_travel_demo` for the pack's demo
  world scale.

Both rendered files are fully self-contained: neither imports anything from
`verticals.travel.generator` at runtime (only this generator module reads
`portfolio` -- the generated files embed the portfolio's values as literal
Python source, so the shipped pack never depends on its own generator
package at runtime).

This module is generated by verticals.travel.generator.process_templates.
Do not hand-edit the rendered files -- change this module (or
`portfolio.py`) and regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.generator.portfolio import CASE_BY_WORKFLOW_TYPE, PROCESS_SPECS

_PROCESSES_PREAMBLE = '''"""Detector, evaluator and reference-case functions for the Travel portfolio.

Every `detect_*` function below is a real, deterministic sensor: it scans
live `TravelWorld` state for a genuine trigger condition and, for each match,
journals a real `"sensor.<condition>_tripped"` event (never a synthetic or
random one) via `world.runtime.emit`. Every `evaluate_*` function is a real,
standalone diagnostic outcome check against live world state -- distinct
from (and not wired into) the generic `api.server.world.evaluations`
pipeline that `TravelWorld.run_reference_process` drives; these are for
direct diagnostic use and for tooling that wants a plain pass/fail read of
one process's real-world condition without opening an objective.

`REFERENCE_CASES` maps each of the eight workflow types to one real,
executable scenario: a `setup(world)` that arranges genuine world state (by
running the deterministic simulation forward and, where relevant, reporting
a real disruption), a `detect(world)` that calls that process's own
detector and picks out its one real triggering sensor event, and a
`build_command(world, objective)` that returns a real, authority-valid
`SimulationCommand` naming real seeded (or disruption-derived) Travel actor
ids. `TravelWorld.run_reference_process` drives all three through the
generic sensor -> objective -> command -> evaluation pipeline as a pure
Python call -- no world-process HTTP run route is exercised anywhere in
this module.

This module is generated by verticals.travel.generator.process_templates.
Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from api.server.world.model import SimulationCommand, SimulationEvent


def _detect_disruption_kind(world: Any, *, kind: str, event_type: str) -> list[SimulationEvent]:
    """Journal one real sensor event per reported-but-unresolved `kind` disruption.

    Shared by five of the six disruption-driven detectors below -- every one
    except `detect_flight_cancellation_impact`, which needs its own
    eligibility-gated, rising-edge logic (see below): a disruption only
    ever trips its sensor while genuinely `"reported"`, so a disruption an
    earlier command already resolved never re-trips it.
    """
    events: list[SimulationEvent] = []
    for disruption in sorted(world.disruptions.values(), key=lambda d: d.id):
        if disruption.kind != kind or disruption.status != "reported":
            continue
        events.append(
            world.runtime.emit(
                event_type,
                target_id=disruption.resource_id,
                payload={"disruption_id": disruption.id, "measurements": {"kind": kind}},
            )
        )
    return events


def detect_quote_ready(world: Any) -> list[SimulationEvent]:
    """Real sensor: every currently-offered quote is ready to be confirmed."""
    events: list[SimulationEvent] = []
    for quote in sorted(world.quotes.values(), key=lambda quote: quote.id):
        if quote.status != "offered":
            continue
        events.append(
            world.runtime.emit(
                "sensor.quote_ready_tripped",
                target_id=quote.id,
                payload={"quote_id": quote.id, "measurements": {"price": quote.price}},
            )
        )
    return events


def detect_capacity_pressure(world: Any, threshold: float = 0.02) -> list[SimulationEvent]:
    """Real sensor: an allotment's reserved/contracted ratio at or above `threshold`."""
    events: list[SimulationEvent] = []
    for allotment in sorted(world.allotments.values(), key=lambda allotment: allotment.id):
        if allotment.allotment <= 0:
            continue
        ratio = allotment.reserved / allotment.allotment
        if ratio < threshold:
            continue
        events.append(
            world.runtime.emit(
                "sensor.capacity_pressure_tripped",
                target_id=allotment.id,
                payload={"allotment_id": allotment.id, "measurements": {"ratio": ratio}},
            )
        )
    return events


_SENSOR_FLIGHT_CANCELLATION_IMPACT = "sensor:flight_cancellation_impact"
_ELIGIBLE_BOOKING_STATUSES = frozenset({"confirmed", "deposit_paid", "paid"})


def detect_flight_cancellation_impact(world: Any) -> list[SimulationEvent]:
    """Real, state-derived sensor for a reported flight-cancellation disruption
    whose flight still has at least one affected paid/confirmed booking and
    traveller party.

    Bespoke rather than delegated to `_detect_disruption_kind` (unlike the
    other six disruption-driven detectors): a cancellation against a flight
    with no eligible demand never trips this sensor at all -- the condition
    is read from real world state, never faked. Once a disruption has
    tripped this sensor, this function never re-emits `"sensor.tripped"`
    for it again: calling it again (or advancing the simulation further)
    while the same condition remains true is always a safe, idempotent
    no-op, since the rising edge is re-derived from the journal itself on
    every call rather than from any separate latch.
    """
    already_tripped = {
        event.payload.get("disruption_id")
        for event in world.runtime.journal
        if event.type == "sensor.tripped" and event.payload.get("sensor_id") == _SENSOR_FLIGHT_CANCELLATION_IMPACT
    }
    events_by_id = {event.event_id: event for event in world.runtime.journal}

    events: list[SimulationEvent] = []
    for disruption in sorted(world.disruptions.values(), key=lambda d: d.id):
        if disruption.kind != "flight_cancellation" or disruption.status != "reported":
            continue
        if disruption.id in already_tripped:
            continue

        flight_id = disruption.resource_id
        affected_bookings = sorted(
            (
                booking
                for booking in world.bookings.values()
                if booking.flight_id == flight_id and booking.status in _ELIGIBLE_BOOKING_STATUSES
            ),
            key=lambda booking: booking.id,
        )
        if not affected_bookings:
            continue

        party_ids = sorted({booking.party_id for booking in affected_bookings})
        parties = [world.parties[party_id] for party_id in party_ids]
        member_customer_ids = sorted(
            {customer_id for party in parties for customer_id in party.member_customer_ids}
        )
        hotel_ids = sorted({booking.hotel_id for booking in affected_bookings})
        transfer_ids = sorted({booking.transfer_id for booking in affected_bookings})
        flight = world.flights[flight_id]
        supplier_ids = sorted(
            {flight.supplier_id}
            | {world.hotels[hotel_id].supplier_id for hotel_id in hotel_ids}
            | {world.transfers[transfer_id].supplier_id for transfer_id in transfer_ids}
        )
        traveller_count = sum(party.size for party in parties)
        actor_ids = sorted(
            {flight_id, disruption.id, *(b.id for b in affected_bookings), *party_ids}
            | set(member_customer_ids)
            | set(hotel_ids)
            | set(transfer_ids)
            | set(supplier_ids)
        )

        cause_event = events_by_id[disruption.last_event_id]
        events.append(
            world.runtime.emit(
                "sensor.tripped",
                actor_id=disruption.id,
                target_id=flight_id,
                cause_event_id=cause_event.event_id,
                trace_id=cause_event.trace_id,
                payload={
                    "sensor_id": _SENSOR_FLIGHT_CANCELLATION_IMPACT,
                    "disruption_id": disruption.id,
                    "flight_id": flight_id,
                    "booking_ids": [booking.id for booking in affected_bookings],
                    "party_ids": party_ids,
                    "member_customer_ids": member_customer_ids,
                    "hotel_ids": hotel_ids,
                    "transfer_ids": transfer_ids,
                    "supplier_ids": supplier_ids,
                    "actor_ids": actor_ids,
                    "measurements": {
                        "affected_booking_count": len(affected_bookings),
                        "affected_party_count": len(party_ids),
                        "affected_traveller_count": traveller_count,
                        "seats_impacted": traveller_count,
                        "material_change": True,
                    },
                },
            )
        )
    return events


def detect_hotel_allotment_shortfall(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved hotel allotment shortfall disruption."""
    return _detect_disruption_kind(
        world, kind="hotel_allotment_shortfall", event_type="sensor.hotel_allotment_shortfall_tripped",
    )


def detect_customer_cancellation_accepted(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved accepted customer cancellation."""
    return _detect_disruption_kind(
        world,
        kind="customer_cancellation_accepted",
        event_type="sensor.customer_cancellation_accepted_tripped",
    )


def detect_balance_payment_exception(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved balance payment exception disruption."""
    return _detect_disruption_kind(
        world, kind="balance_payment_exception", event_type="sensor.balance_payment_exception_tripped",
    )


def detect_transfer_arrival_risk(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved transfer arrival risk disruption."""
    return _detect_disruption_kind(
        world, kind="transfer_arrival_risk", event_type="sensor.transfer_arrival_risk_tripped",
    )


def detect_material_itinerary_change(world: Any) -> list[SimulationEvent]:
    """Real sensor: a reported, unresolved material itinerary change disruption."""
    return _detect_disruption_kind(
        world, kind="material_itinerary_change", event_type="sensor.material_itinerary_change_tripped",
    )


DETECTORS: dict[str, Callable[..., list[SimulationEvent]]] = {
    "holiday-sales-booking": detect_quote_ready,
    "capacity-yield-management": detect_capacity_pressure,
    "flight-disruption-recovery": detect_flight_cancellation_impact,
    "hotel-supplier-recovery": detect_hotel_allotment_shortfall,
    "cancellation-refund": detect_customer_cancellation_accepted,
    "payment-exception": detect_balance_payment_exception,
    "destination-operations": detect_transfer_arrival_risk,
    "proactive-customer-care": detect_material_itinerary_change,
}


def evaluate_booking_confirmed_and_paid(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` names a real booking whose status is `"paid"`."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking"}
    if booking.status != "paid":
        return {"status": "fail", "booking_id": booking_id, "reason": f"booking is {booking.status!r}"}
    return {"status": "pass", "booking_id": booking_id, "total_price": booking.total_price}


def evaluate_capacity_within_bounds(world: Any, *, allotment_id: str) -> dict[str, Any]:
    """Pass iff `allotment_id`'s conservation invariant holds and it is not over-pressured."""
    allotment = world.allotments.get(allotment_id)
    if allotment is None:
        return {"status": "fail", "allotment_id": allotment_id, "reason": "unknown allotment"}
    conserved = 0 <= allotment.occupied <= allotment.reserved <= allotment.allotment <= allotment.total
    if not conserved:
        return {"status": "fail", "allotment_id": allotment_id, "reason": "conservation invariant broken"}
    ratio = (allotment.reserved / allotment.allotment) if allotment.allotment else 0.0
    return {"status": "pass", "allotment_id": allotment_id, "ratio": ratio}


def evaluate_travellers_reaccommodated(world: Any, *, booking_id: str, disruption_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` exists and its linked disruption is `"resolved"`."""
    booking = world.bookings.get(booking_id)
    disruption = world.disruptions.get(disruption_id)
    if booking is None or disruption is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking or disruption"}
    if disruption.status != "resolved":
        return {"status": "fail", "booking_id": booking_id, "reason": "disruption not yet resolved"}
    return {"status": "pass", "booking_id": booking_id, "flight_id": booking.flight_id}


def evaluate_accommodation_restored(world: Any, *, disruption_id: str) -> dict[str, Any]:
    """Pass iff the named hotel-shortfall disruption is `"resolved"`."""
    disruption = world.disruptions.get(disruption_id)
    if disruption is None:
        return {"status": "fail", "disruption_id": disruption_id, "reason": "unknown disruption"}
    if disruption.status != "resolved":
        return {"status": "fail", "disruption_id": disruption_id, "reason": "not yet resolved"}
    return {"status": "pass", "disruption_id": disruption_id}


def evaluate_refund_settled(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` is cancelled and carries exactly one issued refund."""
    booking = world.bookings.get(booking_id)
    if booking is None or booking.status != "cancelled":
        return {"status": "fail", "booking_id": booking_id, "reason": "booking not cancelled"}
    refunds = [refund for refund in world.refunds.values() if refund.booking_id == booking_id]
    if not refunds or refunds[0].status != "issued":
        return {"status": "fail", "booking_id": booking_id, "reason": "no issued refund"}
    return {"status": "pass", "booking_id": booking_id, "refund_amount": refunds[0].amount}


def evaluate_payment_or_inventory_resolved(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` ended either `"paid"` (retry) or `"cancelled"` (release)."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"status": "fail", "booking_id": booking_id, "reason": "unknown booking"}
    if booking.status not in ("paid", "cancelled"):
        return {"status": "fail", "booking_id": booking_id, "reason": f"booking is {booking.status!r}"}
    return {"status": "pass", "booking_id": booking_id, "resolution": booking.status}


def evaluate_transfer_sla_restored(world: Any, *, transfer_id: str) -> dict[str, Any]:
    """Pass iff `transfer_id` was superseded by a real dispatched replacement."""
    transfer = world.transfers.get(transfer_id)
    replacement = world.transfers.get(f"TRF-REPL-{transfer_id}")
    if transfer is None or replacement is None:
        return {"status": "fail", "transfer_id": transfer_id, "reason": "no dispatched replacement"}
    if transfer.status != "superseded":
        return {"status": "fail", "transfer_id": transfer_id, "reason": "original transfer not superseded"}
    return {"status": "pass", "transfer_id": transfer_id, "replacement_id": replacement.id}


def evaluate_customer_notified_and_supported(world: Any, *, booking_id: str) -> dict[str, Any]:
    """Pass iff `booking_id` carries at least one issued customer care action."""
    actions = [action for action in world.care_actions.values() if action.booking_id == booking_id]
    if not actions or any(action.status != "issued" for action in actions):
        return {"status": "fail", "booking_id": booking_id, "reason": "no issued care action"}
    return {"status": "pass", "booking_id": booking_id, "care_action_ids": [a.id for a in actions]}


EVALUATORS: dict[str, Callable[..., dict[str, Any]]] = {
    "holiday-sales-booking": evaluate_booking_confirmed_and_paid,
    "capacity-yield-management": evaluate_capacity_within_bounds,
    "flight-disruption-recovery": evaluate_travellers_reaccommodated,
    "hotel-supplier-recovery": evaluate_accommodation_restored,
    "cancellation-refund": evaluate_refund_settled,
    "payment-exception": evaluate_payment_or_inventory_resolved,
    "destination-operations": evaluate_transfer_sla_restored,
    "proactive-customer-care": evaluate_customer_notified_and_supported,
}


def _run_setup(world: Any, *, run_until_minutes: float, disruption: tuple[str, str] | None) -> None:
    world.run(run_until_minutes)
    if disruption is not None:
        kind, resource_id = disruption
        world.report_disruption(kind=kind, resource_id=resource_id)


def _run_detect(world: Any, *, workflow_type: str, target_id: str) -> SimulationEvent:
    events = DETECTORS[workflow_type](world)
    return next(event for event in events if event.target_id == target_id)


@dataclass(frozen=True)
class ReferenceCase:
    """One real, executable reference scenario for one portfolio process."""

    workflow_type: str
    role: str
    run_until_minutes: float
    disruption: tuple[str, str] | None
    detect_target_id: str
    command_id: str
    command_type: str
    command_payload: dict[str, Any]

    def setup(self, world: Any) -> None:
        _run_setup(world, run_until_minutes=self.run_until_minutes, disruption=self.disruption)

    def detect(self, world: Any) -> SimulationEvent:
        return _run_detect(world, workflow_type=self.workflow_type, target_id=self.detect_target_id)

    def build_command(self, world: Any, objective: Any) -> SimulationCommand:
        return SimulationCommand(
            command_id=self.command_id,
            trace_id=objective.trace_id,
            issued_by=objective.claimed_by,
            type=self.command_type,
            payload=dict(self.command_payload),
        )

'''

_REGISTRATION_PREAMBLE = '''"""World-pack registration for the Travel eight-process portfolio.

Wires every process's real `ObjectiveRoute` (sensor -> objective ->
allowed command -> success/failure event types -> evaluation timeout) and
`ResponderRegistration` (objective type -> orchestrator name -> workflow
type -> prefix -> owning function -> timeout) into one
`api.shared.world_contracts.WorldPackRegistration` scale profile, keyed by
objective_type exactly as `api.server.world.objectives.ObjectiveManager`
and `api.server.world.commands.CommandGateway` expect.

This module is generated by verticals.travel.generator.process_templates.
Do not hand-edit -- change the generator template (or
verticals.travel.generator.portfolio) and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from api.shared.world_contracts import (
    ObjectiveRoute,
    ResponderRegistration,
    WorldPackRegistration,
    WorldScaleProfile,
)
from verticals.travel.worlds.diagnostics import build_diagnostic_input
from verticals.travel.worlds.scenario import TravelWorld

'''


def render_worlds_processes_py() -> str:
    """Render `worlds/processes.py`: detectors, evaluators and REFERENCE_CASES."""
    lines = [_PROCESSES_PREAMBLE.rstrip("\n"), "", "REFERENCE_CASES: dict[str, ReferenceCase] = {"]
    for index, spec in enumerate(PROCESS_SPECS, start=1):
        case = CASE_BY_WORKFLOW_TYPE[spec.workflow_type]
        command_id = f"ref-{spec.workflow_id_prefix}-{index:02d}"
        lines.append(f"    {spec.workflow_type!r}: ReferenceCase(")
        lines.append(f"        workflow_type={spec.workflow_type!r},")
        lines.append(f"        role={spec.authority_role!r},")
        lines.append(f"        run_until_minutes={case.run_until_minutes!r},")
        lines.append(f"        disruption={case.disruption!r},")
        lines.append(f"        detect_target_id={case.detect_target_id!r},")
        lines.append(f"        command_id={command_id!r},")
        lines.append(f"        command_type={spec.command_type!r},")
        lines.append(f"        command_payload={case.command_payload!r},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_worlds_registration_py() -> str:
    """Render `worlds/registration.py`: TRAVEL_WORLD and its lookup helpers."""
    lines = [_REGISTRATION_PREAMBLE.rstrip("\n"), "", "_ROUTES: tuple[ObjectiveRoute, ...] = ("]
    for spec in PROCESS_SPECS:
        lines.append("    ObjectiveRoute(")
        lines.append(f"        sensor_id={spec.sensor_id!r},")
        lines.append(f"        objective_type={spec.objective_type!r},")
        lines.append(f"        allowed_command_types=frozenset({{{spec.command_type!r}}}),")
        # Render from the tuple directly (sorted for determinism), never a
        # set/frozenset repr -- str hash randomization makes plain set
        # iteration order vary across interpreter processes.
        success_types = tuple(sorted(spec.success_event_types))
        failure_types = tuple(sorted(spec.failure_event_types))
        lines.append(f"        success_event_types=frozenset({success_types!r}),")
        lines.append(f"        failure_event_types=frozenset({failure_types!r}),")
        lines.append(f"        evaluation_timeout_minutes={spec.evaluation_timeout_minutes!r},")
        lines.append("    ),")
    lines.append(")")
    lines.append("")
    lines.append("_RESPONDERS: dict[str, ResponderRegistration] = {")
    for spec in PROCESS_SPECS:
        lines.append(f"    {spec.objective_type!r}: ResponderRegistration(")
        lines.append(f"        objective_type={spec.objective_type!r},")
        # Task 6: the flight-disruption-recovery hero's responder points at
        # the real Azure Durable Functions orchestrator name once bound;
        # every other process keeps pointing at its pure-simulator name.
        _rendered_orchestrator = spec.real_orchestrator_name or spec.orchestrator_name
        lines.append(f"        orchestrator={_rendered_orchestrator!r},")
        lines.append(f"        workflow_type={spec.workflow_type!r},")
        lines.append(f"        prefix={spec.workflow_id_prefix!r},")
        lines.append(f"        owner_function={spec.function!r},")
        lines.append(f"        timeout_seconds={spec.timeout_seconds!r},")
        lines.append(
            f"        lifecycle_start_via_bridge={spec.lifecycle_start_via_bridge!r},"
        )
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append('def _build_demo_scenario(runtime: object) -> TravelWorld:')
    lines.append('    """Build the demo-scale TravelWorld, sharing the pack runtime."""')
    lines.append("    return TravelWorld(seed=42, runtime=runtime)")
    lines.append("")
    lines.append("")
    lines.append("_SCALES: dict[str, WorldScaleProfile] = {")
    lines.append('    "demo": WorldScaleProfile(')
    lines.append('        name="demo",')
    lines.append("        build_scenario=_build_demo_scenario,")
    lines.append("        default_minutes_per_second=2.0,")
    lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("TRAVEL_WORLD = WorldPackRegistration(")
    lines.append('    name="travel",')
    lines.append("    scales=_SCALES,")
    lines.append('    default_scale="demo",')
    lines.append("    objective_routes=_ROUTES,")
    lines.append("    responders=_RESPONDERS,")
    lines.append("    build_diagnostic_input=build_diagnostic_input,")
    lines.append(")")
    lines.append("")
    lines.append('TRAVEL_WORLDS: dict[str, WorldPackRegistration] = {"travel": TRAVEL_WORLD}')
    lines.append("")
    lines.append("_ROUTE_BY_WORKFLOW_TYPE: dict[str, ObjectiveRoute] = {")
    for index, spec in enumerate(PROCESS_SPECS):
        lines.append(f"    {spec.workflow_type!r}: _ROUTES[{index}],")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def route_for_workflow_type(workflow_type: str) -> ObjectiveRoute:")
    lines.append('    """The real ObjectiveRoute registered for `workflow_type`."""')
    lines.append("    return _ROUTE_BY_WORKFLOW_TYPE[workflow_type]")
    lines.append("")
    lines.append("")
    lines.append("def responder_for_workflow_type(workflow_type: str) -> ResponderRegistration:")
    lines.append('    """The real ResponderRegistration registered for `workflow_type`."""')
    lines.append("    for responder in _RESPONDERS.values():")
    lines.append("        if responder.workflow_type == workflow_type:")
    lines.append("            return responder")
    lines.append('    raise KeyError(f"no responder registered for workflow type {workflow_type!r}")')
    lines.append("")
    return "\n".join(lines)
