"""Hand-authored source templates for the Travel vertical's `recovery/` package.

This is the ONLY place the flight-disruption-recovery hero's pack-owned
planner is hand-written. `verticals/travel/recovery/` is generated output
rendered from the string constants below by `render.py` -- never hand-edit
those generated files directly. To change the planner's behaviour, edit the
relevant constant here and regenerate via
`uv run python -m verticals.travel.generator`.

`plan_recovery_options` is deliberately pure (reads only its own
`observation` argument, never a live world reference, I/O, randomness or
the wall clock) so it is safe to call directly from a real Azure Durable
Functions activity (`TravelRecoveryPlanOptions` in
`verticals.travel.durable.functions`), which must itself stay deterministic
and replay-safe.
"""
from __future__ import annotations

RECOVERY_INIT_PY = '''"""Travel vertical flight-disruption-recovery package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from verticals.travel.recovery.planner import (
    AUTO_APPROVE_BOUND_GBP,
    RecoveryOption,
    plan_recovery_options,
)

__all__ = ["AUTO_APPROVE_BOUND_GBP", "RecoveryOption", "plan_recovery_options"]
'''

RECOVERY_PLANNER_PY = '''"""Pure flight-disruption-recovery option planner for the Travel vertical.

`plan_recovery_options` is a plain, deterministic function: given one
`verticals.travel.worlds.scenario.TravelWorld.build_observation(...)`-shaped
dict, it returns at most three `RecoveryOption`s, sorted by ascending
material-change severity, then incremental GBP cost, then arrival delay,
then option id. It reads nothing except its own `observation` argument --
no world reference, no I/O, no randomness, no wall-clock read -- so it is
safe to call directly from a real Azure Durable Functions activity
(`TravelRecoveryPlanOptions` in `verticals.travel.durable.functions`),
which must itself stay deterministic and replay-safe.

This module is generated by verticals.travel.generator.recovery_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

# A recovery option requires head_of_operations approval once its
# incremental GBP cost exceeds this bound (operations_controller's own
# authority spend limit -- see verticals.travel.authority.TRAVEL_AUTHORITY)
# or once it materially changes the holiday, whichever fires first.
AUTO_APPROVE_BOUND_GBP = 750.0

# A replacement flight's arrival delay beyond this many minutes (compared
# to the disrupted flight's own scheduled arrival) counts as a material
# change to the holiday, on top of any destination change.
_MATERIAL_DELAY_THRESHOLD_MINUTES = 60.0

# Never present more than this many ranked options to a decision-maker.
_MAX_OPTIONS = 3


@dataclass(frozen=True)
class RecoveryOption:
    """One bounded, evidence-carrying replacement itinerary for a disrupted booking."""

    option_id: str
    disruption_id: str
    booking_id: str
    party_id: str
    old_flight_id: str
    new_flight_id: str
    old_supplier_id: str
    new_supplier_id: str
    old_transfer_id: str
    new_transfer_id: str
    new_transfer_supplier_id: str
    hotel_id: str
    hotel_supplier_id: str
    allotment_id: str
    destination_id: str
    incremental_cost_gbp: float
    arrival_delay_minutes: float
    material_changes: tuple[str, ...]
    requires_approval: bool
    affected_actor_ids: tuple[str, ...]
    capacity_evidence: dict[str, Any]
    evidence_event_ids: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "option_id": self.option_id,
            "disruption_id": self.disruption_id,
            "booking_id": self.booking_id,
            "party_id": self.party_id,
            "old_flight_id": self.old_flight_id,
            "new_flight_id": self.new_flight_id,
            "old_supplier_id": self.old_supplier_id,
            "new_supplier_id": self.new_supplier_id,
            "old_transfer_id": self.old_transfer_id,
            "new_transfer_id": self.new_transfer_id,
            "new_transfer_supplier_id": self.new_transfer_supplier_id,
            "hotel_id": self.hotel_id,
            "hotel_supplier_id": self.hotel_supplier_id,
            "allotment_id": self.allotment_id,
            "destination_id": self.destination_id,
            "incremental_cost_gbp": self.incremental_cost_gbp,
            "arrival_delay_minutes": self.arrival_delay_minutes,
            "material_changes": list(self.material_changes),
            "requires_approval": self.requires_approval,
            "affected_actor_ids": list(self.affected_actor_ids),
            "capacity_evidence": dict(self.capacity_evidence),
            "evidence_event_ids": list(self.evidence_event_ids),
        }


def plan_recovery_options(observation: dict[str, Any]) -> list[RecoveryOption]:
    """Rank and bound replacement itineraries for one disrupted booking.

    Reads only `observation`: every candidate flight/transfer's capacity,
    fare and schedule already comes pre-packaged from the live snapshot
    (see `TravelWorld.build_observation`), so this function never reaches
    back into any mutable world state and is safe to replay.

    Filters candidate flights to those with spare capacity for the whole
    party on both the replacement flight and its paired transfer, computes
    each survivor's incremental GBP cost and arrival delay against the
    disrupted flight's own schedule, flags a material change whenever the
    arrival delay exceeds the material-delay threshold or the destination
    itself would change, and marks `requires_approval` whenever the
    incremental cost exceeds `AUTO_APPROVE_BOUND_GBP` or there is any
    material change at all. Returns at most `_MAX_OPTIONS` options, sorted
    by ascending (material-change count, incremental cost, arrival delay,
    option id) so the same observation always ranks identically.

    Every option also carries the old (disrupted) and new (replacement)
    flight's own real `supplier_id`, the retained hotel's own
    `supplier_id`, and the specific chosen replacement transfer's own
    `supplier_id` -- all straight from the observation, never invented or
    derived -- so any downstream approval, command or audit record can be
    independently checked against the actual operating supplier of every
    asset involved, not just its id.
    """
    disruption_id = observation["disruption_id"]
    booking_id = observation["booking_id"]
    party_id = observation["party_id"]
    party_size = observation["party_size"]
    member_customer_ids = observation["member_customer_ids"]
    old_flight_id = observation["flight_id"]
    old_flight = observation["old_flight"]
    old_supplier_id = old_flight["supplier_id"]
    old_transfer_id = observation["old_transfer_id"]
    hotel_id = observation["hotel_id"]
    hotel_supplier_id = observation["hotel_supplier_id"]
    allotment_id = observation["allotment_id"]
    destination_id = observation["destination_id"]
    evidence_event_ids = tuple(observation["evidence_event_ids"])

    transfers_by_flight = {
        transfer["flight_id"]: transfer for transfer in observation["candidate_transfers"]
    }

    options: list[RecoveryOption] = []
    for candidate in observation["candidate_flights"]:
        transfer = transfers_by_flight.get(candidate["flight_id"])
        if transfer is None:
            continue
        if candidate["capacity"] - candidate["reserved"] < party_size:
            continue
        if transfer["capacity"] - transfer["reserved"] < party_size:
            continue

        arrival_delay_minutes = candidate["scheduled_arrival"] - old_flight["scheduled_arrival"]
        material_changes: list[str] = []
        if arrival_delay_minutes > _MATERIAL_DELAY_THRESHOLD_MINUTES:
            material_changes.append("arrival_delay")
        if candidate["destination_id"] != destination_id:
            material_changes.append("destination")

        incremental_cost_gbp = float(candidate["base_fare_gbp"])
        requires_approval = incremental_cost_gbp > AUTO_APPROVE_BOUND_GBP or bool(material_changes)
        new_supplier_id = candidate["supplier_id"]

        option_id = f"OPT-{disruption_id}-{candidate['flight_id']}"
        options.append(
            RecoveryOption(
                option_id=option_id,
                disruption_id=disruption_id,
                booking_id=booking_id,
                party_id=party_id,
                old_flight_id=old_flight_id,
                new_flight_id=candidate["flight_id"],
                old_supplier_id=old_supplier_id,
                new_supplier_id=new_supplier_id,
                old_transfer_id=old_transfer_id,
                new_transfer_id=transfer["transfer_id"],
                new_transfer_supplier_id=transfer["supplier_id"],
                hotel_id=hotel_id,
                hotel_supplier_id=hotel_supplier_id,
                allotment_id=allotment_id,
                destination_id=destination_id,
                incremental_cost_gbp=incremental_cost_gbp,
                arrival_delay_minutes=arrival_delay_minutes,
                material_changes=tuple(material_changes),
                requires_approval=requires_approval,
                affected_actor_ids=tuple(
                    [
                        booking_id,
                        party_id,
                        *member_customer_ids,
                        old_flight_id,
                        candidate["flight_id"],
                        old_supplier_id,
                        new_supplier_id,
                    ]
                ),
                capacity_evidence={
                    "new_flight_capacity": candidate["capacity"],
                    "new_flight_reserved": candidate["reserved"],
                    "new_transfer_capacity": transfer["capacity"],
                    "new_transfer_reserved": transfer["reserved"],
                },
                evidence_event_ids=evidence_event_ids,
            )
        )

    options.sort(
        key=lambda option: (
            len(option.material_changes),
            option.incremental_cost_gbp,
            option.arrival_delay_minutes,
            option.option_id,
        )
    )
    return options[:_MAX_OPTIONS]
'''
