"""Hand-authored source template for the Travel pack's world scene.

Renders `ui/world-scene.json`, the pack-owned spatial scene registered on
`VerticalUiManifest.world_scene` (loaded through the shared, industry-
neutral `api.shared.world_scene_contracts.load_world_scene` contract).
The scene names the real seeded origin airports/destinations/hotels,
binds every real snapshot collection a generic spatial world renderer
needs, and maps real, journal-backed event types to actor animations.

No shared, industry-neutral code depends on this module's *content* --
only on the generic `WorldSceneContract` shape it produces. Every
location/collection/event name below is genuine Travel vocabulary (real
airport/destination/hotel ids, real dataclass field names, real emitted
event types), never invented for this file.

This module is generated by verticals.travel.generator.scene_templates.
Do not hand-edit the rendered `ui/world-scene.json` -- change this module
and regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import json

# -- locations ---------------------------------------------------------------
# x/y are normalised [0, 1] scene-space coordinates. UK origin airports sit
# on the left; Mediterranean destinations/hotels sit on the right, each
# hotel offset slightly from its destination (hotels bind position via
# their own id as a location -- see _HOTEL_LOCATIONS below -- so every
# hotel id must also exist as a real scene location).
_AIRPORT_LOCATIONS = [
    {"id": "APT-LGW", "label": "London Gatwick", "x": 0.08, "y": 0.35},
    {"id": "APT-MAN", "label": "Manchester Airport", "x": 0.05, "y": 0.15},
    {"id": "APT-BHX", "label": "Birmingham Airport", "x": 0.08, "y": 0.55},
]

_DESTINATION_LOCATIONS = [
    {"id": "DST-PMI", "label": "Palma de Mallorca", "x": 0.75, "y": 0.30},
    {"id": "DST-TFS", "label": "Tenerife South", "x": 0.65, "y": 0.75},
    {"id": "DST-AYT", "label": "Antalya", "x": 0.90, "y": 0.55},
]

_HOTEL_LOCATIONS = [
    {"id": "HTL-SUN-PMI", "label": "Sunseeker Palma Bay Resort", "x": 0.80, "y": 0.25},
    {"id": "HTL-BLU-TFS", "label": "Bluewave Tenerife Gardens", "x": 0.70, "y": 0.80},
    {"id": "HTL-SUN-AYT", "label": "Sunseeker Antalya Bay Resort", "x": 0.95, "y": 0.60},
]

_OPERATIONAL_LOCATIONS = [
    # The staff/customer-service home base, and the default/fallback
    # location for parties, customers, bookings, disruptions and recovery
    # decisions before (or without) a resolvable real travel location --
    # e.g. a customer who has not yet booked, or a disruption whose
    # resource is not itself a flight.
    {"id": "home", "label": "Sales & Service Hub", "x": 0.05, "y": 0.90},
]

_LOCATIONS = _AIRPORT_LOCATIONS + _DESTINATION_LOCATIONS + _HOTEL_LOCATIONS + _OPERATIONAL_LOCATIONS

# -- actor bindings ------------------------------------------------------------
# Position-strategy fields are flat keys alongside collection/kind/id_field/
# state_field (per `api.shared.world_scene_contracts.load_world_scene`'s
# source-JSON shape) -- nesting under a "position" object only happens in
# `WorldSceneContract.to_metadata()`'s runtime-manifest OUTPUT.
_ACTOR_BINDINGS = [
    {
        "collection": "flights",
        "kind": "flight",
        "id_field": "id",
        "state_field": "status",
        "route_field": "route_location_ids",
        "progress_field": "progress",
    },
    {
        "collection": "transfers",
        "kind": "transfer",
        "id_field": "id",
        "state_field": "status",
        "route_field": "route_location_ids",
        "progress_field": "progress",
    },
    {
        "collection": "parties",
        "kind": "party",
        "id_field": "id",
        "state_field": "state",
        "location_field": "current_location_id",
    },
    {
        "collection": "customers",
        "kind": "customer",
        "id_field": "id",
        "state_field": "status",
        "location_field": "current_location_id",
    },
    {
        "collection": "staff",
        "kind": "staff",
        "id_field": "id",
        "state_field": "last_action",
        "location_field": "current_location_id",
    },
    {
        "collection": "hotels",
        "kind": "hotel",
        "id_field": "id",
        "state_field": "occupancy_status",
        # Self-referential: a hotel's own id is also a real scene location
        # (see _HOTEL_LOCATIONS above).
        "location_field": "id",
    },
    {
        "collection": "bookings",
        "kind": "booking",
        "id_field": "id",
        "state_field": "recovery_status",
        "location_field": "current_location_id",
    },
    {
        "collection": "disruptions",
        "kind": "disruption",
        "id_field": "id",
        "state_field": "status",
        "location_field": "current_location_id",
    },
    {
        "collection": "recovery_decisions",
        "kind": "recovery_decision",
        "id_field": "id",
        "state_field": "outcome",
        "location_field": "current_location_id",
    },
    {
        "collection": "recovery_decisions",
        "kind": "workflow",
        "id_field": "workflow_id",
        "state_field": "outcome",
        "location_field": "current_location_id",
    },
]

# -- event -> animation mappings -----------------------------------------------
# Every entry names a real, journal-backed event type this pack actually
# emits (verified against verticals.travel.generator.world_templates,
# commands_templates.py and processes.py, plus the generic, cross-vertical
# HITL responder.* events api.server.services.world_bridge emits for every
# vertical's disruption flow) and references exactly one real actor via
# "actor_id"/"target_id" (the emitting event's own top-level fields) or an
# "actor_id_field" dotted payload path -- never a fixed literal id.
_EVENT_MAPPINGS = [
    # -- flight lifecycle --
    {"event_type": "flight.departed", "animation_type": "depart", "actor_id_field": "actor_id"},
    {"event_type": "flight.arrived", "animation_type": "arrive", "actor_id_field": "actor_id"},
    {"event_type": "flight.cancelled", "animation_type": "alert", "actor_id_field": "actor_id"},
    {"event_type": "flight.capacity_released", "animation_type": "capacity", "actor_id_field": "actor_id"},
    {"event_type": "flight.capacity_reserved", "animation_type": "capacity", "actor_id_field": "actor_id"},
    # -- transfer lifecycle --
    {"event_type": "transfer.departed", "animation_type": "depart", "actor_id_field": "actor_id"},
    {"event_type": "transfer.completed", "animation_type": "arrive", "actor_id_field": "actor_id"},
    {"event_type": "transfer.capacity_released", "animation_type": "capacity", "actor_id_field": "actor_id"},
    {"event_type": "transfer.capacity_reserved", "animation_type": "capacity", "actor_id_field": "actor_id"},
    # -- travelling party stages --
    {"event_type": "party.checked_in", "animation_type": "move", "actor_id_field": "actor_id"},
    {"event_type": "party.boarded", "animation_type": "move", "actor_id_field": "actor_id"},
    {"event_type": "party.disembarked", "animation_type": "move", "actor_id_field": "actor_id"},
    {"event_type": "party.arrived_at_resort", "animation_type": "move", "actor_id_field": "actor_id"},
    {"event_type": "party.reaccommodated", "animation_type": "state", "actor_id_field": "actor_id"},
    # -- ordinary shopping / booking / payment flow --
    {"event_type": "customer.browsed", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "customer.engaged", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "customer.booked", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "booking.confirmed", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "booking.deposit_paid", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "booking.paid", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "payment.succeeded", "animation_type": "state", "actor_id_field": "target_id"},
    # -- staff operational activity --
    {"event_type": "staff.handled_checkin", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "staff.handled_arrival", "animation_type": "state", "actor_id_field": "actor_id"},
    # -- disruption / sensor --
    {"event_type": "disruption.reported", "animation_type": "alert", "actor_id_field": "actor_id"},
    {"event_type": "disruption.resolved", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "sensor.tripped", "animation_type": "alert", "actor_id_field": "target_id"},
    # -- HITL (generic, cross-vertical responder events; real for Travel) --
    {
        "event_type": "responder.requested",
        "animation_type": "state",
        "actor_id_field": "payload.observation.booking_id",
    },
    {
        "event_type": "responder.decided",
        "animation_type": "state",
        "actor_id_field": "payload.command.payload.booking_id",
    },
    # -- booking / traveller recovery, command and evaluation --
    {"event_type": "booking.reaccommodated", "animation_type": "move", "actor_id_field": "actor_id"},
    {"event_type": "recovery.decision_recorded", "animation_type": "state", "actor_id_field": "actor_id"},
    {"event_type": "recovery.command_recorded", "animation_type": "state", "actor_id_field": "target_id"},
    {"event_type": "recovery.evaluation_recorded", "animation_type": "state", "actor_id_field": "target_id"},
]


def render_world_scene_json() -> str:
    """Render `ui/world-scene.json`: the Travel pack's spatial scene source."""
    data = {
        "version": "1",
        "title": "Travel Operations World",
        "locations": _LOCATIONS,
        "actor_bindings": _ACTOR_BINDINGS,
        "event_mappings": _EVENT_MAPPINGS,
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"
