"""Hand-authored source templates for the Travel pack's per-process assets
and skill surface.

Renders, per process (looping `PROCESS_SPECS` / `CASE_SPECS` from
`verticals.travel.generator.portfolio` -- never hand-duplicating any of
the eight near-identical blocks): `domains/<workflow_type>.yaml`,
`profiles/<workflow_type>.json`, `cases/<workflow_type>.json`,
`skills/<workflow_type>/SKILL.md`, one `personae/<role>/SKILL.md` per
authority role (fourteen total), and `policies/authority.yaml`.

This module is generated by verticals.travel.generator.skill_templates.
Do not hand-edit the rendered files -- change this module (or
`portfolio.py`) and regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import json

import yaml

from verticals.travel.generator.portfolio import (
    AUTHORITY_BY_ROLE,
    AUTHORITY_SPECS,
    CASE_BY_WORKFLOW_TYPE,
    FUNCTION_BY_NAME,
    PROCESS_SPECS,
)

# One human-readable trigger predicate/threshold per process, describing
# exactly what that process's own `detect_*` function in
# `worlds/processes.py` checks -- documentation mirrors the executable
# detector rather than inventing unrelated marketing language.
_TRIGGER_PREDICATES: dict[str, tuple[str, str]] = {
    "holiday-sales-booking": (
        "a customer quote reaches status 'ready' with a live flight, hotel "
        "and transfer still holding availability",
        "any quote whose status becomes 'ready'",
    ),
    "capacity-yield-management": (
        "a hotel allotment's booked-room ratio rises to or above its "
        "pressure threshold while a paired allotment still has spare rooms",
        "allotment utilisation >= 0.85 with headroom available elsewhere",
    ),
    "flight-disruption-recovery": (
        "a flight is cancelled while it still has confirmed, paid "
        "bookings attached to it",
        "flight.status == 'cancelled' and booking_count > 0",
    ),
    "hotel-supplier-recovery": (
        "a hotel allotment supplier shortfall disruption is reported "
        "against a live allotment",
        "open disruption of kind 'hotel_allotment_shortfall'",
    ),
    "cancellation-refund": (
        "a customer cancellation is accepted against a paid booking",
        "open disruption of kind 'customer_cancellation_accepted'",
    ),
    "payment-exception": (
        "a balance payment attempt on a booking fails or lapses",
        "open disruption of kind 'balance_payment_exception'",
    ),
    "destination-operations": (
        "a resort transfer is flagged at risk of missing its arrival "
        "window",
        "open disruption of kind 'transfer_arrival_risk'",
    ),
    "proactive-customer-care": (
        "a booking's itinerary changes materially enough to warrant "
        "proactive customer contact",
        "open disruption of kind 'material_itinerary_change'",
    ),
}


def _authority_block(role: str) -> dict[str, object]:
    row = AUTHORITY_BY_ROLE[role]
    return {
        "role": row.role,
        "spend_limit_gbp": row.spend_limit_gbp,
        "approval_bound_gbp": row.spend_limit_gbp,
        "approval_actions": list(row.approval_actions),
        "delegate_to": row.delegate_to,
    }


def render_profile_json(workflow_type: str) -> str:
    """Render `profiles/<workflow_type>.json`: executable profile data.

    Every one of the eleven required keys (trigger, objective,
    orchestrator, phases, skills, tools, authority, command,
    mutation_contract, evaluation_contract, maturity) is populated from
    the same `ProcessSpec` / `CaseSpec` rows that drive the executable
    detector, evaluator and command handler -- never invented separately.
    """
    spec = next(s for s in PROCESS_SPECS if s.workflow_type == workflow_type)
    case = CASE_BY_WORKFLOW_TYPE[workflow_type]
    predicate, threshold = _TRIGGER_PREDICATES[workflow_type]
    profile = {
        "workflow_type": spec.workflow_type,
        "display_name": spec.display_name,
        "hero": spec.hero,
        "function": spec.function,
        "trigger": {
            "sensor_id": spec.sensor_id,
            "predicate": predicate,
            "threshold": threshold,
        },
        "objective": {
            "objective_type": spec.objective_type,
            "description": spec.skill_summary,
        },
        "orchestrator": {
            "name": spec.orchestrator_name,
            "workflow_id_prefix": spec.workflow_id_prefix,
            "timeout_seconds": spec.timeout_seconds,
        },
        "phases": [
            {"name": phase.name, "kind": phase.kind} for phase in spec.phases
        ],
        "skills": [spec.workflow_type],
        "tools": list(spec.tools),
        "authority": _authority_block(spec.authority_role),
        "command": {
            "command_type": spec.command_type,
            "required_fields": sorted(case.command_payload),
        },
        "mutation_contract": {
            "success_event_types": list(spec.success_event_types),
            "failure_event_types": list(spec.failure_event_types),
            "evaluation_timeout_minutes": spec.evaluation_timeout_minutes,
        },
        "evaluation_contract": {
            "evaluation_type": spec.evaluation_type,
            "evaluator_fn": spec.evaluator_fn,
        },
        "maturity": spec.maturity,
    }
    if spec.hitl_gate is not None:
        profile["hitl_gate"] = {
            "gate_phase": spec.hitl_gate.gate_phase,
            "external_event": spec.hitl_gate.external_event,
            "persona": spec.hitl_gate.persona,
            "wait_probability": spec.hitl_gate.wait_probability,
        }
    return json.dumps(profile, indent=2, sort_keys=True) + "\n"


def render_case_json(workflow_type: str) -> str:
    """Render `cases/<workflow_type>.json`: the same reference scenario
    rendered into `worlds/processes.REFERENCE_CASES` by
    `process_templates.render_worlds_processes_py`, mirrored as data so
    the executable case and its documentation never drift apart."""
    case = CASE_BY_WORKFLOW_TYPE[workflow_type]
    payload = {
        "workflow_type": case.workflow_type,
        "run_until_minutes": case.run_until_minutes,
        "disruption": (
            {"kind": case.disruption[0], "resource_id": case.disruption[1]}
            if case.disruption is not None
            else None
        ),
        "detect_target_id": case.detect_target_id,
        "command_payload": dict(case.command_payload),
        "expected_event_type": case.expected_event_type,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_domain_yaml(workflow_type: str) -> str:
    """Render `domains/<workflow_type>.yaml`: a YAML mirror of that
    process's `Domain` row in `domains.py`, for human review/diffing."""
    spec = next(s for s in PROCESS_SPECS if s.workflow_type == workflow_type)
    data = {
        "workflow_type": spec.workflow_type,
        "display_name": spec.display_name,
        "workflow_id_prefix": spec.workflow_id_prefix,
        "orchestrator_name": spec.orchestrator_name,
        "function": spec.function,
        "operator_surface": FUNCTION_BY_NAME[spec.function].operator_surface,
        "hero": spec.hero,
        "phases": [
            {"name": phase.name, "kind": phase.kind} for phase in spec.phases
        ],
        "skills": [spec.workflow_type],
        "authority_role": spec.authority_role,
    }
    if spec.hitl_gate is not None:
        data["hitl_gates"] = [
            {
                "gate_phase": spec.hitl_gate.gate_phase,
                "external_event": spec.hitl_gate.external_event,
                "persona": spec.hitl_gate.persona,
                "wait_probability": spec.hitl_gate.wait_probability,
            }
        ]
    else:
        data["hitl_gates"] = []
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


def render_skill_md(workflow_type: str) -> str:
    """Render `skills/<workflow_type>/SKILL.md`.

    Frontmatter starts at byte zero (required by the shared pack loader's
    `_FRONTMATTER` regex) with `name`, `description` and an
    `allowed-tools` YAML list naming that process's exact
    `mcps.travel_operations` tool pair.
    """
    spec = next(s for s in PROCESS_SPECS if s.workflow_type == workflow_type)
    tool_lines = "\n".join(f"  - {tool}" for tool in spec.tools)
    lines = [
        "---",
        f"name: {spec.workflow_type}",
        f"description: {spec.skill_summary}",
        "allowed-tools:",
        tool_lines,
        "---",
        "",
        f"# {spec.display_name}",
        "",
        spec.skill_summary,
        "",
        f"- **Sensor:** `{spec.sensor_id}`",
        f"- **Objective:** `{spec.objective_type}`",
        f"- **Command:** `{spec.command_type}`",
        f"- **Evaluation:** `{spec.evaluation_type}`",
        f"- **Authority:** `{spec.authority_role}`",
        f"- **Orchestrator:** `{spec.orchestrator_name}`",
        "",
        "## Phases",
        "",
    ]
    for phase in spec.phases:
        lines.append(f"1. `{phase.name}` ({phase.kind})")
    lines.append("")
    lines.append("## Tools")
    lines.append("")
    for tool in spec.tools:
        lines.append(f"- `{tool}`")
    lines.append("")
    return "\n".join(lines)


_PERSONA_DESCRIPTIONS: dict[str, str] = {
    spec.authority_role: (
        f"Executes {spec.command_type} for {spec.display_name} within a "
        f"GBP {AUTHORITY_BY_ROLE[spec.authority_role].spend_limit_gbp:,.0f} "
        "bounded authority, escalating to "
        f"{AUTHORITY_BY_ROLE[spec.authority_role].delegate_to} above that."
    )
    for spec in PROCESS_SPECS
}
for _function_spec in FUNCTION_BY_NAME.values():
    _head_row = AUTHORITY_BY_ROLE[_function_spec.head_role]
    _PERSONA_DESCRIPTIONS[_function_spec.head_role] = (
        f"Escalation authority for {_function_spec.display}: approves "
        f"{', '.join(_head_row.approval_actions)} up to GBP "
        f"{_head_row.spend_limit_gbp:,.0f} when a process role's own bound "
        "is exceeded."
    )


def render_persona_skill_md(role: str) -> str:
    """Render `personae/<role>/SKILL.md`: exists so the shared pack
    loader's persona-hierarchy validation can resolve every process and
    head role referenced by `functions.py`."""
    row = AUTHORITY_BY_ROLE[role]
    description = _PERSONA_DESCRIPTIONS[role]
    lines = [
        "---",
        f"name: {role}",
        f"description: {description}",
        "---",
        "",
        f"# {role.replace('_', ' ').title()}",
        "",
        description,
        "",
        f"- **Spend limit:** GBP {row.spend_limit_gbp:,.0f}",
        f"- **Approval actions:** {', '.join(row.approval_actions)}",
        f"- **Delegates to:** {row.delegate_to or '(none: top of chain)'}",
        "",
    ]
    return "\n".join(lines)


def render_authority_yaml() -> str:
    """Render `policies/authority.yaml`: the real fourteen-row bounded GBP
    authority matrix as a reviewable policy document (mirrors
    `authority.py`'s `TRAVEL_AUTHORITY`, never invented separately)."""
    data = {
        "roles": [
            {
                "role": spec.role,
                "spend_limit_gbp": spec.spend_limit_gbp,
                "approval_actions": list(spec.approval_actions),
                "delegate_to": spec.delegate_to,
            }
            for spec in AUTHORITY_SPECS
        ]
    }
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


def render_governance_tools_yaml() -> str:
    """Render the governance tool schema separate from Travel authority rows."""
    return """tools:
  - id: travel_operations_check_flight_disruption
    reversible: true
    requires_authority: false
    scope_function: operations-control
    description: Read the current flight-disruption evidence.
  - id: travel_operations_reaccommodate_booking
    reversible: false
    requires_authority: true
    value_field: incremental_cost_gbp
    scope_function: operations-control
    description: Build a bounded traveller-reaccommodation plan.
"""
