"""Hand-authored source templates for the Travel vertical's `worlds/` package.

This is the ONLY place the Travel world's runtime source is hand-written.
Every file under `verticals/travel/worlds/` is generated output rendered
from the string constants below by `render.py` -- never hand-edit those
generated files directly. To change the world's behaviour, edit the
relevant constant here and regenerate via
`uv run python -m verticals.travel.generator`.

Each constant is wrapped in a triple-single-quoted string so the embedded
files' own triple-double-quoted docstrings never collide with the
wrapper. To keep that safe, every embedded file consistently uses double
quotes for its own string literals and avoids apostrophes in prose.
"""
from __future__ import annotations

WORLDS_INIT_PY = '''"""Travel vertical world package (generated by verticals.travel.generator).

Do not hand-edit. Regenerate via `uv run python -m verticals.travel.generator`.

Deliberately side-effect-free: this package must not eagerly re-export
`TravelWorld` here, because `verticals.travel.worlds.scenario` imports
`verticals.travel.actions.commands`, which imports
`verticals.travel.worlds.model` -- and importing any `verticals.travel.worlds`
submodule first runs this file. An eager re-export here would make that
import chain circular back through this package before
`verticals.travel.actions.commands` finishes initializing. Import
`TravelWorld` from `verticals.travel.worlds.scenario` directly instead.
"""
from __future__ import annotations

__all__: list[str] = []
'''

WORLDS_DIAGNOSTICS_PY = '''"""Direct, actor-world-disabled diagnostics for the Travel pack.

This module constructs a fresh, private deterministic TravelWorld only to
derive the same sensor event and Durable observation as the live world. It
never starts an actor-world service and never applies the resulting command,
so the generic diagnostic route can prove Durable/API recovery honestly while
the live actor world is intentionally disabled.

Generated by verticals.travel.generator.world_templates; do not hand-edit.
"""
from __future__ import annotations

from typing import Any

from verticals.travel.worlds.scenario import TravelWorld

_WORKFLOW_TYPE = "flight-disruption-recovery"
_TARGET_FLIGHT_ID = "FLT-ZV204"
_DISRUPTION_MINUTE = 180.0


def build_diagnostic_input(
    workflow_type: str,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return real derived input for the one supported direct diagnostic.

    The source sensor comes from a private run of the exact autonomous
    cancellation scenario. A diagnostic-specific transport id prevents this
    disabled-world run from being mistaken for a live actor-world journal
    event, while `source_sensor_event_id` preserves its real causal source.
    """
    if workflow_type != _WORKFLOW_TYPE:
        raise ValueError(f"unsupported Travel diagnostic workflow: {workflow_type!r}")

    world = TravelWorld(seed=42)
    world.run(_DISRUPTION_MINUTE)
    source = next(
        event
        for event in world.runtime.journal
        if event.type == "sensor.tripped" and event.target_id == _TARGET_FLIGHT_ID
    )
    source_event = source.to_dict()
    source_event_id = source_event["event_id"]
    diagnostic_trace_id = f"diagnostic-{source_event.get('trace_id') or source_event_id}"
    diagnostic_event = {
        **source_event,
        "event_id": f"diagnostic-{source_event_id}",
        "trace_id": diagnostic_trace_id,
        "payload": {
            **(source_event.get("payload") or {}),
            "source_sensor_event_id": source_event_id,
            "diagnostic": True,
        },
    }
    observation = world.build_observation(source_event, now=world.runtime.now)
    observation["trace_id"] = diagnostic_trace_id
    observation["evidence_event_ids"] = [source_event_id]
    return diagnostic_event, observation
'''


WORLDS_MODEL_PY = '''"""Dataclasses for the Travel vertical's deterministic, synthetic world.

Every record is a small, mutable dataclass carrying a real string "id" and
a "last_event_id" that always names the most recent causal journal event
that created or mutated it. There is no decorative or random state: every
field change in verticals.travel.worlds.scenario is paired with a journal
event that names the record (as actor or target) and carries the exact
new field values, so "last_event_id" evidence always matches final state.

This module is generated by verticals.travel.generator.world_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Airport:
    """A real-world-shaped, synthetic UK departure airport."""

    id: str
    name: str
    city: str
    country: str
    last_event_id: str | None = None


@dataclass
class Destination:
    """A holiday destination package bookings travel to."""

    id: str
    name: str
    country: str
    last_event_id: str | None = None


@dataclass
class Supplier:
    """A third-party supplier: airline, hotelier or transfer operator."""

    id: str
    name: str
    kind: str  # "airline" | "hotelier" | "transfer_operator"
    last_event_id: str | None = None


@dataclass
class StaffMember:
    """A tour-operator staff member and the most recent action they took."""

    id: str
    name: str
    role: str  # "adviser" | "operations" | "destination" | "finance"
    last_action: str | None = None
    last_event_id: str | None = None


@dataclass
class Customer:
    """An individual customer. "status" tracks their own booking journey."""

    id: str
    name: str
    email: str
    status: str = "new"  # "new" -> "browsing" -> "engaged" -> "booked"
    last_event_id: str | None = None


@dataclass
class TravellingParty:
    """A group of customers travelling together on one itinerary.

    "state" is the party's lifecycle stage and "location" is its current
    real-world position (a home marker, an airport id, a flight id, a
    destination id, or a hotel id) -- both only ever change through a
    matching causal journal event.
    """

    id: str
    lead_customer_id: str
    member_customer_ids: tuple[str, ...]
    size: int
    state: str
    location: str
    last_event_id: str | None = None


@dataclass
class Flight:
    """A scheduled flight operated by a supplier airline.

    "base_fare_gbp" is the deterministic, reference-data-fixed GBP cost of
    reaccommodating one affected party onto this flight as a
    flight-disruption-recovery replacement -- read directly as an
    already-incremental figure (never subtracted against the disrupted
    flight's own fare), so it is only meaningful on a flight that is a
    candidate replacement. It is 0.0 on every flight seeded as an ordinary,
    never-disrupted itinerary leg.
    """

    id: str
    supplier_id: str
    origin_airport_id: str
    destination_id: str
    scheduled_departure: float
    scheduled_arrival: float
    capacity: int
    reserved: int
    status: str  # "scheduled" -> "departed" -> "arrived"
    base_fare_gbp: float = 0.0
    last_event_id: str | None = None


@dataclass
class Hotel:
    """A contracted hotel at a destination."""

    id: str
    name: str
    destination_id: str
    supplier_id: str
    star_rating: int
    last_event_id: str | None = None


@dataclass
class RoomAllotment:
    """A hotel's contracted room inventory for this world.

    Conservation always holds: 0 <= occupied <= reserved <= allotment <=
    total.
    """

    id: str
    hotel_id: str
    total: int
    allotment: int
    reserved: int
    occupied: int
    last_event_id: str | None = None


@dataclass
class Transfer:
    """A resort transfer tied to exactly one flight arrival."""

    id: str
    destination_id: str
    flight_id: str
    supplier_id: str
    capacity: int
    reserved: int
    status: str  # "scheduled" -> "in_progress" -> "completed"
    last_event_id: str | None = None


@dataclass
class Quote:
    """A price quote an adviser prepares for a travelling party."""

    id: str
    party_id: str
    customer_id: str
    adviser_id: str
    price: float | None
    status: str  # "requested" -> "offered" -> "converted"
    last_event_id: str | None = None


@dataclass
class Booking:
    """A confirmed package booking converted from a quote.

    "status" is either the two-step "confirmed" -> "deposit_paid" -> "paid"
    ordinary sales journey, or a direct "confirmed" -> "paid" one-shot
    package sale (verticals.travel.actions.commands.confirm_package_booking).
    A booking can terminate as "cancelled" (cancellation-refund or a
    payment-exception release). "recovery_status" stays `None` unless a
    flight-disruption-recovery command has moved this booking onto a
    replacement flight/transfer, in which case it becomes
    `"reaccommodated"` -- real, queryable evidence distinct from the
    ordinary sales "status" progression above.
    """

    id: str
    quote_id: str
    party_id: str
    customer_id: str
    flight_id: str
    hotel_id: str
    allotment_id: str
    transfer_id: str
    rooms: int
    total_price: float
    status: str
    recovery_status: str | None = None
    last_event_id: str | None = None


@dataclass
class Payment:
    """A successful payment against a booking."""

    id: str
    booking_id: str
    kind: str  # "deposit" | "balance" | "full" (one-shot sale)
    amount: float
    last_event_id: str | None = None


@dataclass
class Refund:
    """A refund issued against a cancelled booking.

    Created by verticals.travel.actions.commands.cancel_and_refund_booking.
    """

    id: str
    booking_id: str
    amount: float
    reason: str
    status: str  # "issued"
    last_event_id: str | None = None


@dataclass
class Disruption:
    """A reported disruption against a resource.

    Reported by TravelWorld.report_disruption and resolved by whichever of
    the eight verticals.travel.actions.commands handlers accepts a command
    naming it. "status" moves "reported" -> "resolved" only on a successful
    command; a rejected command never touches it.
    """

    id: str
    resource_id: str
    kind: str
    reported_at: float
    status: str = "reported"
    last_event_id: str | None = None


@dataclass
class CareAction:
    """A customer-care action issued against a booking's travelling party.

    Created by verticals.travel.actions.commands.issue_customer_care_action.
    "kind" is "notification" (no cost) or "goodwill_gesture" (a bounded GBP
    gesture, checked against the issuing role's authority).
    """

    id: str
    booking_id: str
    party_id: str
    kind: str  # "notification" | "goodwill_gesture"
    amount_gbp: float
    message: str
    status: str  # "issued"
    last_event_id: str | None = None


@dataclass
class RecoveryDecision:
    """A HITL or auto-approval decision against one flight-disruption-recovery.

    Created by the option-based path of
    verticals.travel.actions.commands.reaccommodate_travellers once a real
    Durable orchestrator instance's TravelRecoveryApproval decision (or its
    own auto-approval for a bounded, non-material option) has been
    independently re-validated. One decision per workflow_id: a declined,
    timed-out or malformed decision never reaches this handler at all, so
    every RecoveryDecision that exists always has "outcome" of "approved"
    or "auto_approved".
    """

    id: str
    workflow_id: str
    option_id: str
    outcome: str  # "approved" | "auto_approved"
    decided_by: str | None
    last_event_id: str | None = None


@dataclass
class RecoveryCommand:
    """The typed reaccommodate_travellers command one RecoveryDecision authorised.

    A real, queryable world record of the same command
    TravelWorld.apply_command already applies idempotently by
    `command_id`, so "the command that reaccommodated this booking" is a
    first-class actor tests and evidence trails can look up directly,
    rather than only the transient SimulationCommand argument. Carries the
    old (disrupted) and new (replacement) flight's own real `supplier_id`
    straight from the RecoveryOption that authorised it, so this audit
    record never loses which real supplier is losing and gaining this
    booking even though only flight ids are named elsewhere.
    """

    id: str
    workflow_id: str
    decision_id: str
    option_id: str
    booking_id: str
    party_id: str
    old_flight_id: str
    new_flight_id: str
    old_supplier_id: str
    new_supplier_id: str
    incremental_cost_gbp: float
    last_event_id: str | None = None


@dataclass
class RecoveryEvaluation:
    """The PASS outcome recorded once a RecoveryCommand's mutation lands.

    Only ever created after every reaccommodation precondition passed and
    the atomic capacity/booking/party mutation actually applied -- so
    "status" is always "pass" here. A command that fails any precondition
    never reaches this record at all: it returns a "command.rejected"
    event instead with zero mutation and zero RecoveryEvaluation created.
    """

    id: str
    workflow_id: str
    command_id: str
    booking_id: str
    party_id: str
    status: str
    last_event_id: str | None = None
'''

WORLDS_REFERENCE_DATA_PY = '''"""Deterministic seed/reference data and lifecycle plan for the Travel world.

Every builder below is a plain function returning fresh dataclass
instances -- never a module-level singleton -- so multiple independent
verticals.travel.worlds.scenario.TravelWorld instances (as used by the
determinism tests) never share mutable state.

This module is generated by verticals.travel.generator.world_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from dataclasses import dataclass

from verticals.travel.worlds.model import (
    Airport,
    Customer,
    Destination,
    Flight,
    Hotel,
    RoomAllotment,
    StaffMember,
    Supplier,
    Transfer,
    TravellingParty,
)


def build_airports() -> list[Airport]:
    return [
        Airport(id="APT-LGW", name="London Gatwick", city="London", country="United Kingdom"),
        Airport(id="APT-MAN", name="Manchester Airport", city="Manchester", country="United Kingdom"),
        Airport(id="APT-BHX", name="Birmingham Airport", city="Birmingham", country="United Kingdom"),
    ]


def build_destinations() -> list[Destination]:
    return [
        Destination(id="DST-PMI", name="Palma de Mallorca", country="Spain"),
        Destination(id="DST-TFS", name="Tenerife South", country="Spain"),
        Destination(id="DST-AYT", name="Antalya", country="Turkiye"),
    ]


def build_suppliers() -> list[Supplier]:
    return [
        Supplier(id="SUP-ZVA", name="Zephyr Vista Airways", kind="airline"),
        Supplier(id="SUP-CRA", name="Coral Ridge Air", kind="airline"),
        Supplier(id="SUP-SUN", name="Sunseeker Hotels Group", kind="hotelier"),
        Supplier(id="SUP-BLU", name="Bluewave Resorts", kind="hotelier"),
        Supplier(id="SUP-CST", name="Coastline Transfers", kind="transfer_operator"),
    ]


def build_staff() -> list[StaffMember]:
    return [
        StaffMember(id="ADV-1", name="Priya Shah", role="adviser"),
        StaffMember(id="ADV-2", name="Tom Fletcher", role="adviser"),
        StaffMember(id="OPS-1", name="Maria Gonzalez", role="operations"),
        StaffMember(id="REP-1", name="Elif Kaya", role="destination"),
        StaffMember(id="FIN-1", name="Grace Adebayo", role="finance"),
    ]


def build_customers() -> list[Customer]:
    names = [
        ("CUS-1", "Alice Whitmore"),
        ("CUS-2", "James Whitmore"),
        ("CUS-3", "Ben Carter"),
        ("CUS-4", "Chloe Dixon"),
        ("CUS-5", "Oliver Dixon"),
        ("CUS-6", "Sophie Dixon"),
        ("CUS-7", "Jack Dixon"),
        ("CUS-8", "Daniel Osei"),
        ("CUS-9", "Ruth Osei"),
        ("CUS-10", "Emma Foster"),
        ("CUS-11", "Noah Bennett"),
    ]
    customers = []
    for customer_id, name in names:
        local_part = name.lower().replace(" ", ".")
        customers.append(Customer(id=customer_id, name=name, email=f"{local_part}@example.com"))
    return customers


def build_parties() -> list[TravellingParty]:
    definitions = [
        ("PTY-1", ("CUS-1", "CUS-2")),
        ("PTY-2", ("CUS-3",)),
        ("PTY-3", ("CUS-4", "CUS-5", "CUS-6", "CUS-7")),
        ("PTY-4", ("CUS-8", "CUS-9")),
        ("PTY-5", ("CUS-10",)),
        ("PTY-6", ("CUS-11",)),
    ]
    return [
        TravellingParty(
            id=party_id,
            lead_customer_id=member_ids[0],
            member_customer_ids=member_ids,
            size=len(member_ids),
            state="planning",
            location="home",
        )
        for party_id, member_ids in definitions
    ]


def build_flights() -> list[Flight]:
    return [
        Flight(
            id="FLT-ZV101",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-LGW",
            destination_id="DST-PMI",
            scheduled_departure=90.0,
            scheduled_arrival=140.0,
            capacity=180,
            reserved=0,
            status="scheduled",
        ),
        Flight(
            id="FLT-ZV102",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-MAN",
            destination_id="DST-TFS",
            scheduled_departure=210.0,
            scheduled_arrival=270.0,
            capacity=160,
            reserved=0,
            status="scheduled",
        ),
        Flight(
            id="FLT-CA150",
            supplier_id="SUP-CRA",
            origin_airport_id="APT-BHX",
            destination_id="DST-AYT",
            scheduled_departure=240.0,
            scheduled_arrival=300.0,
            capacity=150,
            reserved=0,
            status="scheduled",
        ),
        Flight(
            id="FLT-ZV204",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-LGW",
            destination_id="DST-PMI",
            scheduled_departure=320.0,
            scheduled_arrival=380.0,
            capacity=180,
            reserved=0,
            status="scheduled",
        ),
        # -- Task 6: flight-disruption-recovery replacement candidates --
        # Never used by any build_party_plans() itinerary, so "reserved"
        # only ever moves off zero via a real reaccommodation command.
        # base_fare_gbp is read directly as the already-incremental GBP
        # cost of choosing this flight as a replacement (see Flight's own
        # docstring above) -- deliberately chosen so ranking by
        # (material change count, incremental cost, arrival delay, id)
        # is unambiguous and exercises every documented recovery branch:
        # FLT-ZV205 is the cheapest, least-delayed, non-material option
        # but crosses the GBP 750 auto-approve bound; FLT-CA160 is
        # cheaper than the bound but its longer delay is material;
        # FLT-ZV206 is both over-bound and material; FLT-CA161 is worse
        # than all three on every axis and is bounded out of the top 3.
        Flight(
            id="FLT-ZV205",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-LGW",
            destination_id="DST-PMI",
            scheduled_departure=365.0,
            scheduled_arrival=425.0,
            capacity=180,
            reserved=0,
            status="scheduled",
            base_fare_gbp=900.0,
        ),
        Flight(
            id="FLT-CA160",
            supplier_id="SUP-CRA",
            origin_airport_id="APT-BHX",
            destination_id="DST-PMI",
            scheduled_departure=460.0,
            scheduled_arrival=520.0,
            capacity=150,
            reserved=0,
            status="scheduled",
            base_fare_gbp=650.0,
        ),
        Flight(
            id="FLT-ZV206",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-LGW",
            destination_id="DST-PMI",
            scheduled_departure=485.0,
            scheduled_arrival=545.0,
            capacity=180,
            reserved=0,
            status="scheduled",
            base_fare_gbp=1100.0,
        ),
        Flight(
            id="FLT-CA161",
            supplier_id="SUP-CRA",
            origin_airport_id="APT-BHX",
            destination_id="DST-PMI",
            scheduled_departure=540.0,
            scheduled_arrival=600.0,
            capacity=150,
            reserved=0,
            status="scheduled",
            base_fare_gbp=1500.0,
        ),
        # Low-cost, non-material replacement for FLT-ZV102 (DST-TFS): 30
        # minute arrival delay stays under the material-change threshold
        # and GBP 300 stays under the GBP 750 auto-approve bound, so the
        # recovery orchestrator's low-cost branch bypasses HITL entirely.
        Flight(
            id="FLT-ZV103",
            supplier_id="SUP-ZVA",
            origin_airport_id="APT-MAN",
            destination_id="DST-TFS",
            scheduled_departure=240.0,
            scheduled_arrival=300.0,
            capacity=160,
            reserved=0,
            status="scheduled",
            base_fare_gbp=300.0,
        ),
    ]


def build_hotels() -> list[Hotel]:
    return [
        Hotel(
            id="HTL-SUN-PMI",
            name="Sunseeker Palma Bay Resort",
            destination_id="DST-PMI",
            supplier_id="SUP-SUN",
            star_rating=4,
        ),
        Hotel(
            id="HTL-BLU-TFS",
            name="Bluewave Tenerife Gardens",
            destination_id="DST-TFS",
            supplier_id="SUP-BLU",
            star_rating=4,
        ),
        Hotel(
            id="HTL-SUN-AYT",
            name="Sunseeker Antalya Bay Resort",
            destination_id="DST-AYT",
            supplier_id="SUP-SUN",
            star_rating=5,
        ),
    ]


def build_allotments() -> list[RoomAllotment]:
    return [
        RoomAllotment(
            id="ALT-SUN-PMI", hotel_id="HTL-SUN-PMI", total=200, allotment=80, reserved=0, occupied=0,
        ),
        RoomAllotment(
            id="ALT-BLU-TFS", hotel_id="HTL-BLU-TFS", total=180, allotment=70, reserved=0, occupied=0,
        ),
        RoomAllotment(
            id="ALT-SUN-AYT", hotel_id="HTL-SUN-AYT", total=220, allotment=90, reserved=0, occupied=0,
        ),
    ]


def build_transfers() -> list[Transfer]:
    return [
        Transfer(
            id="TRF-1",
            destination_id="DST-PMI",
            flight_id="FLT-ZV101",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-2",
            destination_id="DST-PMI",
            flight_id="FLT-ZV204",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-3",
            destination_id="DST-TFS",
            flight_id="FLT-ZV102",
            supplier_id="SUP-CST",
            capacity=40,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-4",
            destination_id="DST-AYT",
            flight_id="FLT-CA150",
            supplier_id="SUP-CST",
            capacity=40,
            reserved=0,
            status="scheduled",
        ),
        # -- Task 6: paired 1:1 with each replacement candidate flight --
        # A Transfer is always tied to exactly one flight arrival (see
        # Transfer's own docstring), so every replacement candidate flight
        # above needs its own paired transfer here.
        Transfer(
            id="TRF-5",
            destination_id="DST-PMI",
            flight_id="FLT-ZV205",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-6",
            destination_id="DST-PMI",
            flight_id="FLT-CA160",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-7",
            destination_id="DST-PMI",
            flight_id="FLT-ZV206",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-8",
            destination_id="DST-PMI",
            flight_id="FLT-CA161",
            supplier_id="SUP-CST",
            capacity=50,
            reserved=0,
            status="scheduled",
        ),
        Transfer(
            id="TRF-9",
            destination_id="DST-TFS",
            flight_id="FLT-ZV103",
            supplier_id="SUP-CST",
            capacity=40,
            reserved=0,
            status="scheduled",
        ),
    ]


@dataclass(frozen=True)
class PartyPlan:
    """The deterministic, staggered pipeline timeline for one party.

    Every timestamp is an absolute simulation minute. A stage whose
    timestamp is None means the party's pipeline stops before that stage
    (used for the two parties that do not convert into a booking).
    `browse_at` always precedes `request_at`: every party's lead customer
    browses a destination before requesting a quote, and
    `browse_destination_id` names the destination they were looking at
    (not necessarily the one they eventually book, since ordinary browsing
    is exploratory).
    """

    party_id: str
    quote_id: str
    customer_id: str
    adviser_id: str
    price: float | None
    rooms: int
    browse_at: float
    browse_destination_id: str
    request_at: float
    offer_at: float | None
    convert_at: float | None
    deposit_at: float | None
    balance_at: float | None
    flight_id: str | None
    hotel_id: str | None
    allotment_id: str | None
    transfer_id: str | None
    booking_id: str | None
    deposit_payment_id: str | None
    balance_payment_id: str | None


def build_party_plans() -> list[PartyPlan]:
    return [
        PartyPlan(
            party_id="PTY-1", quote_id="QTE-1", customer_id="CUS-1", adviser_id="ADV-1",
            price=1200, rooms=1,
            browse_at=5, browse_destination_id="DST-PMI",
            request_at=10, offer_at=25, convert_at=40, deposit_at=50, balance_at=65,
            flight_id="FLT-ZV101", hotel_id="HTL-SUN-PMI", allotment_id="ALT-SUN-PMI",
            transfer_id="TRF-1",
            booking_id="BKG-1", deposit_payment_id="PAY-1", balance_payment_id="PAY-2",
        ),
        PartyPlan(
            party_id="PTY-2", quote_id="QTE-2", customer_id="CUS-3", adviser_id="ADV-2",
            price=550, rooms=1,
            browse_at=9, browse_destination_id="DST-TFS",
            request_at=14, offer_at=29, convert_at=44, deposit_at=54, balance_at=69,
            flight_id="FLT-ZV102", hotel_id="HTL-BLU-TFS", allotment_id="ALT-BLU-TFS",
            transfer_id="TRF-3",
            booking_id="BKG-2", deposit_payment_id="PAY-3", balance_payment_id="PAY-4",
        ),
        PartyPlan(
            party_id="PTY-3", quote_id="QTE-3", customer_id="CUS-4", adviser_id="ADV-1",
            price=2600, rooms=2,
            browse_at=13, browse_destination_id="DST-AYT",
            request_at=18, offer_at=33, convert_at=48, deposit_at=58, balance_at=73,
            flight_id="FLT-CA150", hotel_id="HTL-SUN-AYT", allotment_id="ALT-SUN-AYT",
            transfer_id="TRF-4",
            booking_id="BKG-3", deposit_payment_id="PAY-5", balance_payment_id="PAY-6",
        ),
        PartyPlan(
            party_id="PTY-4", quote_id="QTE-4", customer_id="CUS-8", adviser_id="ADV-2",
            price=1300, rooms=1,
            browse_at=17, browse_destination_id="DST-PMI",
            request_at=22, offer_at=37, convert_at=52, deposit_at=62, balance_at=77,
            flight_id="FLT-ZV204", hotel_id="HTL-SUN-PMI", allotment_id="ALT-SUN-PMI",
            transfer_id="TRF-2",
            booking_id="BKG-4", deposit_payment_id="PAY-7", balance_payment_id="PAY-8",
        ),
        PartyPlan(
            party_id="PTY-5", quote_id="QTE-5", customer_id="CUS-10", adviser_id="ADV-1",
            price=None, rooms=1,
            browse_at=21, browse_destination_id="DST-PMI",
            request_at=26, offer_at=None, convert_at=None, deposit_at=None, balance_at=None,
            flight_id=None, hotel_id=None, allotment_id=None, transfer_id=None,
            booking_id=None, deposit_payment_id=None, balance_payment_id=None,
        ),
        PartyPlan(
            party_id="PTY-6", quote_id="QTE-6", customer_id="CUS-11", adviser_id="ADV-2",
            price=640, rooms=1,
            browse_at=25, browse_destination_id="DST-TFS",
            request_at=30, offer_at=45, convert_at=None, deposit_at=None, balance_at=None,
            flight_id=None, hotel_id=None, allotment_id=None, transfer_id=None,
            booking_id=None, deposit_payment_id=None, balance_payment_id=None,
        ),
    ]
'''

WORLDS_SCENARIO_PY = '''"""Deterministic, synthetic Travel world simulation (Task 3 + Task 4 + Task 5).

TravelWorld builds a seeded, integrated-tour-operator-style world on top
of api.server.world.runtime.SimulationRuntime: customers browse a
destination, then request quotes, advisers make offers, quotes convert
into confirmed package bookings, deposits and balances are paid, and (for
the one itinerary whose flight departs before minute 180) the party real
position advances booked -> checked-in at its origin airport -> airborne
-> disembarked at the destination -> transferred to its resort, with
hotel occupancy changing to match. Every mutation is paired with a
causal journal event that names the record it changed (as actor or
target) and carries the exact new field values, and every mutated
record last_event_id points at that exact event.

Task 4 adds the eight-process portfolio's real, journal-backed command
surface on top of that ordinary lifecycle: `report_disruption` records a
real disruption event against a resource; `apply_command` is a typed,
idempotent dispatcher (`verticals.travel.actions.commands.COMMAND_HANDLERS`)
that replays a cached result for a previously-seen `command_id` instead of
re-mutating; `run_reference_process` drives one real
sensor -> objective -> command -> evaluation pass for a named workflow type
through the generic `api.server.world` gateway, entirely as a pure Python
call -- no world-process HTTP run route is exercised anywhere in this
module.

Task 5 adds one autonomous, deterministic operational disruption on top of
that ordinary lifecycle and command surface: at simulation minute 180, once
FLT-ZV204's own ordinary shopping/booking activity has produced a real paid
package booking on it, a real supplier/operations cancellation changes its
status to `"cancelled"` and reports a real disruption, both causally
chained by `cause_event_id`/`trace_id`. A separate sensor-evaluation step
then re-derives `sensor:flight_cancellation_impact` from that mutated state
through the real generated detector -- never an unconditional emission --
so the sensor only trips while there is genuine, eligible demand at risk,
and never trips twice for the same disruption. This mutation never
releases or rebooks capacity by itself; that recovery is a distinct, later
task's command, and no objective/workflow/responder event is exercised
anywhere in this module.

Task 6 adds `build_observation`, which turns one
`sensor:flight_cancellation_impact` event into the single flat, JSON-only
dict the real Azure Durable Functions
`verticals.travel.durable.functions.TravelFlightDisruptionRecoveryOrchestrator`
and the pure `verticals.travel.recovery.planner.plan_recovery_options`
both read -- naming the exact affected booking/party/flight and every
candidate replacement flight/transfer, so the planner itself never reaches
back into this module's own mutable world state. The option-based path of
`verticals.travel.actions.commands.reaccommodate_travellers` then applies
the approved (or auto-approved) `RecoveryOption` atomically, and records
its own `RecoveryDecision`/`RecoveryCommand`/`RecoveryEvaluation` as real,
queryable world actors alongside the ordinary booking/flight/transfer
mutation.

This module is generated by verticals.travel.generator.world_templates.
Do not hand-edit -- change the generator template and regenerate via
`uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

import dataclasses
from typing import Any, Callable

from api.server.world.model import SimulationCommand, SimulationEvent
from api.server.world.runtime import SimulationRuntime
from verticals.travel.actions.commands import COMMAND_HANDLERS, reject
from verticals.travel.worlds import processes, reference_data
from verticals.travel.worlds.model import (
    Airport,
    Booking,
    CareAction,
    Customer,
    Destination,
    Disruption,
    Flight,
    Hotel,
    Payment,
    Quote,
    RecoveryCommand,
    RecoveryDecision,
    RecoveryEvaluation,
    Refund,
    RoomAllotment,
    StaffMember,
    Supplier,
    Transfer,
    TravellingParty,
)


def _jsonify(value: Any) -> Any:
    if isinstance(value, (tuple, list)):
        return [_jsonify(item) for item in value]
    if isinstance(value, dict):
        return {key: _jsonify(item) for key, item in value.items()}
    return value


class TravelWorld:
    """A deterministic, synthetic integrated-tour-operator world."""

    def __init__(self, seed: int = 42, *, runtime: SimulationRuntime | None = None) -> None:
        self.seed = seed
        # Task 3 deliberately builds and seeds eagerly in one phase so the
        # scenario is immediately usable standalone in tests. The generic
        # `ActorWorldService` instead builds a runtime first and calls a
        # separate `.install()` afterwards (see
        # `api.server.world.packs.support.SupportScenario` for the shared
        # precedent this mirrors) -- passing `runtime=` here lets
        # `worlds.registration.build_travel_demo` share that externally
        # built runtime instead of this scenario constructing its own,
        # while every existing `TravelWorld(seed=...)` call site keeps
        # working unchanged.
        self.runtime = runtime if runtime is not None else SimulationRuntime(seed=seed)

        self.airports: dict[str, Airport] = {}
        self.destinations: dict[str, Destination] = {}
        self.suppliers: dict[str, Supplier] = {}
        self.staff: dict[str, StaffMember] = {}
        self.customers: dict[str, Customer] = {}
        self.parties: dict[str, TravellingParty] = {}
        self.flights: dict[str, Flight] = {}
        self.hotels: dict[str, Hotel] = {}
        self.allotments: dict[str, RoomAllotment] = {}
        self.transfers: dict[str, Transfer] = {}
        self.quotes: dict[str, Quote] = {}
        self.bookings: dict[str, Booking] = {}
        self.payments: dict[str, Payment] = {}
        self.refunds: dict[str, Refund] = {}
        self.disruptions: dict[str, Disruption] = {}
        self.care_actions: dict[str, CareAction] = {}

        # Task 6: flight-disruption-recovery's own real, queryable actors.
        self.recovery_decisions: dict[str, RecoveryDecision] = {}
        self.recovery_commands: dict[str, RecoveryCommand] = {}
        self.recovery_evaluations: dict[str, RecoveryEvaluation] = {}

        # Task 4: idempotency cache keyed by command_id -- replaying a
        # previously-seen command_id (success or rejection) always returns
        # the cached event and never re-emits or re-mutates.
        self._processed_commands: dict[str, SimulationEvent] = {}

        self._seed_world()
        self._schedule_processes()

    def install(self) -> None:
        """No-op: satisfies `ActorWorldService`'s two-phase build/install
        convention. Task 3 chose eager single-phase seeding inside
        `__init__` (for standalone testability), so there is no deferred
        seeding step left to run here.
        """
        return None

    # -- generic causal-mutation helpers ----------------------------------

    def _created(
        self,
        event_type: str,
        record: Any,
        *,
        target_id: str | None = None,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
        extra_payload: dict[str, Any] | None = None,
    ):
        payload = dict(extra_payload or {})
        payload.setdefault("id", record.id)
        event = self.runtime.emit(
            event_type,
            actor_id=record.id,
            target_id=target_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            payload=payload,
        )
        record.last_event_id = event.event_id
        return event

    def _apply(
        self,
        event_type: str,
        record: Any,
        changes: dict[str, Any],
        *,
        target_id: str | None = None,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
        extra_payload: dict[str, Any] | None = None,
    ):
        payload = {**(extra_payload or {}), **changes}
        event = self.runtime.emit(
            event_type,
            actor_id=record.id,
            target_id=target_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            payload=payload,
        )
        for field, value in changes.items():
            setattr(record, field, value)
        record.last_event_id = event.event_id
        return event

    # -- genesis -------------------------------------------------------------

    def _seed_world(self) -> None:
        for airport in reference_data.build_airports():
            self.airports[airport.id] = airport
            self._created("world.airport_seeded", airport)
        for destination in reference_data.build_destinations():
            self.destinations[destination.id] = destination
            self._created("world.destination_seeded", destination)
        for supplier in reference_data.build_suppliers():
            self.suppliers[supplier.id] = supplier
            self._created("world.supplier_seeded", supplier)
        for member in reference_data.build_staff():
            self.staff[member.id] = member
            self._created("world.staff_seeded", member)
        for customer in reference_data.build_customers():
            self.customers[customer.id] = customer
            self._created("world.customer_seeded", customer)
        for party in reference_data.build_parties():
            self.parties[party.id] = party
            self._created("world.party_seeded", party)
        for flight in reference_data.build_flights():
            self.flights[flight.id] = flight
            self._created("world.flight_seeded", flight)
        for hotel in reference_data.build_hotels():
            self.hotels[hotel.id] = hotel
            self._created("world.hotel_seeded", hotel)
        for allotment in reference_data.build_allotments():
            self.allotments[allotment.id] = allotment
            self._created("world.allotment_seeded", allotment)
        for transfer in reference_data.build_transfers():
            self.transfers[transfer.id] = transfer
            self._created("world.transfer_seeded", transfer)

    def _schedule_processes(self) -> None:
        for plan in reference_data.build_party_plans():
            self.runtime.process(self._party_pipeline(plan))
        for flight_id in sorted(self.flights):
            self.runtime.process(self._flight_lifecycle(flight_id))
        self.runtime.process(self._operations_flight_cancellation())

    # -- ordinary autonomous lifecycle ---------------------------------------

    def _party_pipeline(self, plan: reference_data.PartyPlan):
        party = self.parties[plan.party_id]
        lead_customer = self.customers[plan.customer_id]
        adviser = self.staff[plan.adviser_id]

        yield self.runtime.env.timeout(plan.browse_at)
        browsed = self._apply(
            "customer.browsed",
            lead_customer,
            {"status": "browsing"},
            target_id=party.id,
            extra_payload={"party_id": party.id, "destination_id": plan.browse_destination_id},
        )

        yield self.runtime.env.timeout(plan.request_at - plan.browse_at)
        quote = Quote(
            id=plan.quote_id,
            party_id=party.id,
            customer_id=lead_customer.id,
            adviser_id=adviser.id,
            price=None,
            status="requested",
        )
        self.quotes[quote.id] = quote
        created = self._created(
            "quote.requested",
            quote,
            target_id=party.id,
            cause_event_id=browsed.event_id,
            extra_payload={"party_id": party.id, "customer_id": lead_customer.id},
        )
        self._apply(
            "party.quote_requested",
            party,
            {"state": "quote_requested"},
            cause_event_id=created.event_id,
        )
        self._apply(
            "customer.engaged",
            lead_customer,
            {"status": "engaged"},
            cause_event_id=created.event_id,
        )

        if plan.offer_at is None:
            return
        yield self.runtime.env.timeout(plan.offer_at - plan.request_at)
        self._apply(
            "quote.offered",
            quote,
            {"price": plan.price, "status": "offered"},
            target_id=adviser.id,
        )
        self._apply(
            "staff.handled_quote",
            adviser,
            {"last_action": f"offered:{quote.id}"},
            target_id=quote.id,
        )

        if plan.convert_at is None:
            return
        yield self.runtime.env.timeout(plan.convert_at - plan.offer_at)
        self._apply("quote.converted", quote, {"status": "converted"})

        booking = Booking(
            id=plan.booking_id,
            quote_id=quote.id,
            party_id=party.id,
            customer_id=lead_customer.id,
            flight_id=plan.flight_id,
            hotel_id=plan.hotel_id,
            allotment_id=plan.allotment_id,
            transfer_id=plan.transfer_id,
            rooms=plan.rooms,
            total_price=plan.price,
            status="confirmed",
        )
        self.bookings[booking.id] = booking
        booking_created = self._created(
            "booking.confirmed",
            booking,
            target_id=quote.id,
            extra_payload={"party_id": party.id, "flight_id": plan.flight_id},
        )
        self._apply(
            "party.booked", party, {"state": "booked"}, cause_event_id=booking_created.event_id,
        )

        flight = self.flights[plan.flight_id]
        self._apply(
            "flight.capacity_reserved",
            flight,
            {"reserved": flight.reserved + party.size},
            target_id=booking.id,
        )
        allotment = self.allotments[plan.allotment_id]
        self._apply(
            "hotel.rooms_reserved",
            allotment,
            {"reserved": allotment.reserved + booking.rooms},
            target_id=booking.id,
        )
        transfer = self.transfers[plan.transfer_id]
        self._apply(
            "transfer.capacity_reserved",
            transfer,
            {"reserved": transfer.reserved + party.size},
            target_id=booking.id,
        )

        if plan.deposit_at is None:
            return
        yield self.runtime.env.timeout(plan.deposit_at - plan.convert_at)
        deposit_amount = plan.price * 20 // 100
        deposit_payment = Payment(
            id=plan.deposit_payment_id,
            booking_id=booking.id,
            kind="deposit",
            amount=deposit_amount,
        )
        self.payments[deposit_payment.id] = deposit_payment
        self._created("payment.succeeded", deposit_payment, target_id=booking.id)
        self._apply("booking.deposit_paid", booking, {"status": "deposit_paid"})
        finance = self.staff["FIN-1"]
        self._apply(
            "staff.handled_payment",
            finance,
            {"last_action": f"deposit:{deposit_payment.id}"},
            target_id=deposit_payment.id,
        )

        if plan.balance_at is None:
            return
        yield self.runtime.env.timeout(plan.balance_at - plan.deposit_at)
        balance_amount = plan.price - deposit_amount
        balance_payment = Payment(
            id=plan.balance_payment_id,
            booking_id=booking.id,
            kind="balance",
            amount=balance_amount,
        )
        self.payments[balance_payment.id] = balance_payment
        self._created("payment.succeeded", balance_payment, target_id=booking.id)
        self._apply("booking.paid", booking, {"status": "paid"})
        self._apply("customer.booked", lead_customer, {"status": "booked"})
        self._apply(
            "staff.handled_payment",
            finance,
            {"last_action": f"balance:{balance_payment.id}"},
            target_id=balance_payment.id,
        )

    def _bookings_for_flight(self, flight_id: str) -> list[Booking]:
        return sorted(
            (booking for booking in self.bookings.values() if booking.flight_id == flight_id),
            key=lambda booking: booking.id,
        )

    def _flight_lifecycle(self, flight_id: str):
        flight = self.flights[flight_id]
        checkin_offset = flight.scheduled_departure - 10
        yield self.runtime.env.timeout(checkin_offset)

        bookings = self._bookings_for_flight(flight_id)
        ops = self.staff["OPS-1"]
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply(
                "party.checked_in",
                party,
                {"state": "checked_in", "location": flight.origin_airport_id},
            )
            self._apply(
                "staff.handled_checkin",
                ops,
                {"last_action": f"checked_in:{party.id}"},
                target_id=party.id,
            )

        yield self.runtime.env.timeout(flight.scheduled_departure - checkin_offset)
        self._apply("flight.departed", flight, {"status": "departed"})
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply("party.boarded", party, {"state": "airborne", "location": flight.id})

        yield self.runtime.env.timeout(flight.scheduled_arrival - flight.scheduled_departure)
        self._apply("flight.arrived", flight, {"status": "arrived"})
        for booking in bookings:
            party = self.parties[booking.party_id]
            self._apply(
                "party.disembarked",
                party,
                {"state": "in_transfer", "location": flight.destination_id},
            )
            transfer = self.transfers[booking.transfer_id]
            self._apply("transfer.departed", transfer, {"status": "in_progress"})

        yield self.runtime.env.timeout(20)
        rep = self.staff["REP-1"]
        for booking in bookings:
            party = self.parties[booking.party_id]
            hotel = self.hotels[booking.hotel_id]
            allotment = self.allotments[booking.allotment_id]
            self._apply(
                "party.arrived_at_resort", party, {"state": "at_resort", "location": hotel.id},
            )
            self._apply(
                "hotel.rooms_occupied",
                allotment,
                {"occupied": allotment.occupied + booking.rooms},
                target_id=hotel.id,
            )
            transfer = self.transfers[booking.transfer_id]
            self._apply("transfer.completed", transfer, {"status": "completed"})
            self._apply(
                "staff.handled_arrival",
                rep,
                {"last_action": f"arrived:{party.id}"},
                target_id=party.id,
            )

    def run(self, until: float) -> None:
        self.runtime.run_until(until)

    # -- Task 4: process portfolio command/process surface --------------------

    def report_disruption(
        self,
        *,
        kind: str,
        resource_id: str,
        cause_event_id: str | None = None,
        trace_id: str | None = None,
    ) -> Disruption:
        """Record a real disruption against `resource_id`.

        Deterministic id `DIS-{kind}-{resource_id}`: reporting the exact
        same (kind, resource_id) pair twice returns the already-reported
        record unchanged instead of double-journalling it. `cause_event_id`
        and `trace_id` are optional so an autonomous mutation (Task 5's
        minute-180 flight cancellation) can causally chain this report back
        to the event that triggered it; every existing call site that omits
        them keeps its original, untraced-cause behaviour unchanged.
        """
        disruption_id = f"DIS-{kind}-{resource_id}"
        existing = self.disruptions.get(disruption_id)
        if existing is not None:
            return existing

        disruption = Disruption(
            id=disruption_id,
            resource_id=resource_id,
            kind=kind,
            reported_at=self.runtime.now,
            status="reported",
        )
        self.disruptions[disruption_id] = disruption
        self._created(
            "disruption.reported",
            disruption,
            target_id=resource_id,
            cause_event_id=cause_event_id,
            trace_id=trace_id,
            extra_payload={"kind": kind, "resource_id": resource_id},
        )
        return disruption

    def apply_command(self, command: SimulationCommand) -> SimulationEvent:
        """Typed, idempotent dispatch for the eight portfolio commands.

        Replaying a previously-seen `command_id` (whether it succeeded or
        was rejected) always returns the cached event unchanged and never
        re-mutates or re-journals: the cache is keyed purely by
        `command_id`, never by command type or payload, so a genuine retry
        with the exact same id is always safe.
        """
        cached = self._processed_commands.get(command.command_id)
        if cached is not None:
            return cached

        handler = COMMAND_HANDLERS.get(command.type)
        result = (
            reject(self, command, f"unknown command type {command.type!r}")
            if handler is None
            else handler(self, command)
        )
        self._processed_commands[command.command_id] = result
        return result

    def run_reference_process(self, workflow_type: str) -> dict[str, Any]:
        """Run one real sensor -> objective -> command -> evaluation pass.

        Drives the generic `api.server.world` objective/command/evaluation
        machinery for `workflow_type`'s reference case end to end as a pure
        Python call: arranges the exact world state the case needs, runs
        its real detector, opens and claims a real objective, and applies
        its real command through the same `CommandGateway` the live bridge
        uses. No world-process HTTP run route is exercised --
        this is a pure diagnostic call for tests and tooling; a later task
        owns scheduling this pipeline live inside a running world.
        """
        from api.server.world.commands import CommandGateway
        from api.server.world.objectives import ObjectiveManager
        from verticals.travel.worlds.processes import REFERENCE_CASES
        from verticals.travel.worlds.registration import (
            responder_for_workflow_type,
            route_for_workflow_type,
        )

        case = REFERENCE_CASES[workflow_type]
        case.setup(self)
        sensor_event = case.detect(self)

        route = route_for_workflow_type(workflow_type)
        responder = responder_for_workflow_type(workflow_type)
        objectives = ObjectiveManager(self.runtime)
        objective = objectives.open(
            sensor_event.to_dict(), route, owner_function=responder.owner_function,
        )
        # Objective is immutable: transition() returns the updated instance
        # rather than mutating in place, so the local binding must be
        # reassigned or build_command below would see a stale claimed_by.
        objective = objectives.transition(objective.id, "claimed", claimed_by=case.role)
        objective = objectives.transition(objective.id, "acting")

        gateway = CommandGateway(self.runtime, objectives, self.apply_command)
        command = case.build_command(self, objective)
        result_event = gateway.apply(objective, command)
        evaluation = gateway.evaluator.for_objective(objective.id)
        result_payload = result_event.payload or {}

        return {
            "workflow_type": workflow_type,
            "command_id": command.command_id,
            "trace_id": command.trace_id,
            "affected_actor_ids": result_payload.get("affected_actor_ids"),
            "evidence_event_ids": result_payload.get("evidence_event_ids"),
            "evaluation_status": evaluation.status if evaluation is not None else None,
        }

    # -- Task 5: autonomous operational disruption -----------------------------

    def _operations_flight_cancellation(self):
        """Autonomous minute-180 disruption: a real supplier/operations
        cancellation of FLT-ZV204, strictly after its own ordinary
        shopping/booking activity has produced a real paid booking on it.

        Mutates `Flight.status` to `"cancelled"` and reports a real
        disruption, both causally chained by cause_event_id/trace_id, then
        runs a *separate* sensor-evaluation step against the now-mutated
        world state through the real generated detector -- never an
        unconditional `sensor.tripped` emission. The detector itself
        (`verticals.travel.worlds.processes.detect_flight_cancellation_impact`)
        owns the eligibility gate (no eligible booking means no sensor) and
        the rising-edge/no-repeat guarantee, so calling it again later (or
        from anywhere else) is always a safe no-op. This mutation never
        releases or rebooks capacity by itself -- recovery is a distinct,
        later task's command.
        """
        yield self.runtime.env.timeout(180)
        flight = self.flights["FLT-ZV204"]
        cancelled_event = self._apply(
            "flight.cancelled",
            flight,
            {"status": "cancelled"},
            extra_payload={"reason": "supplier_operational_cancellation"},
        )
        self.report_disruption(
            kind="flight_cancellation",
            resource_id=flight.id,
            cause_event_id=cancelled_event.event_id,
            trace_id=cancelled_event.trace_id,
        )
        processes.detect_flight_cancellation_impact(self)

    # -- Task 6: flight-disruption-recovery observation ------------------------

    def build_observation(
        self, sensor_event: dict[str, Any], *, now: float | None = None
    ) -> dict[str, Any]:
        """Turn one `sensor:flight_cancellation_impact` `sensor.tripped` event
        into the single flat, JSON-only observation dict that both the pure
        `verticals.travel.recovery.planner.plan_recovery_options` and the
        real Azure Durable Functions
        `verticals.travel.durable.functions.TravelRecoveryDetect` /
        `TravelRecoveryAssessImpact` activities read. `sensor_event` is a
        plain dict (the same `SimulationEvent.to_dict()` shape the world
        bridge already publishes as `FleetEvent.simulation_event`), so this
        method never depends on a live event object -- only JSON-shaped
        data flows onward from here, matching a real Durable orchestrator's
        own no-object-identity replay constraint. `now` lets a caller pin
        the observation's clock reading to a specific moment (e.g. the
        world's own `runtime.now` at sensor-trip time) instead of
        whatever the world's clock reads when this method happens to run;
        defaults to `self.runtime.now` when omitted.

        Deliberately supports exactly one affected booking and party per
        sensor event: every reference disruption in this world's own
        reference data (FLT-ZV204, FLT-ZV102) only ever has one
        paid/confirmed booking against it. Raising here instead of
        silently only recovering the first affected party would otherwise
        hide unrecovered demand -- a genuinely multi-party disruption is
        out of this task's scope.
        """
        payload = sensor_event.get("payload", {})
        disruption_id = payload["disruption_id"]
        flight_id = payload["flight_id"]
        booking_ids = payload["booking_ids"]
        party_ids = payload["party_ids"]
        if len(booking_ids) != 1 or len(party_ids) != 1:
            raise ValueError(
                "build_observation supports exactly one affected booking and party per "
                f"flight_cancellation_impact sensor event; disruption {disruption_id!r} named "
                f"{len(booking_ids)} booking(s) and {len(party_ids)} part(y/ies)"
            )

        booking = self.bookings[booking_ids[0]]
        party = self.parties[party_ids[0]]
        old_flight = self.flights[flight_id]
        hotel = self.hotels[booking.hotel_id]

        candidate_flights = [
            {
                "flight_id": flight.id,
                "supplier_id": flight.supplier_id,
                "destination_id": flight.destination_id,
                "scheduled_departure": flight.scheduled_departure,
                "scheduled_arrival": flight.scheduled_arrival,
                "capacity": flight.capacity,
                "reserved": flight.reserved,
                "status": flight.status,
                "base_fare_gbp": flight.base_fare_gbp,
            }
            for flight in sorted(self.flights.values(), key=lambda flight: flight.id)
            if flight.id != flight_id
            and flight.destination_id == old_flight.destination_id
            and flight.status == "scheduled"
        ]
        candidate_transfers = [
            {
                "transfer_id": transfer.id,
                "flight_id": transfer.flight_id,
                "destination_id": transfer.destination_id,
                "supplier_id": transfer.supplier_id,
                "capacity": transfer.capacity,
                "reserved": transfer.reserved,
                "status": transfer.status,
            }
            for transfer in sorted(self.transfers.values(), key=lambda transfer: transfer.id)
        ]

        return {
            "sensor_id": payload.get("sensor_id", "sensor:flight_cancellation_impact"),
            "trace_id": sensor_event["trace_id"],
            "disruption_id": disruption_id,
            "flight_id": flight_id,
            "booking_id": booking.id,
            "party_id": party.id,
            "party_size": party.size,
            "member_customer_ids": list(party.member_customer_ids),
            "hotel_id": booking.hotel_id,
            "hotel_supplier_id": hotel.supplier_id,
            "allotment_id": booking.allotment_id,
            "old_transfer_id": booking.transfer_id,
            "destination_id": old_flight.destination_id,
            "old_flight": {
                "flight_id": old_flight.id,
                "supplier_id": old_flight.supplier_id,
                "destination_id": old_flight.destination_id,
                "scheduled_departure": old_flight.scheduled_departure,
                "scheduled_arrival": old_flight.scheduled_arrival,
                "capacity": old_flight.capacity,
                "reserved": old_flight.reserved,
            },
            "candidate_flights": candidate_flights,
            "candidate_transfers": candidate_transfers,
            "now": now if now is not None else self.runtime.now,
            "evidence_event_ids": [sensor_event.get("event_id")],
        }

    # -- scene-renderer-ready state -------------------------------------------

    def render_state(self) -> dict[str, Any]:
        def rows(
            mapping: dict[str, Any],
            extra: Callable[[Any], dict[str, Any]] | None = None,
        ) -> list[dict[str, Any]]:
            result = []
            for record in sorted(mapping.values(), key=lambda record: record.id):
                row = _jsonify(dataclasses.asdict(record))
                if extra is not None:
                    row.update(_jsonify(extra(record)))
                result.append(row)
            return result

        # -- Task 8: JSON-safe derived scene fields for the generic spatial
        # world renderer. Every value below is derived from this same
        # authoritative, journal-backed state (real flight/transfer
        # schedule and status, real party/booking location, real hotel
        # allotment occupancy) -- never decorative or random -- so it
        # changes only when the record it is derived from changes.

        # `self.runtime.now` only ever advances to the sim_time of the most
        # recently *processed* event -- anywhere in this shared world, not
        # necessarily this flight's own timeline (`run_until` steps event
        # by event rather than forcing a wall clock) -- so interpolating a
        # single flight's elapsed-journey fraction against it would risk a
        # stale, misleadingly-precise value driven by an unrelated event
        # elsewhere. A real, authoritative, status-derived progress value
        # is used instead, exactly mirroring how transfers (which carry no
        # timing fields at all) are already derived below.
        _FLIGHT_PROGRESS = {"scheduled": 0.0, "departed": 0.5, "arrived": 1.0, "cancelled": 0.0}

        def _flight_extra(flight: Flight) -> dict[str, Any]:
            return {
                "route_location_ids": [flight.origin_airport_id, flight.destination_id],
                "progress": _FLIGHT_PROGRESS.get(flight.status, 0.0),
            }

        def _hotel_for_destination(destination_id: str) -> Hotel | None:
            return next(
                (hotel for hotel in self.hotels.values() if hotel.destination_id == destination_id),
                None,
            )

        _TRANSFER_PROGRESS = {"scheduled": 0.0, "in_progress": 0.5, "completed": 1.0}

        def _transfer_extra(transfer: Transfer) -> dict[str, Any]:
            hotel = _hotel_for_destination(transfer.destination_id)
            return {
                "route_location_ids": [transfer.destination_id, hotel.id if hotel is not None else None],
                "progress": _TRANSFER_PROGRESS.get(transfer.status, 0.0),
            }

        def _party_location(party: TravellingParty | None) -> str | None:
            if party is None:
                return None
            if party.location in self.flights:
                # Airborne: mid-flight is a genuine transient gap between
                # named real-world locations, not an invented position.
                return None
            return party.location

        def _party_extra(party: TravellingParty) -> dict[str, Any]:
            return {"current_location_id": _party_location(party)}

        def _party_for_customer(customer_id: str) -> TravellingParty | None:
            return next(
                (
                    party
                    for party in self.parties.values()
                    if party.lead_customer_id == customer_id
                    or customer_id in party.member_customer_ids
                ),
                None,
            )

        def _customer_extra(customer: Customer) -> dict[str, Any]:
            party = _party_for_customer(customer.id)
            location = _party_location(party) if party is not None else None
            return {"current_location_id": location if location is not None else "home"}

        def _booking_extra(booking: Booking) -> dict[str, Any]:
            return {"current_location_id": _party_location(self.parties.get(booking.party_id))}

        def _disruption_extra(disruption: Disruption) -> dict[str, Any]:
            flight = self.flights.get(disruption.resource_id)
            return {"current_location_id": flight.origin_airport_id if flight is not None else None}

        def _recovery_decision_extra(decision: RecoveryDecision) -> dict[str, Any]:
            command = next(
                (
                    candidate
                    for candidate in self.recovery_commands.values()
                    if candidate.workflow_id == decision.workflow_id
                ),
                None,
            )
            party = self.parties.get(command.party_id) if command is not None else None
            return {"current_location_id": _party_location(party)}

        def _staff_extra(_staff: StaffMember) -> dict[str, Any]:
            # No per-staff-member location is modelled in this world: every
            # staff action (check-in, arrival handling) is issued from the
            # single real operations base, never a travel location.
            return {"current_location_id": "home"}

        def _hotel_extra(hotel: Hotel) -> dict[str, Any]:
            allotment = next(
                (a for a in self.allotments.values() if a.hotel_id == hotel.id),
                None,
            )
            if allotment is None or allotment.allotment <= 0:
                return {"occupancy_ratio": 0.0, "capacity_ratio": 0.0, "occupancy_status": "normal"}
            occupancy_ratio = allotment.occupied / allotment.allotment
            capacity_ratio = allotment.reserved / allotment.allotment
            if occupancy_ratio >= 1.0:
                occupancy_status = "full"
            elif occupancy_ratio >= 0.85:
                occupancy_status = "near_full"
            else:
                occupancy_status = "normal"
            return {
                "occupancy_ratio": occupancy_ratio,
                "capacity_ratio": capacity_ratio,
                "occupancy_status": occupancy_status,
            }

        bookings_paid = sum(1 for booking in self.bookings.values() if booking.status == "paid")
        return {
            "seed": self.seed,
            "sim_time": self.runtime.now,
            "status": self.runtime.status,
            "airports": rows(self.airports),
            "destinations": rows(self.destinations),
            "suppliers": rows(self.suppliers),
            "staff": rows(self.staff, _staff_extra),
            "customers": rows(self.customers, _customer_extra),
            "parties": rows(self.parties, _party_extra),
            "flights": rows(self.flights, _flight_extra),
            "hotels": rows(self.hotels, _hotel_extra),
            "allotments": rows(self.allotments),
            "transfers": rows(self.transfers, _transfer_extra),
            "quotes": rows(self.quotes),
            "bookings": rows(self.bookings, _booking_extra),
            "payments": rows(self.payments),
            "refunds": rows(self.refunds),
            "disruptions": rows(self.disruptions, _disruption_extra),
            "care_actions": rows(self.care_actions),
            "recovery_decisions": rows(self.recovery_decisions, _recovery_decision_extra),
            "recovery_commands": rows(self.recovery_commands),
            "recovery_evaluations": rows(self.recovery_evaluations),
            "summary": {
                "customers": len(self.customers),
                "parties": len(self.parties),
                "flights": len(self.flights),
                "hotels": len(self.hotels),
                "transfers": len(self.transfers),
                "quotes": len(self.quotes),
                "bookings": len(self.bookings),
                "bookings_paid": bookings_paid,
                "payments": len(self.payments),
                "care_actions": len(self.care_actions),
                "recovery_commands": len(self.recovery_commands),
            },
        }
'''
