# src/functions/graphs/__init__.py
"""Per-phase MAF Workflow graph builders. Each returns a Workflow instance ready to
be invoked from the durable orchestration via `await workflow.run(input)`.

POC1 ExpenseClaim 7-phase flow: Intake -> Classify -> Validate Receipt -> Route ->
Notify -> Arbitrate -> Audit.

POC2 Hiring 10-phase flow (spine, stubs to be filled in per-track): Budget ->
Job Design -> Sourcing -> Triage -> Screening -> Voice -> Interview ->
Compliance -> Offer -> Onboarding.
"""
from .intake import build_intake_workflow
from .intake_expense import build_intake_expense_workflow
from .classify import build_classify_workflow
from .receipt import build_receipt_workflow
from .route import build_route_workflow
from .notify import build_notify_workflow
from .arbitrate import build_arbitrate_workflow
from .audit import build_audit_workflow
from .approval import build_approval_workflow

# POC2 hiring spine
from .budget import build_hiring_budget_workflow
from .job_design import build_hiring_job_design_workflow
from .sourcing import build_hiring_sourcing_workflow
from .triage import build_hiring_triage_workflow
from .screening import build_hiring_screening_workflow
from .voice import build_hiring_voice_workflow
from .compliance import build_hiring_compliance_workflow
from .offer import build_hiring_offer_workflow
from .onboarding import build_hiring_onboarding_workflow

# Generated domains (compose-domain v1)
from .fleet_travel_preapproval_employee_lookup import (
    build_fleet_travel_preapproval_employee_lookup_workflow,
)
from .fleet_travel_preapproval_policy_fit_check import (
    build_fleet_travel_preapproval_policy_fit_check_workflow,
)


__all__ = [
    # POC1
    "build_intake_workflow",
    "build_intake_expense_workflow",
    "build_classify_workflow",
    "build_approval_workflow",
    "build_receipt_workflow",
    "build_route_workflow",
    "build_notify_workflow",
    "build_arbitrate_workflow",
    "build_audit_workflow",
    # POC2 hiring spine
    "build_hiring_budget_workflow",
    "build_hiring_job_design_workflow",
    "build_hiring_sourcing_workflow",
    "build_hiring_triage_workflow",
    "build_hiring_screening_workflow",
    "build_hiring_voice_workflow",
    "build_hiring_compliance_workflow",
    "build_hiring_offer_workflow",
    "build_hiring_onboarding_workflow",
]

# Generated by compose-domain v3: fleet-employee-onboarding
from .fleet_employee_onboarding_employee_lookup import (
    build_fleet_employee_onboarding_employee_lookup_workflow,
)
from .fleet_employee_onboarding_access_drafter import (
    build_fleet_employee_onboarding_access_drafter_workflow,
)
from .fleet_employee_onboarding_induction_planner import (
    build_fleet_employee_onboarding_induction_planner_workflow,
)

# Generated by compose-domain v3: fleet-vendor-kyc
from .fleet_vendor_kyc_vendor_intake import build_fleet_vendor_kyc_vendor_intake_workflow
from .fleet_vendor_kyc_kyc_diligence import build_fleet_vendor_kyc_kyc_diligence_workflow
from .fleet_vendor_kyc_ubo_resolver import build_fleet_vendor_kyc_ubo_resolver_workflow

# Generated by compose-domain v3: fleet-it-access-request
from .fleet_it_access_request_employee_lookup import (
    build_fleet_it_access_request_employee_lookup_workflow,
)
from .fleet_it_access_request_rbac_resolver import (
    build_fleet_it_access_request_rbac_resolver_workflow,
)
from .fleet_it_access_request_risk_assessor import (
    build_fleet_it_access_request_risk_assessor_workflow,
)

# Generated by compose-domain v3: fleet-contract-renewal
from .fleet_contract_renewal_contract_lookup import (
    build_fleet_contract_renewal_contract_lookup_workflow,
)
from .fleet_contract_renewal_market_benchmarker import (
    build_fleet_contract_renewal_market_benchmarker_workflow,
)
from .fleet_contract_renewal_renewal_terms_drafter import (
    build_fleet_contract_renewal_renewal_terms_drafter_workflow,
)

# Generated by compose-domain v3: fleet-perf-review
from .fleet_perf_review_employee_lookup import (
    build_fleet_perf_review_employee_lookup_workflow,
)
from .fleet_perf_review_peer_feedback_aggregator import (
    build_fleet_perf_review_peer_feedback_aggregator_workflow,
)
from .fleet_perf_review_calibration_drafter import (
    build_fleet_perf_review_calibration_drafter_workflow,
)
