# src/functions/graphs/__init__.py
"""Per-phase MAF Workflow graph builders. Each returns a Workflow instance ready to
be invoked from the durable orchestration via `await workflow.run(input)`.

POC1 ExpenseClaim 7-phase flow: Intake -> Classify -> Validate Receipt -> Route ->
Notify -> Arbitrate -> Audit.

POC2 Hiring 10-phase flow (spine, stubs to be filled in per-track): Budget ->
Job Design -> Sourcing -> Triage -> Screening -> Voice -> Interview ->
Compliance -> Offer -> Onboarding.
"""
from .intake import build_intake_workflow
from .intake_expense import build_intake_expense_workflow
from .classify import build_classify_workflow
from .receipt import build_receipt_workflow
from .route import build_route_workflow
from .notify import build_notify_workflow
from .arbitrate import build_arbitrate_workflow
from .audit import build_audit_workflow
from .approval import build_approval_workflow

# POC2 hiring spine
from .budget import build_hiring_budget_workflow
from .job_design import build_hiring_job_design_workflow
from .sourcing import build_hiring_sourcing_workflow
from .triage import build_hiring_triage_workflow
from .screening import build_hiring_screening_workflow
from .voice import build_hiring_voice_workflow
from .compliance import build_hiring_compliance_workflow
from .offer import build_hiring_offer_workflow
from .onboarding import build_hiring_onboarding_workflow

# Generated domains (compose-domain v1)
from .fleet_travel_preapproval_employee_lookup import (
    build_fleet_travel_preapproval_employee_lookup_workflow,
)
from .fleet_travel_preapproval_policy_fit_check import (
    build_fleet_travel_preapproval_policy_fit_check_workflow,
)


__all__ = [
    # POC1
    "build_intake_workflow",
    "build_intake_expense_workflow",
    "build_classify_workflow",
    "build_approval_workflow",
    "build_receipt_workflow",
    "build_route_workflow",
    "build_notify_workflow",
    "build_arbitrate_workflow",
    "build_audit_workflow",
    # POC2 hiring spine
    "build_hiring_budget_workflow",
    "build_hiring_job_design_workflow",
    "build_hiring_sourcing_workflow",
    "build_hiring_triage_workflow",
    "build_hiring_screening_workflow",
    "build_hiring_voice_workflow",
    "build_hiring_compliance_workflow",
    "build_hiring_offer_workflow",
    "build_hiring_onboarding_workflow",
]

# Generated by compose-domain v3: fleet-employee-onboarding
from .fleet_employee_onboarding_employee_lookup import (
    build_fleet_employee_onboarding_employee_lookup_workflow,
)
from .fleet_employee_onboarding_access_drafter import (
    build_fleet_employee_onboarding_access_drafter_workflow,
)
from .fleet_employee_onboarding_induction_planner import (
    build_fleet_employee_onboarding_induction_planner_workflow,
)

# Generated by compose-domain v3: fleet-vendor-kyc
from .fleet_vendor_kyc_vendor_intake import build_fleet_vendor_kyc_vendor_intake_workflow
from .fleet_vendor_kyc_kyc_diligence import build_fleet_vendor_kyc_kyc_diligence_workflow
from .fleet_vendor_kyc_ubo_resolver import build_fleet_vendor_kyc_ubo_resolver_workflow
from .proactive_customer_care_entitlement import (
    build_proactive_customer_care_entitlement_workflow,
)
from .proactive_customer_care_execution import (
    build_proactive_customer_care_execution_workflow,
)

# Generated by compose-domain v3: fleet-it-access-request
from .fleet_it_access_request_employee_lookup import (
    build_fleet_it_access_request_employee_lookup_workflow,
)
from .fleet_it_access_request_rbac_resolver import (
    build_fleet_it_access_request_rbac_resolver_workflow,
)
from .fleet_it_access_request_risk_assessor import (
    build_fleet_it_access_request_risk_assessor_workflow,
)

# Generated by compose-domain v3: fleet-contract-renewal
from .fleet_contract_renewal_contract_lookup import (
    build_fleet_contract_renewal_contract_lookup_workflow,
)
from .fleet_contract_renewal_market_benchmarker import (
    build_fleet_contract_renewal_market_benchmarker_workflow,
)
from .fleet_contract_renewal_renewal_terms_drafter import (
    build_fleet_contract_renewal_renewal_terms_drafter_workflow,
)

# Generated by compose-domain v3: fleet-perf-review
from .fleet_perf_review_employee_lookup import (
    build_fleet_perf_review_employee_lookup_workflow,
)
from .fleet_perf_review_peer_feedback_aggregator import (
    build_fleet_perf_review_peer_feedback_aggregator_workflow,
)
from .fleet_perf_review_calibration_drafter import (
    build_fleet_perf_review_calibration_drafter_workflow,
)

# Generated by hand (curve proof): fleet-ap-invoice
from .fleet_ap_invoice_invoice_lookup import (
    build_fleet_ap_invoice_invoice_lookup_workflow,
)
from .fleet_ap_invoice_three_way_match import (
    build_fleet_ap_invoice_three_way_match_workflow,
)

# Hand-graduated wave 2: purchase-order
from .fleet_purchase_order_po_lookup import (
    build_fleet_purchase_order_po_lookup_workflow,
)
from .fleet_purchase_order_supplier_check import (
    build_fleet_purchase_order_supplier_check_workflow,
)
from .fleet_purchase_order_authority_resolve import (
    build_fleet_purchase_order_authority_resolve_workflow,
)

# Hand-graduated wave 2: contract-review
from .fleet_contract_review_contract_intake import (
    build_fleet_contract_review_contract_intake_workflow,
)
from .fleet_contract_review_risk_classify import (
    build_fleet_contract_review_risk_classify_workflow,
)
from .fleet_contract_review_authority_resolve import (
    build_fleet_contract_review_authority_resolve_workflow,
)

# Hand-graduated wave 2: privacy-dpia
from .fleet_privacy_dpia_dpia_intake import (
    build_fleet_privacy_dpia_dpia_intake_workflow,
)
from .fleet_privacy_dpia_risk_classify import (
    build_fleet_privacy_dpia_risk_classify_workflow,
)
from .fleet_privacy_dpia_authority_resolve import (
    build_fleet_privacy_dpia_authority_resolve_workflow,
)

# Hand-graduated wave 2: treasury-fx
from .fleet_treasury_fx_op_lookup import (
    build_fleet_treasury_fx_op_lookup_workflow,
)
from .fleet_treasury_fx_position_check import (
    build_fleet_treasury_fx_position_check_workflow,
)
from .fleet_treasury_fx_authority_resolve import (
    build_fleet_treasury_fx_authority_resolve_workflow,
)

# POC3: creative-campaign (5 agentic phase graphs; HITL phases are pure
# orchestrator yields — no graph needed). Real per-phase skills land in
# Phase 4 of plan/feature-poc3-ai-agency-1.md; v1 ships against the
# shared agent_creative_stub + validate_creative_stub pair.
from .creative_brief_synthesis import build_creative_brief_synthesis_workflow
from .creative_insight_audience import build_creative_insight_audience_workflow
from .creative_concept_fanout import build_creative_concept_fanout_workflow
from .creative_storyboard_render import build_creative_storyboard_render_workflow
from .creative_package_handoff import build_creative_package_handoff_workflow

# Generated by compose-domain v4: fleet-employee-transfer
from .fleet_employee_transfer_transfer_intake import build_fleet_employee_transfer_transfer_intake_workflow
from .fleet_employee_transfer_employee_lookup import build_fleet_employee_transfer_employee_lookup_workflow
from .fleet_employee_transfer_identity_migration import build_fleet_employee_transfer_identity_migration_workflow

# Generated by compose-domain v4: fleet-training-request
from .fleet_training_request_request_intake import build_fleet_training_request_request_intake_workflow
from .fleet_training_request_book import build_fleet_training_request_book_workflow
