"""api/shared/domains.py — Domain registry: single source of truth.

Every per-domain integration fact (workflow_type, prefix, orchestrator name,
HITL gates, persona, external_event, operator surface, optional wake hints)
lives in `DOMAINS` keyed by workflow_type. Adding a 9th domain via
`compose-domain` becomes one entry here.

Consumers:
- api.server.services.simulator_orchestrator — spawner dispatch
- api.server.services.blueprint_inventory   — visual mind-map composition
- api.server.routes.workflows               — workflow_id-prefix → workflow_type
- api.server.routes.exceptions              — current_phase → external_event fallback
- api.server.services.triage                — wake-event allow-list extension
- api.server.services.fleet_manager_service — domain catalogue inside FM skill
- api.shared.functions — derives Domain.function back-ref at import; orphan validator runs at boot.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

PhaseKind = Literal["deterministic", "agent", "hitl"]


@dataclass(frozen=True)
class Phase:
    """A workflow phase — used for documentation + FM skill text generation.

    `name` matches the human-readable step name fired via `step.started`
    by `_run_workflow` in api/functions/workflows/activities.py. HITL
    phases that are pure orchestrator yields (no activity wrapper) carry
    the snake_case gate name to match the suspended-payload `phase` field.
    """
    name: str
    kind: PhaseKind


@dataclass(frozen=True)
class HitlGate:
    """A HITL suspend point on a domain's workflow.

    The orchestrator stamps `phase` (snake_case for fleet domains, mixed
    for POC1/POC2) on every suspended payload; the responder + resolve
    route use that key to find the matching `external_event`. The
    `persona` matches a SKILL.md role under api/server/personae/.
    """
    gate_phase: str
    external_event: str
    persona: str


@dataclass(frozen=True)
class WakeHint:
    """Domain-specific event the FM should treat as wake-worthy.

    These are anticipatory signals (e.g. POC1's `claim.routed.red`) the
    FM should react to before a HITL gate trips. Declared per domain in
    the registry; only fires when the domain's activities/validators
    actually emit the event.
    """
    event: str
    reason: str


@dataclass
class Domain:
    workflow_type: str
    display_name: str
    workflow_id_prefix: str
    orchestrator_name: str
    operator_surface: str
    phases: tuple[Phase, ...]
    hitl_gates: tuple[HitlGate, ...]
    skills: tuple[str, ...]
    wake_hints: tuple[WakeHint, ...] = ()
    # `function` is mutated exactly once at import time by
    # api.shared.functions._wire_function_back_refs(); treat as
    # immutable thereafter. The dataclass is non-frozen *only* to
    # accommodate this single boot-time back-ref write.
    function: str | None = None
    # Phase 4 IP5+6 (TASK-027/028). When True, this Domain is a stub
    # for a meta-workflow / strategic CEO domain whose orchestrator is
    # codegen'd from a brief at docs/superpowers/specs/<wt>-brief.yaml
    # but is NOT yet registered in function_app.py. The orphan
    # validator and FM-skill catalog still see the entry; orchestrator-
    # name resolution tests skip it.
    stub: bool = False


# --------------------------------------------------------------------------
# The registry. Entries grouped by graduation order (POC1 expense first,
# POC2 hiring second, then the six fleet-* domains generated by
# compose-domain v3 over the 2026-05 weekend).
# --------------------------------------------------------------------------

DOMAINS: dict[str, Domain] = {
    # ----- POC1 -----
    "expense-claim": Domain(
        workflow_type="expense-claim",
        display_name="Finance Compliance",
        workflow_id_prefix="EXP",
        orchestrator_name="ExpenseClaimOrchestrator",
        operator_surface="finance-controller",
        phases=(
            Phase("Intake", "deterministic"),
            Phase("Classify", "agent"),
            Phase("Validate Receipt", "agent"),
            Phase("Route", "agent"),
            Phase("Notify", "hitl"),
            Phase("Arbitrate", "hitl"),
            Phase("Audit", "agent"),
        ),
        hitl_gates=(
            HitlGate("Notify", "justification", "claim_submitter"),
            HitlGate("Arbitrate", "reviewer_decision", "ssc_reviewer"),
        ),
        skills=(
            "field-extractor", "line-item-extractor", "rag-classifier",
            "receipt-validator", "escalation-advisor", "notification-composer",
            "arbitration", "anomaly-flagger", "exception-classifier",
            "resolution-recommender", "root-cause-explainer", "audit-summariser",
            "use-document-intelligence",
        ),
        wake_hints=(
            WakeHint("claim.routed.red", "Red verdict before HITL gate trips"),
        ),
    ),
    # ----- POC2 -----
    "hiring": Domain(
        workflow_type="hiring",
        display_name="Hiring",
        workflow_id_prefix="HIRE",
        orchestrator_name="HiringOrchestrator",
        operator_surface="hr-bp",
        phases=(
            Phase("Budget", "hitl"),
            Phase("Job Design", "agent"),
            Phase("Sourcing", "agent"),
            Phase("Triage", "agent"),
            Phase("Screening", "agent"),
            Phase("Voice", "hitl"),
            Phase("Interview", "hitl"),
            Phase("Compliance", "agent"),
            Phase("Offer", "hitl"),
            Phase("Onboarding", "agent"),
        ),
        hitl_gates=(
            HitlGate("Budget", "budget_approval", "finance_bp"),
            HitlGate("Voice", "voice_complete", "candidate"),
            HitlGate("Interview", "interview_invite", "recruiter"),
            HitlGate("Offer", "offer_approval", "candidate"),
        ),
        skills=(
            "budget-checker", "jd-drafter", "sourcing-orchestrator",
            "cv-crystalliser", "auto-shortlister", "voice-screener",
            "interview-recommender", "interview-coordinator",
            "jurisdiction-router", "betrvg-checker", "offer-personaliser",
            "exception-classifier", "use-document-intelligence",
        ),
    ),
    # ----- Weekend fleet-* domains (compose-domain v3) -----
    "travel-preapproval": Domain(
        workflow_type="travel-preapproval",
        display_name="Travel pre-approval",
        workflow_id_prefix="TRV",
        orchestrator_name="FleetTravelPreapprovalOrchestrator",
        operator_surface="line-manager",
        phases=(
            Phase("Employee Lookup", "deterministic"),
            Phase("Policy Fit Check", "agent"),
            Phase("manager_approval", "hitl"),
        ),
        hitl_gates=(
            HitlGate("manager_approval", "manager_approval_decision", "line_manager"),
        ),
        skills=(
            "fleet-travel-preapproval-policy-fit-checker",
        ),
        wake_hints=(
            WakeHint("travel.policy.exception", "Trip outside policy band before approval"),
        ),
    ),
    "vendor-kyc": Domain(
        workflow_type="vendor-kyc",
        display_name="Vendor onboarding & KYC",
        workflow_id_prefix="VKY",
        orchestrator_name="FleetVendorKycOrchestrator",
        operator_surface="finance-bp",
        phases=(
            Phase("Vendor Intake", "deterministic"),
            Phase("KYC Diligence", "agent"),
            Phase("UBO Resolver", "agent"),
            Phase("finance_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("finance_signoff", "finance_signoff_decision", "vendor_kyc_finance_bp"),
        ),
        skills=(
            "fleet-vendor-kyc-kyc-diligence-checker",
            "fleet-vendor-kyc-ubo-resolver",
        ),
        wake_hints=(
            WakeHint("vendor.kyc.high_risk", "Vendor in high-risk jurisdiction or sanctions hit"),
        ),
    ),
    "employee-onboarding": Domain(
        workflow_type="employee-onboarding",
        display_name="Employee onboarding",
        workflow_id_prefix="ONB",
        orchestrator_name="FleetEmployeeOnboardingOrchestrator",
        operator_surface="it-admin",
        phases=(
            Phase("Employee Lookup", "deterministic"),
            Phase("Access Drafter", "agent"),
            Phase("it_admin_approval", "hitl"),
            Phase("Induction Planner", "agent"),
        ),
        hitl_gates=(
            HitlGate("it_admin_approval", "it_admin_approval_decision", "onboarding_it_admin"),
        ),
        skills=(
            "fleet-employee-onboarding-access-drafter",
            "fleet-employee-onboarding-induction-planner",
        ),
        wake_hints=(
            WakeHint("onboarding.access.broad_scope", "Joiner requesting broad access scope"),
        ),
    ),
    "it-access-request": Domain(
        workflow_type="it-access-request",
        display_name="IT access request",
        workflow_id_prefix="ITAR",
        orchestrator_name="FleetItAccessRequestOrchestrator",
        operator_surface="it-admin",
        phases=(
            Phase("Employee Lookup", "deterministic"),
            Phase("RBAC Resolver", "agent"),
            Phase("Risk Assessor", "agent"),
            Phase("line_manager_approval", "hitl"),
            Phase("it_admin_approval", "hitl"),
        ),
        hitl_gates=(
            HitlGate("line_manager_approval", "line_manager_approval_decision",
                     "it_access_line_manager"),
            HitlGate("it_admin_approval", "it_admin_approval_decision",
                     "it_access_it_admin"),
        ),
        skills=(
            "fleet-it-access-request-rbac-resolver",
            "fleet-it-access-request-access-risk-assessor",
        ),
        wake_hints=(
            WakeHint("access.scope.privileged", "Privileged-tier role template requested"),
        ),
    ),
    "contract-renewal": Domain(
        workflow_type="contract-renewal",
        display_name="Contract renewal",
        workflow_id_prefix="CRN",
        orchestrator_name="FleetContractRenewalOrchestrator",
        operator_surface="finance-bp",
        phases=(
            Phase("Contract Lookup", "deterministic"),
            Phase("Market Benchmarker", "agent"),
            Phase("Renewal Terms Drafter", "agent"),
            Phase("finance_signoff", "hitl"),
            Phase("contract_owner_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("finance_signoff", "finance_signoff_decision", "contract_finance_bp"),
            HitlGate("contract_owner_signoff", "contract_owner_signoff_decision",
                     "contract_line_manager"),
        ),
        skills=(
            "fleet-contract-renewal-market-benchmarker",
            "fleet-contract-renewal-renewal-terms-drafter",
        ),
        wake_hints=(
            WakeHint("contract.renewal.price_jump", "Proposed value >25% above current"),
        ),
    ),
    "perf-review": Domain(
        workflow_type="perf-review",
        display_name="Performance review",
        workflow_id_prefix="PRR",
        orchestrator_name="FleetPerfReviewOrchestrator",
        operator_surface="hr-bp",
        phases=(
            Phase("Employee Lookup", "deterministic"),
            Phase("Peer Feedback Aggregator", "agent"),
            Phase("Calibration Drafter", "agent"),
            Phase("hr_calibration", "hitl"),
            Phase("line_manager_delivery", "hitl"),
        ),
        hitl_gates=(
            HitlGate("hr_calibration", "hr_calibration_decision", "perf_review_hr_bp"),
            HitlGate("line_manager_delivery", "line_manager_delivery_decision",
                     "perf_review_line_manager"),
        ),
        skills=(
            "fleet-perf-review-peer-feedback-aggregator",
            "fleet-perf-review-calibration-drafter",
        ),
        wake_hints=(
            WakeHint("perf.calibration.outlier", "Calibration draft is a >2-band outlier"),
        ),
    ),
    # ----- Hand-graduated: AP invoice (9th live domain) -----
    # Proves the curve: once the substrate primitives (authority MCP +
    # persona registry + compose-persona) are in place, the next domain
    # reuses them without per-persona engineering. ap_clerk + controller
    # personae are unchanged from Phase 6 graduation — they decide gates
    # against AP-001..AP-004 in the matrix.
    "ap-invoice": Domain(
        workflow_type="ap-invoice",
        display_name="AP invoice",
        workflow_id_prefix="API",
        orchestrator_name="FleetApInvoiceOrchestrator",
        operator_surface="ap-clerk",
        phases=(
            Phase("Invoice Lookup", "deterministic"),
            Phase("Three-Way Match", "deterministic"),
            Phase("ap_clerk_signoff", "hitl"),
            Phase("controller_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("ap_clerk_signoff", "ap_invoice_processing_decision", "ap_clerk"),
            HitlGate("controller_signoff", "controller_signoff_decision", "controller"),
        ),
        skills=(
            # Deterministic phases — no agent skills today.
            # Engagement-POC graduation adds a real LLM-driven line-item validator.
        ),
        wake_hints=(
            WakeHint("invoice.three_way_match.failed", "Invoice failed three-way match"),
            WakeHint("invoice.value.controller_band", "Invoice >£25k routed to controller"),
        ),
    ),

    # ----- Hand-graduated wave 2 (10th–13th live domains) -----
    # All four use a 4-phase pattern:
    #   Phase 1 deterministic lookup -> Phase 2 deterministic check ->
    #   Phase 3 Authority Resolve (calls matrix MCP, picks approver_role
    #   dynamically) -> Phase 4 HITL approver_signoff. The HitlGate
    #   persona below is the *most-likely* / lowest-band approver; the
    #   actual responder uses the resolved approver_role from the
    #   suspended payload's persona field, so any of the matrix-routed
    #   roles can take the gate.
    "purchase-order": Domain(
        workflow_type="purchase-order",
        display_name="Purchase Order",
        workflow_id_prefix="POW",
        orchestrator_name="FleetPurchaseOrderOrchestrator",
        operator_surface="procurement",
        phases=(
            Phase("PO Lookup", "deterministic"),
            Phase("Supplier Check", "deterministic"),
            Phase("Authority Resolve", "deterministic"),
            Phase("approver_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("approver_signoff", "purchase_order_approval_decision", "line_manager"),
        ),
        skills=(),
        wake_hints=(
            WakeHint("po.supplier.unapproved", "PO supplier not on approved list"),
            WakeHint("po.value.cpo_band", "PO >£500k routed to CPO"),
        ),
    ),
    "contract-review": Domain(
        workflow_type="contract-review",
        display_name="Contract Review",
        workflow_id_prefix="CRW",
        orchestrator_name="FleetContractReviewOrchestrator",
        operator_surface="legal",
        phases=(
            Phase("Contract Intake", "deterministic"),
            Phase("Risk Classify", "deterministic"),
            Phase("Authority Resolve", "deterministic"),
            Phase("approver_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("approver_signoff", "contract_review_signoff_decision", "contracts_counsel"),
        ),
        skills=(),
        wake_hints=(
            WakeHint("contract.template.deviation", "Contract deviates from template"),
            WakeHint("contract.value.material", "Contract MSA >£250k routed to GC"),
        ),
    ),
    "privacy-dpia": Domain(
        workflow_type="privacy-dpia",
        display_name="Privacy DPIA",
        workflow_id_prefix="DPI",
        orchestrator_name="FleetPrivacyDpiaOrchestrator",
        operator_surface="privacy",
        phases=(
            Phase("DPIA Intake", "deterministic"),
            Phase("Risk Classify", "deterministic"),
            Phase("Authority Resolve", "deterministic"),
            Phase("approver_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("approver_signoff", "dpia_signoff_decision", "dpo"),
        ),
        skills=(),
        wake_hints=(
            WakeHint("dpia.risk.high", "DPIA flagged as high-risk processing"),
            WakeHint("dpia.gdpr.art_35", "EMEA high-risk DPIA — GDPR Art. 35 trigger"),
        ),
    ),
    "treasury-fx": Domain(
        workflow_type="treasury-fx",
        display_name="Treasury FX",
        workflow_id_prefix="TFX",
        orchestrator_name="FleetTreasuryFxOrchestrator",
        operator_surface="treasury",
        phases=(
            Phase("Op Lookup", "deterministic"),
            Phase("Position Check", "deterministic"),
            Phase("Authority Resolve", "deterministic"),
            Phase("approver_signoff", "hitl"),
        ),
        hitl_gates=(
            HitlGate("approver_signoff", "treasury_signoff_decision", "treasurer"),
        ),
        skills=(),
        wake_hints=(
            WakeHint("fx.position.over_limit", "FX op exceeds per-pair trading limit"),
            WakeHint("fx.value.cfo_band", "FX op >£1M routed to CFO"),
        ),
    ),

    # ----- POC3 — Creative Campaign (AI-Agency demo) -----
    # Per plan/feature-poc3-ai-agency-1.md. The four storyboard-defined HITL
    # gates (◆1 brief approval, ◆2 concept lock, ◆3 storyboard approval,
    # ◆4 final signoff) plus the Phase-1 voice intake (parks waiting for the
    # creative director to complete the multi-party briefing call) are all
    # five entries below. Phase 1 ships every phase as a stub against canned
    # image fixtures under data/synthetic/creative-campaign/cached/; Phases
    # 2–4 swap stubs for real Foundry gpt-image-2 + brand-RAG.
    "creative-campaign": Domain(
        workflow_type="creative-campaign",
        display_name="Creative Campaign",
        workflow_id_prefix="CMP",
        orchestrator_name="CreativeCampaignOrchestrator",
        operator_surface="producer-queue",
        phases=(
            Phase("brief_capture", "hitl"),
            Phase("Brief Synthesis", "agent"),
            Phase("brief_approval", "hitl"),
            Phase("Insight & Audience", "agent"),
            Phase("Concept Fan-out", "agent"),
            Phase("concept_lock", "hitl"),
            Phase("Storyboard Render", "agent"),
            Phase("storyboard_approval", "hitl"),
            Phase("final_signoff", "hitl"),
            Phase("Package & Handoff", "agent"),
        ),
        hitl_gates=(
            HitlGate("brief_capture", "voice_complete", "creative_director"),
            HitlGate("brief_approval", "brief_approval_decision", "creative_director"),
            HitlGate("concept_lock", "concept_lock_decision", "creative_director"),
            HitlGate("storyboard_approval", "storyboard_approval_decision",
                     "creative_director"),
            HitlGate("final_signoff", "final_signoff_decision", "creative_director"),
        ),
        skills=(
            "creative-briefer",
            "brief-synthesiser",
            "concept-curator",
            "brand-guardian",
            "storyboard-curator",
        ),
        wake_hints=(
            WakeHint("creative.content_safety.rejected",
                     "gpt-image-2 RAI filter rejected a render"),
            WakeHint("creative.brand.distinctiveness_low",
                     "Concept route scored below distinctiveness threshold"),
        ),
    ),
    # --------------------------------------------------------------
    # Phase 4 IP5+6 — meta-workflow + CEO strategic stubs (TASK-027,
    # TASK-028). These are graduated via compose-domain v4 from briefs
    # under docs/superpowers/specs/. Their orchestrators live as
    # rendered-string codegen output (validated by ast.parse, NOT
    # written to api/functions/workflows/ in this phase). The stubs
    # below exist purely to satisfy the orphan validator in
    # api.shared.functions: every domain a function claims must be in
    # DOMAINS, and every domain in DOMAINS must be claimed.
    # --------------------------------------------------------------
    "hire-to-productive": Domain(
        workflow_type="hire-to-productive",
        display_name="Hire to Productive",
        workflow_id_prefix="H2P",
        orchestrator_name="HireToProductiveOrchestrator",
        operator_surface="hr-bp",
        phases=(),
        hitl_gates=(HitlGate("manager_signoff", "manager_onboarding_plan_decision",
                             "hr_bp"),),
        skills=(),
        stub=True,
    ),
    "vendor-risk-to-pay": Domain(
        workflow_type="vendor-risk-to-pay",
        display_name="Vendor Risk to Pay",
        workflow_id_prefix="VRP",
        orchestrator_name="VendorRiskToPayOrchestrator",
        operator_surface="finance-controller",
        phases=(),
        hitl_gates=(HitlGate("payment_release", "payment_release_decision", "cfo"),),
        skills=(),
        stub=True,
    ),
    "lead-to-cash": Domain(
        workflow_type="lead-to-cash",
        display_name="Lead to Cash",
        workflow_id_prefix="L2C",
        orchestrator_name="LeadToCashOrchestrator",
        operator_surface="account-director",
        phases=(),
        hitl_gates=(HitlGate("revenue_recognition", "revenue_recognition_decision",
                             "account_director"),),
        skills=(),
        stub=True,
    ),
    "fy-close": Domain(
        workflow_type="fy-close",
        display_name="Fiscal-Year Close",
        workflow_id_prefix="FYC",
        orchestrator_name="FyCloseOrchestrator",
        operator_surface="ceo",
        phases=(),
        hitl_gates=(HitlGate("ceo_signoff", "fy_close_decision", "cfo"),),
        skills=(),
        stub=True,
    ),
    "board-prep": Domain(
        workflow_type="board-prep",
        display_name="Board Pack Preparation",
        workflow_id_prefix="BRD",
        orchestrator_name="BoardPrepOrchestrator",
        operator_surface="ceo",
        phases=(),
        hitl_gates=(HitlGate("board_signoff", "board_pack_decision", "cfo"),),
        skills=(),
        stub=True,
    ),
}


# --------------------------------------------------------------------------
# Lookup helpers — keep call sites readable.
# --------------------------------------------------------------------------


def get(workflow_type: str) -> Domain | None:
    """Return the registered Domain for a workflow_type, or None."""
    return DOMAINS.get(workflow_type)


def by_prefix(workflow_id: str) -> Domain | None:
    """Resolve a workflow_id (e.g. 'VKY-0007') to its Domain via prefix.

    Used by api/server/routes/workflows.py to synthesise minimal records
    when a fleet workflow isn't in the store. (Phase 2 of the plan
    upserts every workflow into the store, so this falls back to a no-op
    in steady state.)
    """
    prefix = workflow_id.split("-", 1)[0] if "-" in workflow_id else workflow_id
    for d in DOMAINS.values():
        if d.workflow_id_prefix == prefix:
            return d
    return None


def resolve_external_event(workflow_type: str, current_phase: str) -> str | None:
    """Map (workflow_type, current_phase) to the Durable external event name.

    Cold-cache fallback for the resolve route when the in-memory
    pending-gate cache has been cleared (e.g. FastAPI restart between
    suspend and operator click). Matches HitlGate.gate_phase exactly,
    case-insensitive, with underscore/space normalisation so
    "Manager Approval" and "manager_approval" both resolve.
    """
    domain = DOMAINS.get(workflow_type)
    if not domain:
        return None
    norm = current_phase.lower().replace(" ", "_")
    for gate in domain.hitl_gates:
        if gate.gate_phase.lower().replace(" ", "_") == norm:
            return gate.external_event
    return None


def all_wake_hints() -> set[str]:
    """Union of every domain's wake-hint event names.

    Triage layer (api/server/services/triage.py) uses this to extend
    `WAKE_TYPES` so per-domain anticipatory events wake the FM without
    each domain needing to edit api/shared/events.py.
    """
    out: set[str] = set()
    for d in DOMAINS.values():
        for wh in d.wake_hints:
            out.add(wh.event)
    return out


def all_personae() -> set[str]:
    """Set of every persona role referenced by any HITL gate.

    Used by the registry validation test to assert every persona has a
    SKILL.md under api/server/personae/.
    """
    out: set[str] = set()
    for d in DOMAINS.values():
        for g in d.hitl_gates:
            out.add(g.persona)
    return out
