// Auto-generated by compose-domain v4 author-decision-mapping codegen.
// Workflow: employee-transfer
// Phase:    hr_director_signoff
// Persona:  hr_director
//
// Bind params:
//   $entity_id  — entity id the current workflow's persona is reasoning about
//   $limit      — max precedents to return (caller chooses)
MATCH (d:Decision)-[:DECIDED_ON]->(e {id: $entity_id})
WHERE d.persona_role = 'hr_director'
  AND d.workflow_type = 'employee-transfer'
RETURN d
ORDER BY d.decided_at DESC
LIMIT $limit
