"""Travel: real deterministic query/mutation-planning MCP operations
(generated by verticals.travel.generator.mcp_templates).

Every tool below reads `TravelWorld` state (or computes a feasibility
plan for a proposed command) without ever mutating it: the sole
authoritative, journal-backed mutation path for the eight processes is
`verticals.travel.actions.commands.COMMAND_HANDLERS`. No tool here calls
out to a network or external system -- every result is a pure function
of the `TravelWorld` snapshot passed to (or freshly built by) it.

Do not hand-edit -- change verticals.travel.generator.mcp_templates and
regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from collections.abc import Callable
from typing import Any

from copilot.tools import define_tool
from pydantic import BaseModel

from verticals.travel.worlds.scenario import TravelWorld

# A fresh, deterministic (seed=42) reference world, built lazily and
# reused for every tool call that is not explicitly bound to its own
# world instance. Deterministic and side-effect-free: every call reads
# the same actor layout `worlds/reference_data.py` seeds.
_DEFAULT_SEED = 42
_default_world: TravelWorld | None = None


def _reference_world() -> TravelWorld:
    global _default_world
    if _default_world is None:
        _default_world = TravelWorld(seed=_DEFAULT_SEED)
    return _default_world


# ---------------------------------------------------------------------------
# 1. holiday-sales-booking
# ---------------------------------------------------------------------------


class CheckQuoteOfferParams(BaseModel):
    quote_id: str


def check_quote_offer(world: TravelWorld, quote_id: str) -> dict[str, Any]:
    """Query: a quote's current offer state (mirrors
    `confirm_package_booking`'s own quote checks)."""
    quote = world.quotes.get(quote_id)
    if quote is None:
        return {"found": False, "quote_id": quote_id, "reason": "unknown quote"}
    return {
        "found": True,
        "quote_id": quote.id,
        "status": quote.status,
        "price": quote.price,
        "party_id": quote.party_id,
        "customer_id": quote.customer_id,
        "adviser_id": quote.adviser_id,
        "ready_to_confirm": quote.status == "offered" and quote.price is not None,
    }


@define_tool(
    name="travel_operations_check_quote_offer",
    description=(
        "Check a holiday quote's current offer state (status, price, "
        "party) and whether it is ready to be confirmed into a booking."
    ),
)
def check_quote_offer_tool(params: CheckQuoteOfferParams) -> dict[str, Any]:
    return check_quote_offer(_reference_world(), params.quote_id)


class ReservePackageCapacityParams(BaseModel):
    flight_id: str
    allotment_id: str
    transfer_id: str
    party_size: int
    rooms: int


def reserve_package_capacity(
    world: TravelWorld,
    *,
    flight_id: str,
    allotment_id: str,
    transfer_id: str,
    party_size: int,
    rooms: int,
) -> dict[str, Any]:
    """Planning: would a party of `party_size` and `rooms` rooms fit this
    flight/allotment/transfer? Mirrors `confirm_package_booking`'s own
    three capacity checks exactly, without reserving anything."""
    flight = world.flights.get(flight_id)
    allotment = world.allotments.get(allotment_id)
    transfer = world.transfers.get(transfer_id)
    if flight is None or allotment is None or transfer is None:
        return {"feasible": False, "reason": "unknown flight, allotment or transfer"}
    flight_ok = flight.reserved + party_size <= flight.capacity
    allotment_ok = allotment.reserved + rooms <= allotment.allotment
    transfer_ok = transfer.reserved + party_size <= transfer.capacity
    feasible = flight_ok and allotment_ok and transfer_ok
    return {
        "feasible": feasible,
        "flight_capacity_ok": flight_ok,
        "allotment_capacity_ok": allotment_ok,
        "transfer_capacity_ok": transfer_ok,
        "flight_headroom": flight.capacity - flight.reserved,
        "allotment_headroom": allotment.allotment - allotment.reserved,
        "transfer_headroom": transfer.capacity - transfer.reserved,
    }


@define_tool(
    name="travel_operations_reserve_package_capacity",
    description=(
        "Plan (without committing) whether a party and room count would "
        "fit a flight, hotel allotment and transfer's remaining capacity."
    ),
)
def reserve_package_capacity_tool(params: ReservePackageCapacityParams) -> dict[str, Any]:
    return reserve_package_capacity(
        _reference_world(),
        flight_id=params.flight_id,
        allotment_id=params.allotment_id,
        transfer_id=params.transfer_id,
        party_size=params.party_size,
        rooms=params.rooms,
    )


# ---------------------------------------------------------------------------
# 2 / 4. capacity-yield-management + hotel-supplier-recovery (hero)
# ---------------------------------------------------------------------------


class CheckAllotmentHeadroomParams(BaseModel):
    allotment_id: str


def check_allotment_headroom(world: TravelWorld, allotment_id: str) -> dict[str, Any]:
    """Query: an allotment's donor headroom (`allotment - reserved`) and
    recipient headroom (`total - allotment`) -- the same two formulas
    `adjust_package_allotment` / `move_hotel_allotment` check before
    moving rooms."""
    allotment = world.allotments.get(allotment_id)
    if allotment is None:
        return {"found": False, "allotment_id": allotment_id, "reason": "unknown allotment"}
    conserved = 0 <= allotment.occupied <= allotment.reserved <= allotment.allotment <= allotment.total
    utilisation_pct = (
        round(100.0 * allotment.reserved / allotment.allotment, 2) if allotment.allotment else 0.0
    )
    return {
        "found": True,
        "allotment_id": allotment.id,
        "total": allotment.total,
        "allotment": allotment.allotment,
        "reserved": allotment.reserved,
        "occupied": allotment.occupied,
        "donor_headroom": allotment.allotment - allotment.reserved,
        "recipient_headroom": allotment.total - allotment.allotment,
        "utilisation_pct": utilisation_pct,
        "conservation_holds": conserved,
    }


@define_tool(
    name="travel_operations_check_allotment_headroom",
    description=(
        "Check a hotel room allotment's donor headroom (spare contracted "
        "rooms it could give away) and recipient headroom (contracted "
        "total it could still absorb), plus its utilisation percentage."
    ),
)
def check_allotment_headroom_tool(params: CheckAllotmentHeadroomParams) -> dict[str, Any]:
    return check_allotment_headroom(_reference_world(), params.allotment_id)


class MoveAllotmentRoomsParams(BaseModel):
    from_allotment_id: str
    to_allotment_id: str
    rooms: int


def move_allotment_rooms(
    world: TravelWorld, *, from_allotment_id: str, to_allotment_id: str, rooms: int
) -> dict[str, Any]:
    """Planning: would moving `rooms` from the donor to the recipient
    allotment be feasible? Mirrors `adjust_package_allotment` /
    `move_hotel_allotment`'s own two headroom checks exactly, without
    moving anything."""
    donor = world.allotments.get(from_allotment_id)
    recipient = world.allotments.get(to_allotment_id)
    if donor is None or recipient is None:
        return {"feasible": False, "reason": "unknown donor or recipient allotment"}
    donor_headroom = donor.allotment - donor.reserved
    recipient_headroom = recipient.total - recipient.allotment
    donor_ok = rooms <= donor_headroom
    recipient_ok = rooms <= recipient_headroom
    feasible = donor_ok and recipient_ok
    return {
        "feasible": feasible,
        "donor_ok": donor_ok,
        "recipient_ok": recipient_ok,
        "donor_headroom": donor_headroom,
        "recipient_headroom": recipient_headroom,
        "resulting_donor_allotment": donor.allotment - rooms if donor_ok else donor.allotment,
        "resulting_recipient_allotment": (
            recipient.allotment + rooms if recipient_ok else recipient.allotment
        ),
    }


@define_tool(
    name="travel_operations_move_allotment_rooms",
    description=(
        "Plan (without committing) whether moving a room count from a "
        "donor to a recipient hotel allotment would respect both the "
        "donor's headroom and the recipient's contracted total."
    ),
)
def move_allotment_rooms_tool(params: MoveAllotmentRoomsParams) -> dict[str, Any]:
    return move_allotment_rooms(
        _reference_world(),
        from_allotment_id=params.from_allotment_id,
        to_allotment_id=params.to_allotment_id,
        rooms=params.rooms,
    )


# ---------------------------------------------------------------------------
# 3. flight-disruption-recovery (hero)
# ---------------------------------------------------------------------------


class CheckFlightDisruptionParams(BaseModel):
    flight_id: str


def check_flight_disruption(world: TravelWorld, flight_id: str) -> dict[str, Any]:
    """Query: a flight's status, any open cancellation disruption tied to
    it, and how many live bookings it affects."""
    flight = world.flights.get(flight_id)
    if flight is None:
        return {"found": False, "flight_id": flight_id, "reason": "unknown flight"}
    open_disruption = next(
        (
            disruption
            for disruption in world.disruptions.values()
            if disruption.resource_id == flight_id
            and disruption.kind == "flight_cancellation"
            and disruption.status == "reported"
        ),
        None,
    )
    affected_booking_ids = sorted(
        booking.id
        for booking in world.bookings.values()
        if booking.flight_id == flight_id and booking.status in ("confirmed", "deposit_paid", "paid")
    )
    return {
        "found": True,
        "flight_id": flight.id,
        "status": flight.status,
        "open_disruption_id": open_disruption.id if open_disruption else None,
        "affected_booking_ids": affected_booking_ids,
        "affected_booking_count": len(affected_booking_ids),
    }


@define_tool(
    name="travel_operations_check_flight_disruption",
    description=(
        "Check a flight's status, any open cancellation disruption tied "
        "to it, and the live bookings it would strand if cancelled."
    ),
)
def check_flight_disruption_tool(params: CheckFlightDisruptionParams) -> dict[str, Any]:
    return check_flight_disruption(_reference_world(), params.flight_id)


class ReaccommodateBookingParams(BaseModel):
    booking_id: str
    to_flight_id: str
    to_transfer_id: str


def reaccommodate_booking(
    world: TravelWorld, *, booking_id: str, to_flight_id: str, to_transfer_id: str
) -> dict[str, Any]:
    """Planning: would reaccommodating `booking_id` onto the replacement
    flight/transfer be feasible? Mirrors `reaccommodate_travellers`'s own
    capacity checks exactly, without moving anything."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"feasible": False, "reason": "unknown booking"}
    to_flight = world.flights.get(to_flight_id)
    to_transfer = world.transfers.get(to_transfer_id)
    if to_flight is None or to_transfer is None:
        return {"feasible": False, "reason": "unknown replacement flight or transfer"}
    party = world.parties.get(booking.party_id)
    if party is None:
        return {"feasible": False, "reason": "unknown travelling party"}
    flight_ok = to_flight.reserved + party.size <= to_flight.capacity
    transfer_ok = to_transfer.reserved + party.size <= to_transfer.capacity
    return {
        "feasible": flight_ok and transfer_ok,
        "flight_capacity_ok": flight_ok,
        "transfer_capacity_ok": transfer_ok,
        "party_size": party.size,
        "flight_headroom": to_flight.capacity - to_flight.reserved,
        "transfer_headroom": to_transfer.capacity - to_transfer.reserved,
    }


@define_tool(
    name="travel_operations_reaccommodate_booking",
    description=(
        "Plan (without committing) whether a booking's travelling party "
        "would fit a replacement flight and transfer's remaining "
        "capacity."
    ),
)
def reaccommodate_booking_tool(params: ReaccommodateBookingParams) -> dict[str, Any]:
    return reaccommodate_booking(
        _reference_world(),
        booking_id=params.booking_id,
        to_flight_id=params.to_flight_id,
        to_transfer_id=params.to_transfer_id,
    )


# ---------------------------------------------------------------------------
# 5 / 6 / 8. cancellation-refund + payment-exception + proactive-customer-care
# ---------------------------------------------------------------------------


class CheckBookingStatusParams(BaseModel):
    booking_id: str


def check_booking_status(world: TravelWorld, booking_id: str) -> dict[str, Any]:
    """Query: a booking's current status plus its payment and refund
    history -- shared by cancellation-refund, payment-exception and
    proactive-customer-care, which all act on a booking's live state."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"found": False, "booking_id": booking_id, "reason": "unknown booking"}
    payments = sorted(
        (payment.id for payment in world.payments.values() if payment.booking_id == booking_id),
    )
    refunds = sorted(
        (refund.id for refund in world.refunds.values() if refund.booking_id == booking_id),
    )
    paid_to_date = sum(
        payment.amount for payment in world.payments.values() if payment.booking_id == booking_id
    )
    return {
        "found": True,
        "booking_id": booking.id,
        "status": booking.status,
        "total_price": booking.total_price,
        "paid_to_date": paid_to_date,
        "outstanding_balance": booking.total_price - paid_to_date,
        "party_id": booking.party_id,
        "flight_id": booking.flight_id,
        "allotment_id": booking.allotment_id,
        "transfer_id": booking.transfer_id,
        "payment_ids": payments,
        "refund_ids": refunds,
    }


@define_tool(
    name="travel_operations_check_booking_status",
    description=(
        "Check a booking's current status, outstanding balance and its "
        "payment/refund history."
    ),
)
def check_booking_status_tool(params: CheckBookingStatusParams) -> dict[str, Any]:
    return check_booking_status(_reference_world(), params.booking_id)


class ReleaseBookingCapacityParams(BaseModel):
    booking_id: str


def release_booking_capacity(world: TravelWorld, booking_id: str) -> dict[str, Any]:
    """Planning: what flight/allotment/transfer capacity would be freed
    if `booking_id` were cancelled or released? Mirrors
    `cancel_and_refund_booking` / `resolve_payment_exception`'s own
    release maths exactly, without releasing anything."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"feasible": False, "reason": "unknown booking"}
    if booking.status == "cancelled":
        return {
            "feasible": False,
            "reason": "booking already cancelled: capacity already released",
            "already_cancelled": True,
        }
    party = world.parties.get(booking.party_id)
    party_size = party.size if party is not None else 0
    return {
        "feasible": True,
        "booking_id": booking.id,
        "flight_id": booking.flight_id,
        "allotment_id": booking.allotment_id,
        "transfer_id": booking.transfer_id,
        "would_release_flight_seats": party_size,
        "would_release_hotel_rooms": booking.rooms,
        "would_release_transfer_seats": party_size,
    }


@define_tool(
    name="travel_operations_release_booking_capacity",
    description=(
        "Plan (without committing) the flight, hotel allotment and "
        "transfer capacity that would be released if a booking were "
        "cancelled or its payment exception resolved by release."
    ),
)
def release_booking_capacity_tool(params: ReleaseBookingCapacityParams) -> dict[str, Any]:
    return release_booking_capacity(_reference_world(), params.booking_id)


# ---------------------------------------------------------------------------
# 7. destination-operations
# ---------------------------------------------------------------------------


class CheckTransferRiskParams(BaseModel):
    transfer_id: str


def check_transfer_risk(world: TravelWorld, transfer_id: str) -> dict[str, Any]:
    """Query: a transfer's status, any open arrival-risk disruption tied
    to it, and the live bookings it currently carries."""
    transfer = world.transfers.get(transfer_id)
    if transfer is None:
        return {"found": False, "transfer_id": transfer_id, "reason": "unknown transfer"}
    open_disruption = next(
        (
            disruption
            for disruption in world.disruptions.values()
            if disruption.resource_id == transfer_id
            and disruption.kind == "transfer_arrival_risk"
            and disruption.status == "reported"
        ),
        None,
    )
    carried_booking_ids = sorted(
        booking.id for booking in world.bookings.values() if booking.transfer_id == transfer_id
    )
    return {
        "found": True,
        "transfer_id": transfer.id,
        "status": transfer.status,
        "capacity": transfer.capacity,
        "reserved": transfer.reserved,
        "open_disruption_id": open_disruption.id if open_disruption else None,
        "carried_booking_ids": carried_booking_ids,
    }


@define_tool(
    name="travel_operations_check_transfer_risk",
    description=(
        "Check a resort transfer's status, any open arrival-risk "
        "disruption tied to it, and the live bookings it currently "
        "carries."
    ),
)
def check_transfer_risk_tool(params: CheckTransferRiskParams) -> dict[str, Any]:
    return check_transfer_risk(_reference_world(), params.transfer_id)


class DispatchReplacementTransferParams(BaseModel):
    transfer_id: str


def dispatch_replacement_transfer(world: TravelWorld, transfer_id: str) -> dict[str, Any]:
    """Planning: the replacement transfer id `dispatch_replacement_transfer`
    would create or reuse (`TRF-REPL-<transfer_id>`, the exact convention
    the real command handler uses), and whether one already exists."""
    transfer = world.transfers.get(transfer_id)
    if transfer is None:
        return {"feasible": False, "reason": "unknown transfer"}
    replacement_id = f"TRF-REPL-{transfer_id}"
    existing = world.transfers.get(replacement_id)
    return {
        "feasible": True,
        "transfer_id": transfer.id,
        "planned_replacement_id": replacement_id,
        "replacement_already_exists": existing is not None,
        "replacement_status": existing.status if existing is not None else None,
    }


@define_tool(
    name="travel_operations_dispatch_replacement_transfer",
    description=(
        "Plan (without committing) the replacement transfer id a "
        "dispatch would create or reuse for an at-risk transfer."
    ),
)
def dispatch_replacement_transfer_tool(params: DispatchReplacementTransferParams) -> dict[str, Any]:
    return dispatch_replacement_transfer(_reference_world(), params.transfer_id)


# ---------------------------------------------------------------------------
# 8. proactive-customer-care
# ---------------------------------------------------------------------------


class IssueCareActionParams(BaseModel):
    booking_id: str
    kind: str
    amount_gbp: float = 0.0


def issue_care_action(
    world: TravelWorld, *, booking_id: str, kind: str, amount_gbp: float = 0.0
) -> dict[str, Any]:
    """Planning: would issuing a `kind` customer-care action (with a
    bounded `amount_gbp` goodwill gesture) against `booking_id` be a
    well-formed request? Mirrors `issue_customer_care_action`'s own kind
    and non-negative-amount checks, without issuing anything."""
    booking = world.bookings.get(booking_id)
    if booking is None:
        return {"feasible": False, "reason": "unknown booking"}
    if kind not in ("notification", "goodwill_gesture"):
        return {"feasible": False, "reason": f"unknown customer care action kind {kind!r}"}
    if amount_gbp < 0:
        return {"feasible": False, "reason": "amount_gbp must not be negative"}
    return {
        "feasible": True,
        "booking_id": booking.id,
        "party_id": booking.party_id,
        "kind": kind,
        "amount_gbp": amount_gbp,
    }


@define_tool(
    name="travel_operations_issue_care_action",
    description=(
        "Plan (without committing) a customer-care notification or "
        "bounded goodwill gesture against a booking."
    ),
)
def issue_care_action_tool(params: IssueCareActionParams) -> dict[str, Any]:
    return issue_care_action(
        _reference_world(), booking_id=params.booking_id, kind=params.kind, amount_gbp=params.amount_gbp
    )


TOOLS: dict[str, Callable[..., Any]] = {
    "travel_operations_check_quote_offer": check_quote_offer_tool,
    "travel_operations_reserve_package_capacity": reserve_package_capacity_tool,
    "travel_operations_check_allotment_headroom": check_allotment_headroom_tool,
    "travel_operations_move_allotment_rooms": move_allotment_rooms_tool,
    "travel_operations_check_flight_disruption": check_flight_disruption_tool,
    "travel_operations_reaccommodate_booking": reaccommodate_booking_tool,
    "travel_operations_check_booking_status": check_booking_status_tool,
    "travel_operations_release_booking_capacity": release_booking_capacity_tool,
    "travel_operations_check_transfer_risk": check_transfer_risk_tool,
    "travel_operations_dispatch_replacement_transfer": dispatch_replacement_transfer_tool,
    "travel_operations_issue_care_action": issue_care_action_tool,
}
