"""Projection: employee-transfer (compose-domain v4 codegen).

Auto-generated by docs/superpowers/skills/compose-domain/sub-skills/author-entity-projection/codegen.py
from the brief at docs/superpowers/specs/employee-transfer-brief.yaml.
DO NOT EDIT BY HAND — regenerate via `compose-domain --re-projection-only`.
"""
from __future__ import annotations

from api.server.services.entity_projections import (
    DecisionWrite,
    EntityWrite,
    RelWrite,
    build_decision,
    slug,
)
from api.shared.types import Workflow

WORKFLOW_TYPE = "employee-transfer"


def project(workflow: Workflow) -> list[EntityWrite | RelWrite | DecisionWrite]:
    p = workflow.payload or {}
    sw = (workflow.id,)
    ops: list[EntityWrite | RelWrite | DecisionWrite] = []

    person_0_id = f"PERSON-transferee-" + slug(str(p.get('employee_id') or "unknown"))
    ops.append(EntityWrite(
        kind='Person',
        id=person_0_id,
        attrs={
        "kind": 'transferee',
        'department': str(p.get('current_cost_centre') or ""),
    },
        source_workflows=sw,
    ))
    org_1_id = f"ORG-source_org-" + slug(str(p.get('source_org_id') or "unknown"))
    ops.append(EntityWrite(
        kind='Organisation',
        id=org_1_id,
        attrs={
        "kind": 'source_org',
        'name': str(p.get('source_org_name') or ""),
    },
        source_workflows=sw,
    ))
    org_2_id = f"ORG-target_org-" + slug(str(p.get('target_org_id') or "unknown"))
    ops.append(EntityWrite(
        kind='Organisation',
        id=org_2_id,
        attrs={
        "kind": 'target_org',
        'name': str(p.get('target_org_name') or ""),
    },
        source_workflows=sw,
    ))
    period_3_id = f"PERIOD-transfer_window-" + slug(str(p.get('effective_date') or "unknown"))
    ops.append(EntityWrite(
        kind='Period',
        id=period_3_id,
        attrs={
        "kind": 'transfer_window',
        'starts': str(p.get('effective_date') or ""),
    },
        source_workflows=sw,
    ))

    return ops
