"""Projection: training-request (compose-domain v4 codegen).

Auto-generated by docs/superpowers/skills/compose-domain/sub-skills/author-entity-projection/codegen.py
from the brief at docs/superpowers/specs/training-request-brief.yaml.
DO NOT EDIT BY HAND — regenerate via `compose-domain --re-projection-only`.
"""
from __future__ import annotations

from api.server.services.entity_projections import (
    DecisionWrite,
    EntityWrite,
    RelWrite,
    build_decision,
    slug,
)
from api.shared.types import Workflow

WORKFLOW_TYPE = "training-request"


def project(workflow: Workflow) -> list[EntityWrite | RelWrite | DecisionWrite]:
    p = workflow.payload or {}
    sw = (workflow.id,)
    ops: list[EntityWrite | RelWrite | DecisionWrite] = []

    person_0_id = f"PERSON-requester-" + slug(str(p.get('employee_id') or "unknown"))
    ops.append(EntityWrite(
        kind='Person',
        id=person_0_id,
        attrs={
            "kind": 'requester',
            'department': str(p.get('department') or ""),
        },
        source_workflows=sw,
    ))
    money_1_id = f"MONEY-training-cost-" + slug(str(p.get('estimated_cost_id') or "unknown"))
    ops.append(EntityWrite(
        kind='Money',
        id=money_1_id,
        attrs={
            "kind": 'training-cost',
            'currency': str(p.get('currency') or ""),
        },
        source_workflows=sw,
    ))
    period_2_id = f"PERIOD-training-window-" + slug(str(p.get('target_start_date') or "unknown"))
    ops.append(EntityWrite(
        kind='Period',
        id=period_2_id,
        attrs={
            "kind": 'training-window',
            'starts': str(p.get('target_start_date') or ""),
            'ends': str(p.get('target_end_date') or ""),
        },
        source_workflows=sw,
    ))

    return ops
