"""Pure, framework-free phase-plan execution engine (generated by
verticals.travel.generator.durable_templates).

Generic machinery shared by all eight orchestrators in
`orchestrators.py`: a `PhaseStep` names one phase of a process's real
`PhaseSpec` sequence and carries the real callable that executes it;
`run_phase_plan` threads each step's result dict into the next step's
`context` and halts immediately -- without running later steps -- the
moment a `"hitl"` step reports `{"wait": True}`, exactly like a real
human-in-the-loop gate would. Task 6 binds/enhances the
flight-disruption-recovery hero onto real Azure Durable Functions
triggers; this module stays the pure, dependency-free core it wraps.

Do not hand-edit -- change verticals.travel.generator.durable_templates
and regenerate via `uv run python -m verticals.travel.generator`.
"""
from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Any

PhaseRunner = Callable[[Any, Mapping[str, Any]], dict[str, Any]]


@dataclass(frozen=True)
class PhaseStep:
    """One phase of a process's real phase plan: its name, its
    `PhaseSpec.kind` ("deterministic" | "agent" | "hitl"), and the real
    callable -- `run(world, context) -> dict` -- that executes it."""

    name: str
    kind: str
    run: PhaseRunner


@dataclass(frozen=True)
class PhaseOutcome:
    """One executed phase's recorded name, kind and result."""

    name: str
    kind: str
    result: dict[str, Any]


@dataclass(frozen=True)
class PhasePlanResult:
    """The full, ordered record of a phase plan's real execution."""

    workflow_type: str
    outcomes: tuple[PhaseOutcome, ...]
    halted_for_hitl: bool
    context: dict[str, Any]


def run_phase_plan(
    world: Any,
    workflow_type: str,
    steps: tuple[PhaseStep, ...],
    *,
    initial_context: Mapping[str, Any] | None = None,
) -> PhasePlanResult:
    """Execute `steps` in order against `world`, threading each step's
    result into the next as `context`. A `"hitl"` step that reports
    `{"wait": True}` halts the plan immediately: later phases never run,
    exactly as a real pending human approval would block a Durable
    Functions orchestration.
    """
    outcomes: list[PhaseOutcome] = []
    context: dict[str, Any] = dict(initial_context) if initial_context else {}
    halted = False
    for step in steps:
        result = step.run(world, context)
        outcomes.append(PhaseOutcome(name=step.name, kind=step.kind, result=result))
        context = {**context, **result}
        if step.kind == "hitl" and context.get("wait"):
            halted = True
            break
    return PhasePlanResult(
        workflow_type=workflow_type, outcomes=tuple(outcomes), halted_for_hitl=halted, context=context
    )
