"""Codegen for author-decision-mapping (TASK-016).

Pure function :func:`render_cypher` that turns one decision dict into a
``.cypher`` file body the Phase 3 persona reasoning loop will execute
with bind params ``$entity_id`` + ``$limit``.

Pure function :func:`render_filename` returns
``<workflow_type>_<phase>.cypher`` (kebab + snake — matches the
plan's REQ-003 path scheme).
"""
from __future__ import annotations

__all__ = ["render_cypher", "render_filename"]


_TEMPLATE = """\
// Auto-generated by compose-domain v4 author-decision-mapping codegen.
// Workflow: {workflow_type}
// Phase:    {phase}
// Persona:  {persona}
//
// Bind params:
//   $entity_id  — entity id the current workflow's persona is reasoning about
//   $limit      — max precedents to return (caller chooses)
MATCH (d:Decision)-[:DECIDED_ON]->(e {{id: $entity_id}})
WHERE d.persona_role = '{persona}'
  AND d.workflow_type = '{workflow_type}'
RETURN d
ORDER BY d.decided_at DESC
LIMIT $limit
"""


def render_filename(brief: dict, decision: dict) -> str:
    workflow_type = brief["domain"]["workflow_type"]
    phase = decision["phase"]
    return f"{workflow_type}_{phase}.cypher"


def render_cypher(brief: dict, decision: dict) -> str:
    return _TEMPLATE.format(
        workflow_type=brief["domain"]["workflow_type"],
        phase=decision["phase"],
        persona=decision["persona"],
    )
