"""Employee transfer Segment B — eligibility check.

Generated by compose-domain for `kind: agent` phases (segments-by-default).
Opens ONE CopilotSession loaded with the eligibility-checker skill plus
the policy_search / delegated_authority / vendor_registry MCPs; the
model picks the invocation order. The orchestrator owns segment
boundaries, HITL gates, retry, and audit.

Tool wiring follows the v3 fleet pattern (e.g.
`api/functions/graphs/executors/agents/agent_fleet_employee_onboarding_access_drafter.py`):
the `@define_tool`-decorated functions are imported here and passed
explicitly via `tools=[...]`. The SDK does NOT auto-discover MCP tools
from `skill_directories` (KR-5 in
`docs/superpowers/plans/2026-05-21-compose-domain-findings-employee-transfer.md`).
"""
from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from api.server.mcp_tools.policy_search import policy_search_tool
from api.server.mcp_tools.delegated_authority import (
    delegated_authority_check_authority_tool,
    delegated_authority_resolve_approver_tool,
)
from api.server.mcp_tools.vendor_registry import vendor_registry_lookup_vendor_tool


_SEGMENT_B_SKILLS: list[str] = [
    "fleet-employee-transfer-transfer-eligibility-checker",
]
_SEGMENT_B_MCPS: list[str] = [
    "policy_search",
    "delegated_authority_check_authority",
    "delegated_authority_resolve_approver",
    "vendor_registry_lookup_vendor",
]


class SegmentBOutput(BaseModel):
    verdict: Literal["eligible", "blocked"]
    blocker: str | None = Field(
        default=None,
        description=(
            "Snake-case label naming the first failing gate when verdict "
            "is 'blocked' (e.g. 'visa', 'notice_period', 'releasing_authority', "
            "'receiving_authority', 'target_entity_standing'). Null when eligible."
        ),
    )
    reason: str = Field(
        description="One-sentence prose rationale naming the deciding gate.",
    )

    @field_validator("blocker")
    @classmethod
    def _blocker_only_when_blocked(cls, v: str | None, info) -> str | None:
        verdict = info.data.get("verdict")
        if verdict == "blocked" and not v:
            raise ValueError("blocker: required when verdict == 'blocked'")
        if verdict == "eligible" and v:
            raise ValueError("blocker: must be null when verdict == 'eligible'")
        return v


def _skills_dir() -> Path:
    """Return the on-disk skills directory used by the GHCP SDK to
    auto-discover SKILL.md files. Mirrors `_wrapper.py:_SKILLS_DIR`."""
    return Path(__file__).resolve().parents[2] / "server" / "skills"


def _build_segment_b_prompt(
    enriched: dict,
    prior_validator_error: str | None = None,
) -> str:
    """Goal-shaped prompt. Names the deliverable + the available
    skills/MCPs by name; does NOT prescribe invocation order — that's
    the agentic loop's job.

    If the previous attempt failed validation, append the validator
    error so the model can adapt within the retry."""
    schema = SegmentBOutput.model_json_schema()
    summary = {
        k: enriched.get(k) for k in (
            "transfer_intake",
            "employee_lookup",
        ) if k in enriched
    }
    parts: list[str] = [
        "Decide whether the proposed employee transfer is eligible.",
        "",
        "Workflow context:",
        repr(summary),
        "",
        f"Available skills (load on demand): {', '.join(_SEGMENT_B_SKILLS)}",
        f"Available MCPs (call as needed): {', '.join(_SEGMENT_B_MCPS)}",
        "",
        "Deliverable — return ONE JSON object matching this schema:",
        repr(schema),
        "",
        "Return only the JSON object. No preamble.",
    ]
    if prior_validator_error:
        parts.extend([
            "",
            "Your previous attempt failed validation with the following error.",
            "Produce a valid output this time:",
            prior_validator_error,
        ])
    return "\n".join(parts)


async def run_segment_b(input: dict) -> dict:
    """Open one agent session loaded with every Segment B skill, send
    the goal-shaped prompt, return the parsed response."""
    from api.functions.graphs.executors.agents._wrapper import run_agent_session

    skills_root = _skills_dir()
    skill_dirs = [skills_root / s for s in _SEGMENT_B_SKILLS]
    prior_err = input.get("prior_validator_error")
    prompt = _build_segment_b_prompt(input, prior_validator_error=prior_err)

    return await run_agent_session(
        prompt=prompt,
        tools=[
            policy_search_tool,
            delegated_authority_check_authority_tool,
            delegated_authority_resolve_approver_tool,
            vendor_registry_lookup_vendor_tool,
        ],
        skill_dir=skill_dirs[0],
        skill_directories=skill_dirs[1:],
        skill_label="employee-transfer-segment-b",
        workflow_id=input.get("workflow_id"),
        model="gpt-4.1",
    )
