"""Employee transfer Segment D — compensation remap.

Generated by compose-domain for `kind: agent` phases (segments-by-default).
Opens ONE CopilotSession loaded with the compensation-remapper skill
plus the workday_hr_employee / contract_repository MCPs; the model picks
the invocation order.

Tool wiring follows the v3 fleet pattern (e.g.
`api/functions/graphs/executors/agents/agent_fleet_employee_onboarding_access_drafter.py`):
the `@define_tool`-decorated functions are imported here and passed
explicitly via `tools=[...]`. The SDK does NOT auto-discover MCP tools
from `skill_directories`, contrary to the misleading comment in
`hiring_b.py` (KR-5 from
`docs/superpowers/plans/2026-05-21-compose-domain-findings-employee-transfer.md`).
"""
from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from api.server.mcp_tools.workday_hr_employee import (
    workday_hr_employee_get_employee_tool,
)
from api.server.mcp_tools.contract_repository import (
    contract_repository_get_contract_tool,
    contract_repository_find_similar_tool,
)


_SEGMENT_D_SKILLS: list[str] = [
    "fleet-employee-transfer-compensation-remapper",
]
_SEGMENT_D_MCPS: list[str] = [
    "workday_hr_employee_get_employee",
    "contract_repository_get_contract",
    "contract_repository_find_similar",
]


class SegmentDOutput(BaseModel):
    proposed_salary: float = Field(
        gt=0.0,
        description="Proposed annual salary in the target entity's currency.",
    )
    currency: str = Field(
        min_length=3, max_length=3,
        description="ISO-4217 currency code for the proposed salary.",
    )
    delta_pct: float = Field(
        description=(
            "Percentage change vs current salary, positive for uplift. "
            "Used by the HR Director gate's 10% threshold."
        ),
    )
    contract_id: str = Field(
        min_length=1,
        description="Identifier of the contract draft generated in the repo.",
    )
    rationale: str = Field(
        description="One-line rationale for the proposed comp remap.",
    )

    @field_validator("currency")
    @classmethod
    def _currency_upper(cls, v: str) -> str:
        if not v.isalpha():
            raise ValueError("currency: must be alphabetic ISO-4217 code")
        return v.upper()


def _skills_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "server" / "skills"


def _build_segment_d_prompt(
    enriched: dict,
    prior_validator_error: str | None = None,
) -> str:
    schema = SegmentDOutput.model_json_schema()
    summary = {
        k: enriched.get(k) for k in (
            "transfer_intake",
            "employee_lookup",
            "eligibility_check",
            "manager_approval_decision",
        ) if k in enriched
    }
    parts: list[str] = [
        (
            "Remap the transferring employee's compensation against the "
            "target entity's comp band, draft a new contract, and emit "
            "the proposed salary + delta + contract id."
        ),
        "",
        "Workflow context:",
        repr(summary),
        "",
        f"Available skills (load on demand): {', '.join(_SEGMENT_D_SKILLS)}",
        f"Available MCPs (call as needed): {', '.join(_SEGMENT_D_MCPS)}",
        "",
        "Deliverable — return ONE JSON object matching this schema:",
        repr(schema),
        "",
        "Return only the JSON object. No preamble.",
    ]
    if prior_validator_error:
        parts.extend([
            "",
            "Your previous attempt failed validation with the following error.",
            "Produce a valid output this time:",
            prior_validator_error,
        ])
    return "\n".join(parts)


async def run_segment_d(input: dict) -> dict:
    from api.functions.graphs.executors.agents._wrapper import run_agent_session

    skills_root = _skills_dir()
    skill_dirs = [skills_root / s for s in _SEGMENT_D_SKILLS]
    prior_err = input.get("prior_validator_error")
    prompt = _build_segment_d_prompt(input, prior_validator_error=prior_err)

    return await run_agent_session(
        prompt=prompt,
        tools=[
            workday_hr_employee_get_employee_tool,
            contract_repository_get_contract_tool,
            contract_repository_find_similar_tool,
        ],
        skill_dir=skill_dirs[0],
        skill_directories=skill_dirs[1:],
        skill_label="employee-transfer-segment-d",
        workflow_id=input.get("workflow_id"),
        model="gpt-4.1",
    )
