"""Training request Segment B — eligibility & catalogue match.

Generated by compose-domain for `kind: agent` phases (segments-by-default).
Opens ONE CopilotSession loaded with the eligibility-and-catalogue-matcher
skill plus the workday_hr_employee / employee_history / learning_catalogue
MCPs; the model picks the invocation order. The orchestrator owns segment
boundaries, HITL gates, retry, and audit.

Mirrors api/functions/segments/hiring_b.py (canonical example).
"""
from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from api.server.mcp_tools.workday_hr_employee import workday_hr_employee_get_employee_tool
from api.server.mcp_tools.employee_history import employee_history_tool
from api.server.mcp_tools.learning_catalogue import (
    learning_catalogue_match_course_tool,
)


_SEGMENT_B_SKILLS: list[str] = [
    "fleet-training-request-eligibility-and-catalogue-matcher",
]
_SEGMENT_B_MCPS: list[str] = [
    "workday_hr_employee",
    "employee_history",
    "learning_catalogue",
]


class SegmentBOutput(BaseModel):
    verdict: Literal["eligible", "ineligible"]
    course_id: str = Field(
        description=(
            "Catalogue course id (exact or closest alternative). Always "
            "populated — even when ineligible, the matcher returns the "
            "best match so the HR director sees the underlying option."
        ),
    )
    vendor: str = Field(
        description="Vendor that owns the matched course.",
    )
    confirmed_cost_gbp: float = Field(
        ge=0,
        description="Confirmed cost from the catalogue match (not the requester's estimate).",
    )
    course_start_date: str = Field(
        description="Confirmed start date from the catalogue match (ISO YYYY-MM-DD).",
    )
    rationale: str = Field(
        description=(
            "One-sentence prose rationale citing the deciding rule "
            "(eligibility gate name when ineligible; catalogue hit when eligible)."
        ),
    )

    @field_validator("rationale")
    @classmethod
    def _rationale_nonempty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("rationale: must be a non-empty sentence")
        return v


def _skills_dir() -> Path:
    """Return the on-disk skills directory used by the GHCP SDK to
    auto-discover SKILL.md files. Mirrors `_wrapper.py:_SKILLS_DIR`."""
    return Path(__file__).resolve().parents[2] / "server" / "skills"


def _build_segment_b_prompt(
    enriched: dict,
    prior_validator_error: str | None = None,
) -> str:
    """Goal-shaped prompt. Names the deliverable + the available
    skills/MCPs by name; does NOT prescribe invocation order — that's
    the agentic loop's job.

    If the previous attempt failed validation, append the validator
    error so the model can adapt within the retry."""
    schema = SegmentBOutput.model_json_schema()
    summary = {
        k: enriched.get(k) for k in (
            "request_intake",
        ) if k in enriched
    }
    parts: list[str] = [
        "Decide whether the requesting employee is eligible for the training "
        "request and match the request against the L&D catalogue.",
        "",
        "Workflow context:",
        repr(summary),
        "",
        f"Available skills (load on demand): {', '.join(_SEGMENT_B_SKILLS)}",
        f"Available MCPs (call as needed): {', '.join(_SEGMENT_B_MCPS)}",
        "",
        "Deliverable — return ONE JSON object matching this schema:",
        repr(schema),
        "",
        "Return only the JSON object. No preamble.",
    ]
    if prior_validator_error:
        parts.extend([
            "",
            "Your previous attempt failed validation with the following error.",
            "Produce a valid output this time:",
            prior_validator_error,
        ])
    return "\n".join(parts)


async def run_segment_b(input: dict) -> dict:
    """Open one agent session loaded with every Segment B skill, send
    the goal-shaped prompt, return the parsed response."""
    from api.functions.graphs.executors.agents._wrapper import run_agent_session

    skills_root = _skills_dir()
    skill_dirs = [skills_root / s for s in _SEGMENT_B_SKILLS]
    prior_err = input.get("prior_validator_error")
    prompt = _build_segment_b_prompt(input, prior_validator_error=prior_err)

    return await run_agent_session(
        prompt=prompt,
        tools=[
            workday_hr_employee_get_employee_tool,
            employee_history_tool,
            learning_catalogue_match_course_tool,
        ],
        skill_dir=skill_dirs[0],
        skill_directories=skill_dirs[1:],
        skill_label="training-request-segment-b",
        workflow_id=input.get("workflow_id"),
        instance_id=input.get("instance_id"),
        covered_phases=input.get("covered_phases"),
        model="gpt-4.1",
    )
