import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// web/client/components/apex/ExecutionTimelineTab.tsx
import { useState } from "react";
import { useFleetManagerStream } from "../../hooks/useFleetManagerStream";
function statusChip(code) {
    if (code === 0)
        return _jsx("span", { className: "chip-info", children: "PENDING" });
    if (code >= 200 && code < 300)
        return _jsx("span", { className: "chip-success", children: code });
    if (code >= 400)
        return _jsx("span", { className: "chip-danger", children: code });
    return _jsx("span", { className: "chip-info", children: code });
}
export default function ExecutionTimelineTab({ mcpCalls, workflowId, onLogAction }) {
    const [selected, setSelected] = useState(mcpCalls.length > 0 ? 0 : null);
    const fmEvents = useFleetManagerStream();
    const sel = selected != null ? mcpCalls[selected] : null;
    return (_jsxs("div", { className: "grid grid-cols-3 gap-4", "data-testid": "execution-timeline", children: [_jsxs("div", { className: "col-span-2 space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "text-sm text-slate-600", children: ["Run ID: ", _jsx("span", { className: "font-mono", children: workflowId })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { className: "btn-secondary", "data-testid": "rollback-workflow", onClick: () => onLogAction("workflow.rollback-requested"), children: "Rollback" }), _jsx("button", { className: "btn-secondary", "data-testid": "fork-workflow", onClick: () => onLogAction("workflow.fork-requested"), children: "Fork Workflow" })] })] }), mcpCalls.length === 0 && (_jsx("div", { className: "panel panel-body text-xs text-slate-500", children: "Timeline populates as the orchestration fires MCP calls." })), mcpCalls.map((c, i) => {
                        const failed = c.statusCode >= 400;
                        return (_jsxs("button", { onClick: () => setSelected(i), "data-testid": `timeline-step-${i}`, className: `panel w-full text-left panel-body
                      ${i === selected ? "ring-2 ring-blue-400" : ""}
                      ${failed ? "border-red-300" : ""}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-[10px] font-mono text-slate-500", children: ["STEP ", String(i + 1).padStart(2, "0")] }), _jsxs("span", { className: "text-sm font-semibold text-slate-800", children: [c.method, " ", new URL(c.url).pathname] }), _jsx("span", { className: "ml-auto", children: statusChip(c.statusCode) })] }), _jsxs("div", { className: "text-[11px] text-slate-500 mt-1", children: ["tool: ", c.tool, " \u00B7 ", c.durationMs, " ms \u00B7 ", new Date(c.timestamp * 1000).toLocaleTimeString()] }), failed && (_jsxs("div", { className: "flex gap-2 mt-2", children: [_jsx("button", { onClick: e => { e.stopPropagation(); onLogAction(`step.${i}.fork`); }, className: "btn-secondary text-xs", children: "Fork Step & Re-run" }), _jsx("button", { onClick: e => { e.stopPropagation(); onLogAction(`step.${i}.rollback`); }, className: "btn-secondary text-xs", children: "Rollback to here" })] }))] }, i));
                    })] }), _jsxs("div", { className: "col-span-1 space-y-3", children: [_jsxs("div", { className: "panel", "data-testid": "api-configuration", children: [_jsx("div", { className: "panel-header", children: "API Configuration" }), _jsxs("div", { className: "panel-body", children: [!sel && _jsx("div", { className: "text-xs text-slate-500", children: "select a step" }), sel && (_jsxs(_Fragment, { children: [_jsx("div", { className: "text-[11px] uppercase text-slate-500 mb-1", children: "Request" }), _jsx("pre", { className: "text-[11px] bg-slate-50 border border-slate-200 rounded p-2 whitespace-pre-wrap break-all max-h-48 overflow-auto", children: JSON.stringify(sel.request, null, 2) }), _jsx("div", { className: "text-[11px] uppercase text-slate-500 mb-1 mt-2", children: "Response" }), _jsx("pre", { className: "text-[11px] bg-slate-50 border border-slate-200 rounded p-2 whitespace-pre-wrap break-all max-h-48 overflow-auto", children: JSON.stringify(sel.response, null, 2) })] }))] })] }), _jsxs("div", { className: "panel", "data-testid": "agent-thought-stream", children: [_jsx("div", { className: "panel-header", children: "Agent Thought Stream" }), _jsxs("div", { className: "panel-body space-y-1.5", children: [fmEvents.length === 0 && _jsx("div", { className: "text-xs text-slate-500", children: "no agent activity" }), fmEvents.slice(-6).map((e, i) => (_jsxs("div", { className: "text-xs", children: [_jsx("div", { className: "text-slate-800 font-medium", children: e.kind }), _jsx("div", { className: "text-slate-500 break-all", children: e.data ? JSON.stringify(e.data).slice(0, 140) : "" })] }, i)))] })] })] })] }));
}
